### ISSUE TITLE
AssetPathEntity.all.assetList 会报错

### ISSUE THREAD

**Issue by hyz1992** [CaiJingLong/flutter_photo_manager#10]
好吧，又是我，非常感谢你的及时响应！我认为这个项目有广泛的实用价值，也许可以适当地宣传一下。起码来讲，对我提供了很大的帮助。能贴上一个付款二维码就好了，我很想表达一下感激之情。

好吧，说正事。
AssetPathEntity.all初始化的时候，没有赋值hasVideo属性，导致AssetPathEntity.all.assetList时，107行会报hasVideo为null。
自带demo可以复现

**Comment by CaiJingLong** [comment]
link to #11

**Comment by hyz1992** [comment]
好的

**Comment by CaiJingLong** [comment]
fix in #13
