### ISSUE TITLE
[BUG] NOT WORKING ANDROID APP

### ISSUE THREAD

**Issue by lucas-sesti** [CaiJingLong/flutter_photo_manager#103]
**Describe the bug**
When i open the app with photo manager in android emulator, doesn't work, said is using a deprecated API.

**To Reproduce**
Install the photo manager and run

**Expected behavior**
My expected is open the app.

**Flutter version**
 Flutter version 1.7.8+hotfix.4 at

**Smartphone (please complete the following information):**
 - Pixel 2
 - Android 9.0

**Log**

Note: /Users/lucasbuchallasesti/Desktop/all/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-0.3.5/android/src/main/kotlin/top/kikt/imagescanner/PermissionsUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by CaiJingLong** [comment]
dup of #82.

I am refactoring the code structure of the project in #102 , using a completely lazy loading method, I hope this problem can be solved.

**Comment by CaiJingLong** [comment]
If you can,  try to connect to the latest code using the [url](https://github.com/CaiJingLong/flutter_photo_manager/issues/102#issuecomment-529276926) method to see if it solves your problem.

**Comment by CaiJingLong** [comment]
Merged, next version will fix it.
