### ISSUE TITLE
[BUG] iOS

### ISSUE THREAD

**Issue by malikdoksoz** [CaiJingLong/flutter_photo_manager#106]
`Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    In file included from /Users/malikdoksoz/.pub-cache/hosted/pub.dartlang.org/photo_manager-0.4.0/ios/Classes/core/PMNotificationManager.m:7:
    /Users/malikdoksoz/.pub-cache/hosted/pub.dartlang.org/photo_manager-0.4.0/ios/Classes/core/ConvertUtils.h:17:40: error: expected a type
    + (NSDictionary *)convertPHAssetToMap:(PHAsset *)asset;
                                           ^
    1 error generated.
    Runner-bgyvkdpladytrqhcgyarkfgikoao
`

`[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale tr-TR)
    • Flutter version 1.9.1+hotfix.2 at /Dosyalar/flutter_src/flutter
    • Framework revision 2d2a1ffec9 (7 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/malikdoksoz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 7 • A60B8E89-5141-4B92-802C-69F5CC5980A6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!`

iPhone 7 Simulator

**On Android working**

<img width="881" alt="Ekran Resmi 2019-09-13 17 13 25" src="https://user-images.githubusercontent.com/26676061/64869335-da018480-d649-11e9-8863-53e9f056a876.png">
<img width="1179" alt="Ekran Resmi 2019-09-13 17 14 13" src="https://user-images.githubusercontent.com/26676061/64869369-f00f4500-d649-11e9-9a15-b0b471be5b62.png">

**Comment by CaiJingLong** [comment]
Fix it in #107 .

**Comment by CaiJingLong** [comment]
Update version to 0.4.1.
