### ISSUE TITLE
[BUG] 0.4.0 AssetEntity createTime is returning 0

### ISSUE THREAD

**Issue by hwasoocho** [CaiJingLong/flutter_photo_manager#115]
**Describe the bug**
0.4.0 AssetEntity createTime is returning 0
0.3.5 has no issue

**Expected behavior**
createTime shouldn't return 0

**Flutter version**
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/hwa/Dev/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/hwa/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /home/hwa/Android/Sdk
    • ANDROID_SDK_ROOT = /home/hwa/Android/Sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • SM G970N • R39M305PA5L • android-arm64 • Android 9 (API 28)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - OS: Android 9 (API 28)

**Comment by CaiJingLong** [comment]
Try to use version 0.4.3?

**Comment by hwasoocho** [comment]
@CaiJingLong Just saw the release! Will try and let you know, thanks!

**Comment by CaiJingLong** [comment]
This issue should have been resolved in the new version.

**Comment by hwasoocho** [comment]
@CaiJingLong I have confirmed it's fixed in 0.4.3. Thank you!
