### ISSUE TITLE
[BUG] Much of the EXIF data is missing from images

### ISSUE THREAD

**Issue by dekoding** [CaiJingLong/flutter_photo_manager#119]
**Describe the bug**
When the `fullData` getter is used to retrieve an image's data, EXIF information is stripped on iOS. It is present on Android.

**To Reproduce**
1. With location saving enabled for photos, take several pictures on iOS.
2. Retrieve the images in photo_manager using `fullData` or `originFile`.
2. Convert to a `Uint8List` and run `readExifFromBytes` from the exif package.
3. Log the resulting exif data. Most exif tags will be missing (such as GPS).

**Expected behavior**
All exif information should be available, the same as on Android.

**Screenshots**
<img width="377" alt="Screen Shot 2019-09-27 at 11 48 03 AM" src="https://user-images.githubusercontent.com/812488/65794343-c7448080-e11c-11e9-8a4e-0848cccf4eff.png">

**Flutter version**
Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max (Simulator, too)
 - OS: iOS 13.0
 - Browser: N/A
 - Version: N/A

**Comment by CaiJingLong** [comment]
According to the relevant requirements of privacy rights, because the exif information contains positioning information, if you want to obtain, you may need additional positioning rights.

This part of the code I removed in the 0.4.0 refactoring, this is a problem, I will fix this problem later.

**Comment by filly82** [comment]
any news on this one here?

**Comment by CaiJingLong** [comment]
I implement origin file api in https://github.com/CaiJingLong/flutter_photo_manager/pull/152.
I will implement `fullData` in this week.
