### ISSUE TITLE
The getter 'index' was called on null [BUG]

### ISSUE THREAD

**Issue by malikdoksoz** [CaiJingLong/flutter_photo_manager#120]
**I called _pickAsset(PickType.all).**

`flutter: 130697
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'index' was called on null.
Receiver: null
Tried calling: index
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      PhotoManager.getAssetPathList 
package:photo_manager/src/manager.dart:32
<asynchronous suspension>
#2      _PhotoMainPageState._refreshListFromGallery 
package:photo/…/page/photo_main_page.dart:221
<asynchronous suspension>
#3      _PhotoMainPageState._refreshList 
package:photo/…/page/photo_main_page.dart:196
#4      _PhotoMainPageState.initState 
package:photo/…/page/photo_main_page.dart:84
#5      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4068
#6      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3919
#7      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3101
#8      Element.updateChild 
package:flutter/…/widgets/framework.dart:2904
#9      ComponentElement.per<…>
`

**And error with testPhotoListParams**

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: inheritFromWidgetOfExactType(PhotoPickerProvider) or inheritFromElement() was called before _PhotoMainPageState.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.
Typically references to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.
#0      StatefulElement.inheritFromElement.<anonymous closure> 
package:flutter/…/widgets/framework.dart:4164
#1      StatefulElement.inheritFromElement 
package:flutter/…/widgets/framework.dart:4207
#2      Element.inheritFromWidget<…>
`

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo_manager/blob/e04e4144260cdac7b5702c806b894d3aa70b06ac/lib/src/manager.dart#L20-L36

Param `type ` is required, I will set default value to it. Thx for issue.

**Comment by CaiJingLong** [comment]
And I will update example for `photo` library.
