### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by malikdoksoz** [CaiJingLong/flutter_photo_manager#121]
**When viewing photos in the application, an error occurs when refreshing when a new photo arrives.**
**### Video:** https://streamable.com/shh85

`2019-09-29 19:42:51.983756+0300 Runner[2941:852414] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'index' was called on null.
Receiver: null
Tried calling: index
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      PhotoManager.getAssetPathList (package:photo_manager/src/manager.dart:32:18)
<asynchronous suspension>
#2      _PhotoMainPageState._refreshListFromGallery (package:photo/src/ui/page/photo_main_page.dart:221:39)
<asynchronous suspension>
#3      _PhotoMainPageState._refreshList (package:photo/src/ui/page/photo_main_page.dart:196:5)
#4      _PhotoMainPageState.initState (package:photo/src/ui/page/photo_main_page.dart:84:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#45     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#51     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#88     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#97     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#103    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#113    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#118    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#119    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#125    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#132    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#136    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4910:32)
#137    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5243:17)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#139    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#143    StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#147    ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
#148    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#150    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#154    StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#156    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#158    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#161    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#162    StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#165    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#166    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
#167    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
#168    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
#169    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
#170    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
#171    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
#172    _rootRun (dart:async/zone.dart:1124:13)
#173    _CustomZone.run (dart:async/zone.dart:1021:19)
#174    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#175    _invoke (dart:ui/hooks.dart:249:10)
#176    _drawFrame (dart:ui/hooks.dart:207:3)
2019-09-29 19:43:06.275179+0300 Runner[2941:852162] Can't end BackgroundTask: no background task exists with identifier 18 (0x12), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
`

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo_manager/blob/e04e4144260cdac7b5702c806b894d3aa70b06ac/lib/src/manager.dart#L20-L36

Param `type ` is required, I will set default value to it. Thx for issue.

**Comment by CaiJingLong** [comment]
Same problem of #120 .

**Comment by CaiJingLong** [comment]
Fix it in ab84d47.
Update version to latest version.
