### ISSUE TITLE
[BUG] I can't get the video's duration on IOS.

### ISSUE THREAD

**Issue by haoqiangyu** [CaiJingLong/flutter_photo_manager#127]
I can't get the video's duration on IOS.

 - Device: [iPhone x]
 - OS: [iOS13.1.3]

**Comment by CaiJingLong** [comment]
Need more info.

![image](https://user-images.githubusercontent.com/14145407/69521283-92786c80-0f99-11ea-939b-56af12a3180a.png)

The code for getting the duration is not modified.
I can successfully get it on the simulator of ios 13.1.

Do you have any special code?
