### ISSUE TITLE
在ios simulator上获取不到 AssetEntity 的file 和 fullData数据

### ISSUE THREAD

**Issue by yuanjiong** [CaiJingLong/flutter_photo_manager#128]
hi，我在本机的ios simulator上获取不到 AssetEntity（Video） 的file 和 fullData数据，我使用的simulator为ios13.1 的iphone11 pro，但是在ios13.1的iPhone8上是可以获取到这些数据的。希望能得到帮助，谢谢。

**Comment by yuanjiong** [comment]
我调试了一下，在源代码的plugin.dart的getFullFile方法，返回的数据为空。

**Comment by CaiJingLong** [comment]
I found the cause of the error, but I don't know how to fix it.

This is due :  there is no data in the `[AVAssetExportSession allExportPresets]` of the ios13 on iphone11 simulator. So I can't export the video.

---

So I think this is a bug of ios sdk. Maybe I need find a new method to implement it.

**Comment by CaiJingLong** [comment]
Can you use a physical device to reproduce the bug  ?

**Comment by yuanjiong** [comment]
目前我在真机上测试都是OK，非常感谢
