### ISSUE TITLE
[BUG] ios 32位操作系统机型(iphone5s之前的机器) 获取不到相册图片

### ISSUE THREAD

**Issue by xuyuqiang** [CaiJingLong/flutter_photo_manager#131]
ios 32位机型(iphone5s之前的机器) 获取不到相册图片
原因：32位操作系统处理毫秒时间戳long精度不够，得到错误的时间结果1970年...
在后面获取图片时，会过滤小于当前时间的图片 ,因此获取图片为空
问题代码：
- (unsigned long)getTimestamp:(FlutterMethodCall *)call {
    unsigned long timestamp = [call.arguments[@"timestamp"] unsignedLongValue];
    return timestamp;
}
解决方案：long -> long long

- (unsigned long long)getTimestamp:(FlutterMethodCall *)call {
    unsigned long long timestamp = [call.arguments[@"timestamp"] unsignedLongLongValue];
    return timestamp;
}

调用此方法的地方也要替换一下接收值类型为unsigned long long
 unsigned long long timestamp = [self getTimestamp:call];

**Comment by CaiJingLong** [comment]
Can you open PR to resolve and test it?
I don't have 32bit of iOS device.
