### ISSUE TITLE
[BUG] Unable to read all albums on IOS 13.1.2

### ISSUE THREAD

**Issue by iamtyrik** [CaiJingLong/flutter_photo_manager#132]
Hi CaiJingLong,
When I run on the simulator, everything looks normal.
But when I run the app on my phone, the app can't recognize more albums.

Please check on and let me know the solution, so Thanku
XD

**Comment by CaiJingLong** [comment]
I don't have ios 13 device.
It may take some time to resolve this issue.

**Comment by doerme** [comment]
it also happen on IOS 12.4.3

**Comment by CaiJingLong** [comment]
@doerme  Hi, can you try run master branch on your devices?

**Comment by CaiJingLong** [comment]
No response for a long time, closed. If there is a problem, you can reopen it.
