### ISSUE TITLE
[BUG]  Insert new item在iOS上崩溃

### ISSUE THREAD

**Issue by qcyl** [CaiJingLong/flutter_photo_manager#135]
![image](https://user-images.githubusercontent.com/15316136/70329354-2c7fc500-1876-11ea-8406-4687b6ba2e8c.png)
我认为的解决方案：
![image](https://user-images.githubusercontent.com/15316136/70329402-5638ec00-1876-11ea-999c-340b453b0cd9.png)
希望早日解决

**Comment by CaiJingLong** [comment]
Can you open PR to fix and test it?
