### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by quocb14005xx** [CaiJingLong/flutter_photo_manager#137]
When I use your plugin in my application, 
I have a model bottom sheet and GridView with list of images. When I close and open bottom sheet many time, the memory ussage increase without decrease, I think maybe crash will come! do you have any solution?

**Comment by CaiJingLong** [comment]
This library does not do memory caching of pictures, that may be implemented by the flutter framework, you may need to find answers from the issue of flutter.
