### ISSUE TITLE
【iOS13.2.3】选择的视频路径以/private打头，其它组件无权限，导致崩溃。

### ISSUE THREAD

**Issue by liuhong1happy** [CaiJingLong/flutter_photo_manager#138]

**Comment by CaiJingLong** [comment]
Other ios version have problem?

**Comment by CaiJingLong** [comment]
I try reproduce it. 
If have problem, I will fix it .

**Comment by CaiJingLong** [comment]
I try reproduce it. 
If have problem, I will fix it .

**Comment by CaiJingLong** [comment]
No response for a long time, closed. If there is a problem, you can reopen it.
