### ISSUE TITLE
How can I load list of images without await ?

### ISSUE THREAD

**Issue by huynhquoc09x11x1996** [CaiJingLong/flutter_photo_manager#141]
How can I load list of images without await ?
I want to load all images immediately, How can I do that, could you help me about that.
I am facing with this problem, I have a modal bottom sheet, this widget load each of time is 20 images.
But maybe it load again when I close and open many time, so it make the memory usage in IOS increase very fast!

**Comment by CaiJingLong** [comment]
Flutter cannot be loaded synchronously. It can't do asynchronous to synchronous.

There is a deprecated asynchronous to synchronous method.

<details>

```dart
String foo() {
  String result;
  bool haveResult = false;
  foo2().then((r) {
    result = r;
    haveResult = true;
  });
  for (;;) {
    if (haveResult) {
      return result;
    }
  }
}

Future<String> foo2() async {
  return "abc";
}
```
</details>

My real advice is: You can cache the last result instead of calling `getAssetPathList` every time.

**Comment by huynhquoc09x11x1996** [comment]
Thank you so much for your  advice!!!!
Do you have any idea for cache you said? How about memory usage when cache
many images
