### ISSUE TITLE
java.io.FileNotFoundException: /data/user/0/XXX/cache/110826232119603-1.jpg

### ISSUE THREAD

**Issue by qinao19930929** [CaiJingLong/flutter_photo_manager#144]
android 10 

java.io.FileNotFoundException: /data/user/0/XXX/cache/110826232119603-1.jpg

**Comment by qinao19930929** [comment]
只有那张图片报错，路径是/data/user/0/XXX开头的，其他图片路径是正确的

**Comment by CaiJingLong** [comment]
It looks like this image was deleted, but MediaStore was not notified.

**Comment by CaiJingLong** [comment]
The problem will be resolved.
You can try to use 0.5.0-dev.3.
