### ISSUE TITLE
[Custom] How can i get all images from ios device with paging? 

### ISSUE THREAD

**Issue by at-dinhtruong** [CaiJingLong/flutter_photo_manager#145]
## Expect
I would like to get all images from gallery(with paging) to show on my gallery custom.(without album)

## ScreenShots
Screenshots showing the purpose.

**Comment by CaiJingLong** [comment]
Try to read the [readme](https://github.com/CaiJingLong/flutter_photo_manager#get-asset-list-from-imagepath).

**Comment by at-dinhtruong** [comment]
Thanks for reply. But i don't know what is `path ` in `final assetList = await path.getAssetListRange(start: 0, end: 88);`

**Comment by CaiJingLong** [comment]
Two way:

First way:

1. Read readme.

----

Second way:

1. clone repository 
2. flutter pub get 
3. flutter run 
4. Follow the process of the program to understand how the api works

**Comment by at-dinhtruong** [comment]
thanks for supporting me. i think this lib can not get images when i sync it from my mac.
![IMG_2900D8224B8A-1](https://user-images.githubusercontent.com/44964752/71802109-70d9cd00-308f-11ea-9ed3-2b955ca5c066.jpeg)

**Comment by filly82** [comment]
here is how I do it:

List<AssetPathEntity> list = await PhotoManager.getImageAsset();
if (list!=null) 
{
  for(AssetPathEntity path in list)
  {
    final assetList = await path.getAssetListRange(start: 0, end: 88);
   }
}
