### ISSUE TITLE
png files support

### ISSUE THREAD

**Issue by jackstefansky** [CaiJingLong/flutter_photo_manager#147]
Hi, 
So i wanted to get all assets form gallery, also png flies but it looks like plugin is only getting jpg photos from gallery. Is there an option to get all assets, event png files using this plugin?

**Comment by CaiJingLong** [comment]
You are right. Now the picture is forced to be in jpeg format. I will add png support later.

**Comment by CaiJingLong** [comment]
I rewritten the title attribute of the AssetEntity in #155 .
Now, you can use the title to see the original file name, and get the original data type.

Also, you can use originFile to get original file.
