### ISSUE TITLE
[Custom]获取的相册列表数量和Demo中的数量不一致

### ISSUE THREAD

**Issue by OYQ** [CaiJingLong/flutter_photo_manager#150]
下面的运行demo获取到的相册列表，有13个Item，其中包括屏幕截图，LivePhotos等列表。
![20200110114101](https://user-images.githubusercontent.com/16029650/72124162-b0a9f880-339e-11ea-8443-ee1d82f349f5.jpg)

但是在同一台机子上，运行我自己的代码，只能获取7个Item。
![20200110114131](https://user-images.githubusercontent.com/16029650/72124218-e18a2d80-339e-11ea-9434-bbb192f903a3.jpg)

使用的版本是：
photo_manager: ^0.4.5

iOS12.4.1

**Comment by OYQ** [comment]
直接拷贝demo中的photo_manager代码到我的代码里就可以了。请问0.4.5这个版本是不包含这个提交吗？
https://github.com/CaiJingLong/flutter_photo_manager/pull/139

**Comment by CaiJingLong** [comment]
Maybe your problem is fixed by #149 .

**Comment by CaiJingLong** [comment]
The new version maybe need few days.

**Comment by OYQ** [comment]
OK，Thanks
