### ISSUE TITLE
[Feature] Improve reading image original bytes performance

### ISSUE THREAD

**Issue by hoaquo** [CaiJingLong/flutter_photo_manager#151]
Firstly thank you for a very convenient library. IMHO I would like to suggest a bit improvement on your great library 

**iOS Read asset entity bytes without using File**
You can improve performance of the getOriginBytes(plugin.dart)/getFullFileWithCall(ios native) while saving to file(in native) before read it back(in flutter), as file operation is slow. 

**My point**
At file [ImageScanner.m Line 408](https://github.com/CaiJingLong/flutter_photo_manager/blob/master/ios/Classes/ImageScanner.m) you can return the image bytes, and from flutter you can decode returned bytes. And from [plugin.dart/getOriginBytes()](https://github.com/CaiJingLong/flutter_photo_manager/blob/master/lib/src/plugin.dart) you can get the bytes: 

``` dart
    decodeImageFromList(originalBytes, callback: (Image image) {
        print(image.width);
        print(image.height);
    });
```

**Comment by CaiJingLong** [comment]
If you just need images of the same size and don't care about exif information, you can use this API:

```dart
Uint8List thumbDataWithSize = await entity.thumbDataWithSize(entity.width,entity.height);
```

But because it is a thumbnail, it is impossible to get exif.

If you can improve the performance without affecting the api, welcome to provide pull  request.
