### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by AndroidXiongSir** [CaiJingLong/flutter_photo_manager#153]
* What went wrong:
A problem occurred configuring project ':photo_manager'.
> Could not resolve all artifacts for configuration ':photo_manager:classpath'.
   > Could not download kotlin-android-extensions.jar (org.jetbrains.kotlin:kotlin-android-extensions:1.3.41)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-android-extensions/1.3.41/kotlin-android-extensions-1.3.41.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/26d3a8cfaf833c7c463d681e60a9887dff6819d9960936317f0b615b19a11e4f?response-content-disposition=attachment%3Bfilename%3D%22kotlin-android-extensions-1.3.41.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMjZkM2E4Y2ZhZjgzM2M3YzQ2M2Q2ODFlNjBhOTg4N2RmZjY4MTlkOTk2MDkzNjMxN2YwYjYxNWIxOWExMWU0Zj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmtvdGxpbi1hbmRyb2lkLWV4dGVuc2lvbnMtMS4zLjQxLmphciUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU3ODk4NjUwMH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=slghichRt-nNgOPBrPfwEC8a02YZQSScs5DLgLINYumnGCg4HXihxCdNGo5WRPEHOMHuCRGzPSsDQYwXbxXfywybjAVYkrhY44FiOL-TQAJ9hJubdf01S57IcsArOz60AVzQP~hZM4K0HKYaPbOKI4IGgb2OE32o6Ie3bocZhRnBS~DW45R5J9U9adpcMBoC8su2DERQI6Ndk~ph50cruO~AI4CvIQq8cuEU-XLLz4S3eiXrIR3FgsfQg-ImwONY4hkbR-mWCBY07WNBO77BXBZ~fjlzi3JXGCyP24d4zVBJwpcZkuIrd7Emf~tngqLve2mSfAifBAOcgecZoX-CZA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Remote host closed connection during handshake
   > Could not download kotlin-compiler-embeddable.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.41)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.41/kotlin-compiler-embeddable-1.3.41.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/ea6ab03286a534ab24f123b845a107c7a53b679f6ee56bdc34b5dd1b0fd7b6f4?response-content-disposition=attachment%3Bfilename%3D%22kotlin-compiler-embeddable-1.3.41.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZWE2YWIwMzI4NmE1MzRhYjI0ZjEyM2I4NDVhMTA3YzdhNTNiNjc5ZjZlZTU2YmRjMzRiNWRkMWIwZmQ3YjZmND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmtvdGxpbi1jb21waWxlci1lbWJlZGRhYmxlLTEuMy40MS5qYXIlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1Nzg5ODY5ODN9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=gCYDBU4byF1gz1Ym2rL0HFHi-5I3i-MJr1D7XQFs7LHarYM39FbEsEiweuJACcodJfPQEbgAg4GZ1y9j9OfJgsBCyyo~bg11Gx3BnBArffrbkfmClmoBprYzS~dVgJPM~~tqSzXAB1nPgRqWrrKrImIU0SkyL6VGopJ8GvHBXO1p5iDRWiBppqC7vhM7FAW20lIvrc4iY-OmzzGAoMk7TIA5mRYjEfhO8Bnb9C~IBZ9TjfFeTf~6GxZXLx7r2XjACD94h95VWWqr7lhX2MY9v~-eaZGmQ9Kd1HJ3UyQgBgNuws8dr~P5nkqb9WbAYrBCVp6ucmpD6H9ro8kM7Wyc4w__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Received close_notify during handshake

**Comment by CaiJingLong** [comment]
Look like your network error.
