### ISSUE TITLE
[BUG] 0.4.6 iOS Build failed

### ISSUE THREAD

**Issue by filly82** [CaiJingLong/flutter_photo_manager#162]
After updated to newest version 0.4.6 the build on iOS failed. It works on Android 

This is what XCode said. Is it enough information?

`d: warning: ignoring file /Users/fillymacos/entwicklung/dart/fapp/ios/Flutter/Flutter.framework/Flutter, missing required architecture i386 in file /Users/fillymacos/entwicklung/dart/fapp/ios/Flutter/Flutter.framework/Flutter (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in ResultHandler.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in PhotoChangeObserver.o
      objc-class-ref in PMNotificationManager.o
      objc-class-ref in PMPlugin.o
  "_FlutterMethodNotImplemented", referenced from:
      -[ImageScannerPlugin handleMethodCall:result:] in ImageScannerPlugin.o
  "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
      objc-class-ref in ImageScanner.o
      objc-class-ref in PMManager.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

`Undefined symbol: _OBJC_CLASS_$_FlutterError
Undefined symbol: _OBJC_CLASS_$_FlutterMethodChannel
Undefined symbol: _FlutterMethodNotImplemented
Undefined symbol: _OBJC_CLASS_$_FlutterStandardTypedData`

**Comment by filly82** [comment]
i think it has nothing to do with the plugin itself, sorry

**Comment by filly82** [comment]
or maybe it is? I cannot run my app in the iOS simulator and those above mentioned errors appear in the photo_manager section

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo_manager/pull/161/checks
The CI was passed. 
Can you provide example to reproduce it?

and post flutter doctor -v info .

If I cannot reproduce the problem later, you may need a complete project to help me locate the problem.

**Comment by filly82** [comment]
sorry again, my bad. it must have been one of these mysterious problems on iOS. I had to "deep clean" my project in order to fix the problem, which indeed had nothing to do with your plugin

here is the "deep clean" script I've used btw: https://gist.github.com/jeroen-meijer/bc62dcc74e10e745be7b5790cf74edf0
