### ISSUE TITLE
[BUG] performance problem with 0.4.6

### ISSUE THREAD

**Issue by filly82** [CaiJingLong/flutter_photo_manager#163]
After upgrading to 0.4.6 I've noticed a massive performance loss when iterating through all my photos on my device (about 12.000 photos)

with version 0.4.6 it takes about 2 minutes
with version 0.4.5 it took about 2 seconds

this is the code I am using

    var result = await PhotoManager.requestPermission();
    if (result) {
      List<AssetEntity> imageList = [];
      List<AssetPathEntity> list = await PhotoManager.getImageAsset();
      if (list!=null) for(AssetPathEntity path in list)
        imageList.addAll(await path.getAssetListRange(start: 0, end: path.assetCount));

      if (imageList.isNotEmpty)
      {
        imageList.shuffle();

        List<AssetEntity> imageListNew = imageList.length > count ? imageList.sublist(0, count) : imageList;

        List<AssetEntity> data = [];

        for (AssetEntity assetEntity in imageListNew)
            data.add(assetEntity);

        return data;
      }
    }

**Comment by filly82** [comment]
I've managed to refactor my code and got what I want in ~ 6 seconds, so it's not really a problem any more

but still, the same code took ~ 2 seconds with 0.4.5 and ~ 2 minutes with 0.4.6 ... maybe there is something to optimize

BUT I SEEM TO HAVE ANOTHER BUG:
Photos with Longitude/Latitude have a corrupt .originBytes (Photo cannot be shown, it's just a placeholder) whereas Photos without Longitude/Latitude have no problem at all

**Comment by CaiJingLong** [comment]
Android or iOS?
OS Version?

**Comment by CaiJingLong** [comment]
> I've managed to refactor my code and got what I want in ~ 6 seconds, so it's not really a problem any more
> 
> but still, the same code took ~ 2 seconds with 0.4.5 and ~ 2 minutes with 0.4.6 ... maybe there is something to optimize
> 
> BUT I SEEM TO HAVE ANOTHER BUG:
> Photos with Longitude/Latitude have a corrupt .originBytes (Photo cannot be shown, it's just a placeholder) whereas Photos without Longitude/Latitude have no problem at all

No same problem need open new issue to report.
The problem maybe see [readme](https://github.com/CaiJingLong/flutter_photo_manager#origin-description).

**Comment by filly82** [comment]
> 
> 
> Android or iOS?
> OS Version?

iOS 13.3

**Comment by filly82** [comment]
> 
> 
> > I've managed to refactor my code and got what I want in ~ 6 seconds, so it's not really a problem any more
> > but still, the same code took ~ 2 seconds with 0.4.5 and ~ 2 minutes with 0.4.6 ... maybe there is something to optimize
> > BUT I SEEM TO HAVE ANOTHER BUG:
> > Photos with Longitude/Latitude have a corrupt .originBytes (Photo cannot be shown, it's just a placeholder) whereas Photos without Longitude/Latitude have no problem at all
> 
> No same problem need open new issue to report.
> The problem maybe see [readme](https://github.com/CaiJingLong/flutter_photo_manager#origin-description).

sorry did not understand you right, do I need to open a new issue? 
ok, the readme says that .originBytes is not guaranteed to work. but the only other returning Uint8List for the photo is .fullData and this is deprecated

**Comment by CaiJingLong** [comment]
@filly82 
Please open new issue to discuss the originBytes.

**Comment by CaiJingLong** [comment]
> > Android or iOS?
> > OS Version?
> 
> iOS 13.3

Can you try edit your code to test the speed of your project?

Edit `ios/classes/core/PHAsset+PHAsset_getTitle.m`

```objc
//
//  PHAsset+PHAsset_getTitle.m
//  photo_manager
//
//  Created by Caijinglong on 2020/1/15.
//

#import "PHAsset+PHAsset_getTitle.h"
#import "PHAsset+PHAsset_checkType.h"

@implementation PHAsset (PHAsset_getTitle)

- (NSString *)title {
//  NSArray *array = [PHAssetResource assetResourcesForAsset:self];
//  for (PHAssetResource *resource in array) {
//    if ([self isImage] && resource.type == PHAssetResourceTypePhoto) {
//      return resource.originalFilename;
//    } else if ([self isVideo] && resource.type == PHAssetResourceTypeVideo) {
//      return resource.originalFilename;
//    }
//  }
//
//  /// If code run there, the type maybe have problem.
//  /// Use first resource name.
//
//  PHAssetResource *firstRes = array.firstObject;
//  if (firstRes) {
//    return firstRes.originalFilename;
//  }

  return @"";
}

@end

```

**Comment by CaiJingLong** [comment]
In this version of the modification, the code that will affect performance should be only here.

**Comment by filly82** [comment]
yes, that's it!!!  got my 2 seconds again.

so, the determination of the title is responsible for the performance? I don't need it anyway :)

**Comment by CaiJingLong** [comment]
I open #164 to handle the problem.
But due to time, it can only be completed next week.

**Comment by filly82** [comment]
that's ok with me. thank you
