### ISSUE TITLE
[BUG] originBytes corrupted

### ISSUE THREAD

**Issue by filly82** [CaiJingLong/flutter_photo_manager#165]
I've noticed that photos with Longitude/Latitude have a corrupted .originBytes (Photo cannot be shown, it's just a placeholder) whereas Photos without Longitude/Latitude have no problem at all

I replaced .fullData with .originBytes because .fullData is now deprecated

tested on my device, iPhone XS with iOs 13.3

**Comment by CaiJingLong** [comment]
The problem is this, and now it returns the true original file format.

For example, on iOS this file may be is heic format (the default storage method on iOS12 and above).
Flutter does not support the heic format, so you cannot render it with `Image` widget.

**Comment by CaiJingLong** [comment]
It is good because reading this source file does not require a codec process.

This is the process before 0.4.5:
Request original file => Decode to Bitmap / UIImage => Encode to jpeg

Now:
Request original file data => write to file(bytes).

**Comment by filly82** [comment]
those images were indeed in HEIC format. I've managed to render them with `thumbDataWithSize` with the original width and height of the image. that's fine with me. works like a charm.

I still have a problem with sharing this file (with a plugin called `esys_flutter_share`).

I use the following for both rendering and sharing
`randomImage.thumbDataWithSize(randomImage.width, randomImage.height, format: ThumbFormat.png)`
Rendering works fine, but Sharing does not because it still appears as HEIC. What does `format: ThumbFormat.png` exactly do? Seems like it is converting the Image into PNG because Rendering works, but why can't it be shared as PNG as well?
