### ISSUE TITLE
[Feature] Change album for an asset, and favorite an asset

### ISSUE THREAD

**Issue by eldare** [CaiJingLong/flutter_photo_manager#166]
**Is your feature request related to a problem? Please describe.**
I would like to change the album of an asset, and/or add that asset to favorites.

**Describe the solution you'd like**
- To change the album, a method `moveToAlbum(entity.id, albumName)`.
- To add to favorites: `addToFavorites(entity.id)` and `removeFromFavorites(entity.id)`.

**Describe alternatives you've considered**
I've tried to use `photo_saver` lib to save the asset to a different album, but it creates a duplicate in Recents. For more info see my question: https://stackoverflow.com/questions/59804556/how-to-move-a-photo-video-to-an-album-with-flutter-on-mobile-ios-and-android

Thank you.

**Comment by CaiJingLong** [comment]
Android and iOS are not the same
In iOS, an asset can be included in multiple folders. It is a "shortcut" concept.
In Android, asset is a single database record, and gallery is one of the columns.

**Comment by CaiJingLong** [comment]
In addition, favorite exists in iOS, and this field does not seem to exist in android. 

How to ensure the consistency of the api?

**Comment by eldare** [comment]
1. If I understand you correctly, you're concerned about the 1 asset many albums is not supported on Android?

2. Once photo_manager becomes a full manager, read and write, it can mark a flag favourite on iOS, and for Android, create a new album to copy/reference assets to it.

**Comment by eldare** [comment]
Bump @CaiJingLong

**Comment by CaiJingLong** [comment]
Hi,  0.5.1-dev.2 support your features.
You can try to use the version, the API won't change anymore.
