### ISSUE TITLE
How to include a path in the list returned from getAssetPathList()

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo_manager#167]
Hi,
I've been using this library in my app and it works great a part a bug that doesn't show the pictures that I download using other plugins. Probably they don't trigger the list to refresh.

So the question is: I've got a path of a picture I want to include in the list returned by the function getAssetPathList(), how do I do? 
I basically need to create an AssetEntity and get its ID.
Is there a way to get an AssetEntity ID using a path?

Thanks

**Comment by CaiJingLong** [comment]
Seem related caijinglong/flutter_photo#85.
If you can fully describe the actual use case, I can try to give a solution.

**Comment by rignaneseleo** [comment]
Thanks, alright, I'll explain you how I'm using this library: in my app I have a feed page displaying all the pictures on the phone got using your code:
`List<AssetPathEntity> pathList = await PhotoManager.getAssetPathList();`

Sometimes I receive a notification using `firebase_messaging: ^6.0.9` that contains an url of a picture that is automatically downloaded using the lib `dio: ^3.0.8` (but I tried many of them):
```
Future<String> saveImage(String url, String filename) async {
  String folderPath = (await getApplicationDocumentsDirectory()).path;
  if (Platform.isAndroid)
    folderPath = (await DownloadsPathProvider.downloadsDirectory).path;
  //on iOS only allowed in app folder
  String output = folderPath + Platform.pathSeparator + filename;
  try {
    Dio dio = new Dio();
    await dio.download(url, output);
    print("Saving file in: $output");
    return output;
  } catch (error) {
    print(error);
    return null;
  }
}
```

When I go to the feed after the picture is downloaded, I don't see this new picture (neither if I open your image picker). The picture is not in the pathList although it is on the filesystem. It eventually shows after rebooting or sometimes after opening the gallery but it is unpredictable.

How can I fix this? You can test by yourself: try to download a picture from an url and tell me if it displays in your picker.

Tell me if you need other details.

**Comment by CaiJingLong** [comment]
Just android?

**Comment by CaiJingLong** [comment]
After the pictures are downloaded locally, the MediaStore will get them at some moments and add them to the MediaStore, but their width and height may be 0, and this plugin will filter the pictures of size, because some pictures/video of size 0 have questionable.

Because of this [issue](https://github.com/CaiJingLong/flutter_photo_manager/issues/82#issuecomment-550178523), I have filtered out pictures and videos with size 0 in the filter conditions.

When restarting device or in some cases, the width and height in the MediaStore is not 0 or null, and it will be scanned by photo_manager.

**Comment by CaiJingLong** [comment]
I don't know the reason in iOS, but photo_manager with 0 width and height is also not supported.

**Comment by rignaneseleo** [comment]
On ios I have the same issue.
I understand the bug. What do you suggest to do then as a workaround? Maybe trigger the check on mediastore?

Thanks

**Comment by CaiJingLong** [comment]
In iOS, unless you use system API to insert pictures into the photos, and use the API of PHLibrary can be scanned, otherwise it cannot be solved.

For Android, it is an option to use MediaConnection to update the path, and read the width and height of the picture update to the database.

**Comment by rignaneseleo** [comment]
How can I access MediaConnection to update the path? Can you please provide a snippet? 
Thanks

**Comment by rignaneseleo** [comment]
And another question: is there a way to create an ImageItem with a path?

**Comment by CaiJingLong** [comment]
> How can I access MediaConnection to update the path? Can you please provide a snippet?
> Thanks

This usage of api look like the question of [stackoverflower](https://stackoverflow.com/questions/30003798).



> And another question: is there a way to create an ImageItem with a path?
This is currently not supported.

**Comment by CaiJingLong** [comment]
I can provide an API for you, so you can add pictures to MediaStore in an easy way, but this may only be for android.

**Comment by CaiJingLong** [comment]
With versions higher than 0.5.0.dev-3, you can set the ignoreSize property of the size in the filterOption's imageOption to block the size filtering, so that all images should be displayed.
