### ISSUE TITLE
[BUG] typo 

### ISSUE THREAD

**Issue by filly82** [CaiJingLong/flutter_photo_manager#168]
there is a typo in following code
it has to be filterOption not fliterOption :)

`static Future<List<AssetPathEntity>> getAssetPathList({`
    `bool hasAll = true,`
    `RequestType type = RequestType.all,`
    `DateTime fetchDateTime,`
    `FilterOption fliterOption = const FilterOption(),`
  `}) async {`
    `return _plugin.getAllGalleryList(`
      `type: type.index,`
      `dt: fetchDateTime,`
      `hasAll: hasAll,`
      `fliterOption: fliterOption,`
    `);`
  `}`

is it maybe a good idea to make that FilterOption also available in `getImageAsset()` and `getVideoAsset()`

**Comment by CaiJingLong** [comment]
These two methods are legacy methods.
I personally recommend getAssetPathList for use with param type.

Those two methods I will mark as obsolete in the next version and remove them in a future version.

**Comment by CaiJingLong** [comment]
I fixed the typo problem. 
And I split the filter conditions of image and video in 0.5.0 version. Now image and video can have different filter conditions.

Thx for issue.
