### ISSUE TITLE
[Question] Is ACCESS_BACKGROUND_LOCATION necessary?

### ISSUE THREAD

**Issue by hwasoocho** [CaiJingLong/flutter_photo_manager#169]
There are three kinds of location permissions: 
1. Deny
2. Allow only while using the app
3. Allow all the time

Currently, the plugin does not work if user chooses "Allow only while using the app". I'm not sure, but I believe this is due to ACCESS_BACKGROUND_LOCATION being required.

**Comment by CaiJingLong** [comment]
May I ask if this is the case on iOS or android?

**Comment by CaiJingLong** [comment]
In my impression, iOS does not need to obtain positioning information.
And devices before androidQ should not need location, so the problem probably comes from the privacy permissions of androidQ.

**Comment by hwasoocho** [comment]
Yes, this is with Android Q. Currently, "Allow all the time" (ACCESS_BACKGROUND_LOCATION) permission is required to run the plugin's GPS api. But in my understanding, the plugin does not need this level of permission to obtain GPS information from photos.

**Comment by CaiJingLong** [comment]
I reviewed the documentation of androidQ.
What is needed is ACCESS_MEDIA_LOCATION, not other location permissions.
I already fix it, just wait CI, I'll merge it to master.

**Comment by hwasoocho** [comment]
Thank you so much! Btw, do you have any patreon or other means of donation? It's small, but I want to support your work!

**Comment by CaiJingLong** [comment]
I don’t have a suitable cross-border donation channel at the moment.
Paypal is not very easy to use, I can't transfer the donations that others gave me before.

So if you have a recommended way, let me know. 😄

**Comment by hwasoocho** [comment]
Hmm is https://www.patreon.com/ not an option too?
