### ISSUE TITLE
使用Texture来显示相册图片

### ISSUE THREAD

**Issue by wasabia** [CaiJingLong/flutter_photo_manager#173]
目前显示相册列表图片
是读取每一个图片缩略图数据，然后保存到文件
flutter再用缩略图路径来显示？
感觉效率不高
是否可以考虑使用Texture来显示图片 原生读取缩略图数据使用opengl 转成纹理绘制到Texture
这样用户打开相册 应该可以做到秒开 不会出现转圈圈的情况

**Comment by CaiJingLong** [comment]
No plan to do it.
And the efficiency of using Texture is not necessarily faster than the speed at which data is passed to flutter and displayed.
If you have a similar performance test paradigm, you can evaluate whether it is feasible.

**Comment by CaiJingLong** [comment]
No response for a long time, closed. If there is a problem, you can reopen it.
