### ISSUE TITLE
crash on android 10, java.lang.IllegalStateException

### ISSUE THREAD

**Issue by krisfly** [CaiJingLong/flutter_photo_manager#175]
java.lang.IllegalStateException

galleryName must not be null

**Comment by krisfly** [comment]
in file AndroIdQDBUtiils.kt,
val galleryName = cursor.getString(1)
galleryName maybe null in some devicies

**Comment by kingofglory** [comment]
请问更新到pub.dev了吗？现在flutter版本的还有这个问题。
