### ISSUE TITLE
[BUG] UI lag when calling getAssetPathList

### ISSUE THREAD

**Issue by cohenadair** [CaiJingLong/flutter_photo_manager#178]
**Description**
The UI lags significantly when calling `PhotoManager.getAssetPathList` on a device with ~4500 photos.

**Reproduction Steps**
1. Test on a device with a lot of photos. My device has ~4500.
2. Call `PhotoManager.getAssetPathList(type: RequestType.image)` after tapping a widget that shows some interaction effect, such as an `InkWell`. Or, call `Navigator.push` for a page that calls `getAssetPathList` in `initState`.

**Expected Behavior**
The UI does not drop any frames; any interaction effects or transition animations are smooth.

**Flutter Version**
Channel beta, v1.14.6

**Smartphone**
 - Device: iPhone XR
 - OS: iOS 13.3

**Initial Investigation**
I traced `PhotoManager.getAssetPathList` to `[PMManager getGalleryList:date:hasAll:option]`, which does not use a separate thread for fetching and processing assets. 

In contrast, `ImageScanner` wraps its plugin methods in a `dispatch_async`. I imagine something similar should be done with `PMManager` methods.

**Comment by CaiJingLong** [comment]
Can you provide plugin version and gist code?

**Comment by dvlj** [comment]
PhotoManager.getAssetPathList performance seems fixed with local file fetch but not in iCloud, anyone facing this issue?

I got 2T volume iCloud and has around 60000up photos in many folder/album
