### ISSUE TITLE
Large resolution videos not being returned by getAssetListPaged

### ISSUE THREAD

**Issue by mhstoller** [CaiJingLong/flutter_photo_manager#183]
I have a couple of videos that I was trying to test with recently, and they are not included when calling getAssetListPaged on the 'Recent' album of my android device. They are 1440x3440 or 3440x1440 resolution (I was testing both orientations). The files themselves *seem* okay, the dates are normal on them and other apps like Telegram correctly display these videos in their media selection.

```
        List<AssetPathEntity> albums = await PhotoManager.getAssetPathList();
        //use the first album in the list, we are expecting this to be the system's default album such as "All" or "Recent"
        List<AssetEntity> assetList =
            await albums[0].getAssetListPaged(page, 42);
        for(var asset in assetList){
          print(await asset.file);
        }
```

I can't attach the videos to this issue because GitHub does not support the file types. Is there anything I can do to further diagnose this? I've tried removing the files and downloading them again on the device, and sometimes one of them will show up correctly. Other times, neither one shows up in the getAssetListPaged result.

I uploaded the videos to Google Drive: https://drive.google.com/open?id=1vPfZcY3HUlLPsE4RI5LsOTf_POxz7dr2

**Comment by CaiJingLong** [comment]
iOS or android?

**Comment by CaiJingLong** [comment]
I think it is same problem of #167.

Because some pictures / videos in Android have no width / height in MediaStore after being imported, this library will treat them as wrong resources and ignore them.

Maybe I need to find a way to reconstruct the width and height attributes of the picture.

**Comment by CaiJingLong** [comment]
But the most root cause comes from #82.

**Comment by CaiJingLong** [comment]
I try to fix it in #186.

**Comment by mhstoller** [comment]
Thanks for the response. This was on Android, I can test with iOS simulator later today, and can test with physical iOS device over the weekend if needed.

**Comment by mhstoller** [comment]
I am not able to test with iOS simulator due to limitations on the device, it doesn't allow me to save the videos to the camera roll. I will try again with a real iOS device soon.

I pulled the latest code that is checked into master and tested with the android device
```
  photo_manager:
    git:
      url: https://github.com/CaiJingLong/flutter_photo_manager.git
```

Unfortunately, the 1440x3440 video didn't show up in the list, but the horizontal 3440x1440 video does show up. Since the 1440x3440 video is the edited version it may have lost some data in the conversion. The Android Gallery does correctly show the resolution of the video, and the duration though.
