### ISSUE TITLE
iOS is returning uneditied image[BUG]

### ISSUE THREAD

**Issue by barrettbreshears** [CaiJingLong/flutter_photo_manager#184]
**Describe the bug**
If you crop an image in your photo app and select it using this library the thumbnail returns the correct latest version but the full image always returns the original unedited version of the photo instead of the current edit

**To Reproduce**
Steps to reproduce the behavior IOS ONLY:
1. Edit a photo before using the app within your photos app ( i usually resize it )
2. Select an image from the gallery
3. You can see the thumbnail is ok

**Expected behavior**
I would expect the full size image to be the same as the thumbnail

**Screenshots**
![IMG_4543](https://user-images.githubusercontent.com/2055070/74574095-c0899f00-4f3f-11ea-846b-23250ef581b6.PNG)
![IMG_4542](https://user-images.githubusercontent.com/2055070/74574103-c67f8000-4f3f-11ea-9428-35a7a3b0d7cf.PNG)

**Flutter version**
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.7 at /Users/barrettbreshears/dev/flutter
    • Framework revision 9f5ff2306b (3 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

**Smartphone (please complete the following information):**
 - Device: iPhone Xs, iPhone XsMax
 - OS: iOS 13.3.1

**Log**
NA

**Comment by CaiJingLong** [comment]
I understand what you mean again, you edited the picture using the iOS system application, but the `originaiFile` obtained here is still the old one?

**Comment by barrettbreshears** [comment]
@CaiJingLong yes  I don't want the original unedited image especially if the thumbnail is showing the correct edited image, and I got to get the full size image and it isn't the same as the thumbnail. I would think you would never want to get the original un edited version of the image.

**Comment by Andylove1314** [comment]
Future<File> get file async => PhotoManager._getFileWithId(this.id);

  /// This contains all the EXIF information, but in contrast, `Image` widget may not be able to display pictures.
  ///
  /// Usually, you can use the [file] attribute
  Future<File> get originFile async =>
      PhotoManager._getFileWithId(id, isOrigin: true);

ios 这个两个字段为什么返回的都是heic，无法展示无法上传，最新版本发现该问题

**Comment by CaiJingLong** [comment]
@barrettbreshears  
Do you use the photos application of system to edit pictures?

**Comment by barrettbreshears** [comment]
@CaiJingLong yes the systems default photo application.

**Comment by CaiJingLong** [comment]
OK, I will check the code.

**Comment by CaiJingLong** [comment]
It seem the image will be saved all history in iOS.
I try use the last origin resource.

Can you try to use the version to test it?

```yaml
  photo_manager:
    git:
      url: https://github.com/CaiJingLong/flutter_photo_manager.git
      ref: f3331b6584609984574bd11cd93fc91ae485de72
```

**Comment by CaiJingLong** [comment]
I try to fix it in #187.

**Comment by barrettbreshears** [comment]
Thanks for the work, but the fullsize image is still returning the unedited image, while thumbnail is showing the correct image.

**Comment by CaiJingLong** [comment]
I upload a new commit to fix it in #193 .

**Comment by CaiJingLong** [comment]
Can you try use `43dd81ee5cb49c6b7106555cffcf2e9e66e7629a`?

**Comment by CaiJingLong** [comment]
No response for a long time, closed. If there is a problem, you can reopen it.

**Comment by krokyze** [comment]
Hey @CaiJingLong this issue is still active. I'm using `photo_manager: ^0.5.8`. On iOS in Photos if I adjust contrast of the image, draw something on the picture then `thumbData` returns the edited version but `originBytes` still returns without any edits.

**Comment by CaiJingLong** [comment]
The 0.5.x version is no longer maintained. 
If you have any questions, you can follow the newest dev version. 
When I complete some goals, I will push 0.6.0.

**Comment by yasinarik** [comment]
> Thanks for the work, but the full size image is still returning the unedited image, while the thumbnail is showing the correct image.

Hey I am using this version (latest at the moment): `photo_manager: ^1.1.6`
I have the same issue. The thumbnail images (and thumbDataWithSize) work right. However,  `.originBytes` doesn't.

How to solve this?

@CaiJingLong

**Comment by krokyze** [comment]
> > Thanks for the work, but the full size image is still returning the unedited image, while the thumbnail is showing the correct image.
> 
> Hey I am using this version (latest at the moment): `photo_manager: ^1.1.6`
> I have the same issue. The thumbnail images (and thumbDataWithSize) work right. However, `.originBytes` doesn't.
> 
> How to solve this?
> 
> @CaiJingLong

To get the latest version of image `.file` should be used.

**Comment by yasinarik** [comment]
> > > Thanks for the work, but the full size image is still returning the unedited image, while the thumbnail is showing the correct image.
> > 
> > 
> > Hey I am using this version (latest at the moment): `photo_manager: ^1.1.6`
> > I have the same issue. The thumbnail images (and thumbDataWithSize) work right. However, `.originBytes` doesn't.
> > How to solve this?
> > @CaiJingLong
> 
> To get the latest version of image `.file` should be used.

Thanks a lot!
