### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Andylove1314** [CaiJingLong/flutter_photo_manager#185]
Future get file async => PhotoManager._getFileWithId(this.id);

/// This contains all the EXIF information, but in contrast, Image widget may not be able to display pictures.
///
/// Usually, you can use the [file] attribute
Future get originFile async =>
PhotoManager._getFileWithId(id, isOrigin: true);

ios 这个两个字段为什么返回的都是.heic文件，无法展示、无法上传，最新版本发现该问题，之前的版本返回的是.jpg，但是exif信息丢失，请问怎么解决！

**Comment by CaiJingLong** [comment]
Exif is only included in the original file. If the iOS device stores the heic file, then you need to use the heic exif parser to complete it.

**Comment by CaiJingLong** [comment]
Display image you need use thumbDataWithSize.
