### ISSUE TITLE
[BUG] PhotoManager.getAssetPathList hasAll incorrect on iOS simulator

### ISSUE THREAD

**Issue by hoaquo** [CaiJingLong/flutter_photo_manager#194]
**Describe the bug**
PhotoManager.getAssetPathList hasAll incorrect on iOS simulator, maybe on device (not tested)

**Expected behavior**
Recents album

**Actual**
Recents
Recently Deleted
Recently Added

**Screenshots**
![Screen Shot 2020-02-25 at 8 50 42 PM](https://user-images.githubusercontent.com/5163100/75253114-8312f480-5810-11ea-9780-1bd54b67d81f.png)

**Flutter version**
v1.12.13+hotfix.5

**Comment by YannickBiet** [comment]
In deed, omitting or specifing the hasall flag in PhotoManager.getAssetPathList add extra "path"/albums to the result provided by the method, adding Recents/Recently Added/Recently Deleted "albums".
Please note that only Recents has the properti isAll set to true.

<img width="964" alt="Capture d’écran 2020-03-01 à 00 08 36" src="https://user-images.githubusercontent.com/930391/75616437-fc804f00-5b50-11ea-9e79-8eaf92ce8ac7.png">

**Comment by CaiJingLong** [comment]
These two folders belong to the concept of "smart album" in iOS. I processed them in version 0.5.0, and now these two albums will not be displayed.

**Comment by hoaquo** [comment]
Nah, now the recent album photos are incorrect, it only gets single image
