### ISSUE TITLE
[BUG] IDBUtils. exists() throw exception

### ISSUE THREAD

**Issue by heyman0823** [CaiJingLong/flutter_photo_manager#195]
android.database.sqlite.SQLiteException: near ".": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id FROM files WHERE (MediaStore.Files.FileColumns._ID = ?)

context.contentResolver.query(DBUtils.allUri, columns, "MediaStore.Files.FileColumns._ID = ?", arrayOf(id), null).use {}

maybe use ${MediaStore.Files.FileColumns._ID}

**Comment by CaiJingLong** [comment]
Thx for issue.
