### ISSUE TITLE
[BUG] getAssetPathList Localization error in Album names (ios)

### ISSUE THREAD

**Issue by YannickBiet** [CaiJingLong/flutter_photo_manager#199]
**Describe the bug**
When using getAssetPathList, album names returned are in English, whatever the language currently set on the iphone.
Problem appears with system albums like "recently added" "recently deleted" that should appear in the OS localized name

**To Reproduce**
1. Switch your iphone in another language (for example french)
2. using simulator ? add a photo from your mac, and delete one of the current library (trigger the albums recently added/recently deleted)
3. Launch flutter app and make a call to PhotoManager.getAssetPathList
4. Look at method results, 
5. See that albums contains only English labels ? Shoud see "Supprimés Récemment" instead
6. The same for "Recents" that are call in French "Récents"

**Expected behavior**
Albums names should look the same as OS localized string to allow to build our UI on top the API

**Screenshots**
<img width="1802" alt="Capture d’écran 2020-03-01 à 00 22 58" src="https://user-images.githubusercontent.com/930391/75616573-deb3e980-5b52-11ea-8ade-b5c3c924cec2.png">

**Flutter version**
1.12.13 hotfix 8

**Smartphone (please complete the following information):**
 - Device: ios Simulator
 - OS: Iphone XSMAX on IOSSimulator

**Comment by CaiJingLong** [comment]
I don't see the api to get the localized name.

I can only think of this as a problem that may be solved.

**Comment by YannickBiet** [comment]
Sorry @CaiJingLong i didn't get the last part of your answer.
Would you mean this is a task to be added on a future version, or a problem that may *not* be solved ?

(missing not keyword)

**Comment by Hejianghao** [comment]
Here is the answer, https://stackoverflow.com/questions/42579544/ios-phassetcollection-localizedtitle-always-returning-english-name ,you should add the local file in your project.

**Comment by Hejianghao** [comment]
This issue can close.

**Comment by YannickBiet** [comment]
Hello @Hejianghao, could you elaborate a bit further ?
Should we do something in the flutter project ? (i don't think so) 
or in the ios bridge project created by flutter ?

If I have few times remaining this week (working remotely due to covid...) I will have a look.

**Comment by Hejianghao** [comment]
The iOS project. I've tried, it works.

**Comment by YannickBiet** [comment]
Thanks for sharing @Hejianghao 
I confirm the solution is working but i think we should not close the issue before having documented the workaround for new users.

First a small capture that show the working result
<img width="1085" alt="Capture d’écran 2020-03-18 à 22 30 59" src="https://user-images.githubusercontent.com/930391/77010105-709c5e80-6969-11ea-9d07-224ca9015648.png">

To achieve that, I added the French language in the ios/Runner Project using xCode.
<img width="651" alt="Capture d’écran 2020-03-18 à 22 31 36" src="https://user-images.githubusercontent.com/930391/77010186-99bcef00-6969-11ea-9f40-c8bfb4dcbeb3.png">

Selecting Project Runner
<img width="1138" alt="Capture d’écran 2020-03-18 à 22 42 01" src="https://user-images.githubusercontent.com/930391/77010301-cd981480-6969-11ea-9d29-c258ccaeaa4a.png">

It creates a fr.lproj folder with some files inside.

My problem is that even deleting the language in xcode, my albums are still in French now :)
So i don't get what it changed inside the ios project, but it "unlocked" the possibility to have the albums in french even wihtout keeping the language in runner project (i pressed the minus "-" button")

What do you think @CaiJingLong, should we only document the way to enable it in documentation ?

**Comment by YannickBiet** [comment]
Switching back the ios simulator to english display english album names.

**Comment by YannickBiet** [comment]
I used TimeMachine to restore the application as it was two hours ago (thanks Apple for having created such beauty)
Back to the original code, the album names were in English.

Under Android Studio, I created a simple folder fr.lproj in ios Project and it didn't work.
Albums names were in English even on French iPhone. 
So just creating the folder is not enabling the workaround

I created inside fr.lproj a dummy.strings file and relaunch the project in debug
--> still not working

Open ios project in xcode added the FR language via Project properties (add two strings file inside fr.lproj directory)
Relaunched in debug --> it is working !

Removed via xcode FR language localization
Relaunched in debug --> it is still working !

@Hejianghao did you use another method than the xcode project localizartion property to get it working on your device please ?

**Comment by YannickBiet** [comment]
PR submitted to describe in documentation :
https://github.com/CaiJingLong/flutter_photo_manager/pull/210

**Comment by CaiJingLong** [comment]
Thx for PR. I merged it.

**Comment by Hejianghao** [comment]
> I used TimeMachine to restore the application as it was two hours ago (thanks Apple for having created such beauty)
> Back to the original code, the album names were in English.
> 
> Under Android Studio, I created a simple folder fr.lproj in ios Project and it didn't work.
> Albums names were in English even on French iPhone.
> So just creating the folder is not enabling the workaround
> 
> I created inside fr.lproj a dummy.strings file and relaunch the project in debug
> --> still not working
> 
> Open ios project in xcode added the FR language via Project properties (add two strings file inside fr.lproj directory)
> Relaunched in debug --> it is working !
> 
> **To remove language, i deleted via xcode + removed the /buils/ios directory in my flutter project !**
> 
> @Hejianghao did you use another method than the xcode project localizartion property to get it working on your device please ?

I am not sure if you only add the locale support in Material App it will work. Maybe you can try.
