### ISSUE TITLE
有同时支持视频的计划吗？

### ISSUE THREAD

**Issue by hyz1992** [CaiJingLong/flutter_photo_manager#2]
你这个对我很有帮助！如果能支持视频就更好了

**Comment by CaiJingLong** [comment]
可以考虑加入
不过视频这东西很容易破坏整体api的结构性,因为要同时支持ios/android两端的情况下,视频的大小不好控制,正常在手机中的图片目前最大的也不会超过10m

我的api中,对于文件/字节数组是懒加载,也就是真实获取`Future<File>`或bytes的时候再去native端生成,而ios端和android端目前是不一样的,ios端获取到的是一个PHAsset ,我需要利用PHLibrary中的方法读取到数据,写入ios的应用沙盒内,才能反馈给flutter端一个file/bytes

而android端是存在在数据库内的,我可以直接返回File的path地址给flutter端,不需要转存,如果仅仅是android端,这部分功能很容易实现,但牵涉到ios端以后如果想保持flutter端的api一致性就比较麻烦了

ios端的视频获取/储存方式我没有研究过,还不好说实际情况如何,因为一旦也牵扯到转存,视频这东西的大小会很影响获取速度

你有好的建议吗

**Comment by CaiJingLong** [comment]
我刚刚查看了一下 ios中Asset的定义是包含视频的,且目前我也是同样以图片的方式处理的
这部分从api中体现不出来

我后面看一下如果是视频我应该如何整合到api中

**Comment by CaiJingLong** [comment]
will use #3 to resolve bug and support video

**Comment by CaiJingLong** [comment]
finish in #4
