### ISSUE TITLE
PhotoManager.getAssetPathList doesn't return ApplicationDocumentsDirectory

### ISSUE THREAD

**Issue by ROTGP** [CaiJingLong/flutter_photo_manager#20]
I'm trying to integrate [flutter_camera](https://pub.dartlang.org/packages/camera) and saving the photo to the device. Using the [path_provider](https://pub.dartlang.org/packages/path_provider) package, I can save the photo to the Application Documents directory (the only directory recommended to save app content).  However, this directory is not included when I call `PhotoManager.getAssetPathList`.  I've checked that the ApplicationDocuments path contains photos. Is there some way to ensure that it gets included when calling getAssetPathList()?

**Comment by CaiJingLong** [comment]
It looks like an iOS system. 
The iOS system is a complete API for saving photos.
The images captured in the iOS section of this library are based on [photokit](https://developer.apple.com/documentation/photokit?language=objc) encapsulation

**Comment by ROTGP** [comment]
> It looks like an iOS system.
> The iOS system is a complete API for saving photos.
> The images captured in the iOS section of this library are based on [photokit](https://developer.apple.com/documentation/photokit?language=objc) encapsulation

Well, being Flutter, the API needs to be standard for both iOS and Android.  Is there no way to achieve what I'm trying to do? Save a photo to the Application Documents directory, then list that directory with a call to `PhotoManager.getAssetPathList()`? If it's not possible then I understand, but I'm just looking for a definitive answer before moving on.

**Comment by ROTGP** [comment]
Ok thanks... I've just found [image_picker_saver](https://pub.dartlang.org/packages/image_picker_saver), which lets me save images to the system album. So, problem solved. Thanks for your help and good work

**Comment by vantutrieu97** [comment]
My use case: PhotoManager.getAssetPathList always return empty list in some Android devices, some are working (all permission granted)
