### ISSUE TITLE
[BUG] getAssetPathList missing albums inside folder (ios)

### ISSUE THREAD

**Issue by YannickBiet** [CaiJingLong/flutter_photo_manager#200]
**Describe the bug**
Under Simulator, ios 13.3, iPhone XS Max
In Photos app you can create albums or folders using UI (the create folder button is a bit hidden, you have to click see all albums, edit the list as if you want to delete an album but press the appearing + sign on the top left corner)
These "Folders" would contains Albums that would contains photos (from photo library, a photo can be shared in multiple albums)

Currently a call to getAssetPathList does not return any albums contained in a folder.

**To Reproduce**
1. Go to Photos/Albums
2. Click on see All, then on Edit
3. Click on +, select create album. Name it "album 1"
4. Click on +, select create album. Name it "album 2"
5. Click on +, select create Folder. Name it "folder"
6. Select folder
7. Click on +, select create album. Name it "album 3"
8. Launch flutter app and make a call to getAssetPathList
9. See list of returned albums, missing album3

**Expected behavior**
Album 3 should be listed, folder is only a way to user to organize its photo library in multiple folders/subfolders

**Screenshots**
In this example, i only created a folder at the root of the photos app
then another folder2 in the first folder
then an album1 (adding 3 photos) inside.

You will also see the result of the call to the method

All albums lists from Photos app listing folder
<img width="375" alt="Capture d’écran 2020-03-01 à 00 35 47" src="https://user-images.githubusercontent.com/930391/75616699-df4d7f80-5b54-11ea-8da7-92b9bc34c6d5.png">

Inside folder, another subfolder folder2
<img width="371" alt="Capture d’écran 2020-03-01 à 00 35 54" src="https://user-images.githubusercontent.com/930391/75616697-dceb2580-5b54-11ea-83bd-2d668e751990.png">

that contain an album1 (containing 3 pictures)
<img width="370" alt="Capture d’écran 2020-03-01 à 00 36 00" src="https://user-images.githubusercontent.com/930391/75616696-d9579e80-5b54-11ea-968f-ba43e2fd0c3e.png">

**Where is my album ?**
<img width="898" alt="Capture d’écran 2020-03-01 à 00 38 33" src="https://user-images.githubusercontent.com/930391/75616710-02782f00-5b55-11ea-8c17-29acce6d4899.png">

**Flutter version**
1.12.13 hotfix 8

**Comment by YannickBiet** [comment]
Can't see any open or closed issue regarding "folders" 
don't know if it is a feature request or a bug (like a small hole in the code to handle folders ?)

**Comment by CaiJingLong** [comment]
This is a known issue, I have never figured out how to solve it.

Because of the following 2 reasons:
1. There is no concept of album nesting / folder nesting in Android, because a picture cannot exist in two albums at the same time.
2. Regarding picture selection, because a photo can be included in multiple albums in iOS, if such a photo is selected, I don't know how to deal with the selected state so as not to look strange.

Do you have any good suggestions?

**Comment by YannickBiet** [comment]
I am unsure the root cause is linked to the way iOS is dealing with images in multiple albums but in the fact that the API would ignore given albums in the result list.

Yesterday, I saw other plugins on dart.pub that are dealing with image selection and allow to change album and previously selected images are still selected in the new album. Maybe you/we should have a look on how they achieve to keep this (hope this is not your "photo" plugin ^_^ )

**Comment by YannickBiet** [comment]
If it can help, i think https://pub.dev/packages/multi_image_picker can currently deal with the album change + retain photo selected

**Comment by CaiJingLong** [comment]
@YannickBiet 
This kind of plugin is usually directly connected to the existing library, the main purpose is to select images, and my starting point is different.
The fundamental purpose of my creation of this library is to provide a complete set of APIs to manipulate the resources inside the album.

**Comment by CaiJingLong** [comment]
I already have an idea on how to design the api and implementation, please look forward to it.

**Comment by YannickBiet** [comment]
### ok don't hesitate to share your throughts if I can help, it will be with pleasure.

**Comment by CaiJingLong** [comment]
Use [get-sub-path](https://github.com/CaiJingLong/flutter_photo_manager/tree/get-sub-path) branch to do it.
