### ISSUE TITLE
[Feature] Adding suboptions to getAssetPathList > fetchDateTime

### ISSUE THREAD

**Issue by YannickBiet** [CaiJingLong/flutter_photo_manager#201]
The API is pretty clear about how to use fetchDateTime in getAssetPathList.
This only returns albums containing photos older of the **DateTime** object set in parameter.

But what if we want the other way, only albums containg photo newer than ?

In my scenario, i want to help the user to select photo amongst 50k+ photos in his library by showing him only subset of the photo gallery.

I would suggest him to select a timeframe and only display revelant photos/albums between the timeframe

**Describe the solution you'd like**
if we could have something to describe the timeframe with options for adding such dates
I think we should add a DateConstraint in filteroption object

This DateTimeConstraint could contain the same old behavior fetchDateTime (renamed olderThan)
and add new timeframe option like minDateTime, maxDateTime, and adding the opposite of olderThan : newerThan)

**Describe alternatives you've considered**
unfortunately, it seems there's developement inside the ios/android channel to add the feature directly in the OS ?

**Comment by CaiJingLong** [comment]
Hi, thx for issue.

This is in my plan, I just didn't think about how to discard the old api.

**Comment by YannickBiet** [comment]
I think that if you use semamtic versionning you could just use the version of the module to warn about breaking changes.

Updating from 0.5.x to 0.5.x+1 no breaking change
Updating from 0.5.x to 0.6.x will require an upgrade and a small documentation about breaking changes and how to upgrade the code

Ok there's no really a solution there, only coding best practice.

Regards
