### ISSUE TITLE
[BUG] addChangeCallback not working

### ISSUE THREAD

**Issue by razerduy** [CaiJingLong/flutter_photo_manager#202]
**Describe the bug**
I load all image and video, then i use addChangeCallback for listening to adding new image or new video, but the function not working when i capture new photo or record video. 

**Flutter version**

**Comment by CaiJingLong** [comment]
Is there a complete use case that will allow me to reproduce it?

**Comment by razerduy** [comment]
@CaiJingLong android

**Comment by CaiJingLong** [comment]
No use case, no solution.

**Comment by razerduy** [comment]
i produce a screen like gallery. I load the image and video from gallery at the first time. In that screen, i have a button for capturing photo or recording video.
So when i capture new image or record new video, i want to my screen can add that image or video.

**Comment by CaiJingLong** [comment]
Hi, this notification can only be called back when the app inserted into the album is notified to the system.

If you insert pictures / videos into the album, then you must notify MediaStore / Photos, otherwise this API cannot receive notifications.
