### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dvasea1** [CaiJingLong/flutter_photo_manager#203]
@CaiJingLong Fatal Exception: java.lang.IllegalArgumentException
Unsupported value: android.graphics.ImageDecoder$DecodeException: Input was incomplete.

io.flutter.plugin.common.StandardMessageCodec.writeValue (StandardMessageCodec.java:294)
io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope (StandardMethodCodec.java:70)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error (MethodChannel.java:239)
top.kikt.imagescanner.util.ResultHandler$replyError$1.run (ResultHandler.kt:26)

**Comment by dvasea1** [comment]
@CaiJingLong any updates? Please.

**Comment by CaiJingLong** [comment]
Any code of case ?

**Comment by dvasea1** [comment]
@CaiJingLong i'm using "photo" library. when fast scroll on Android 10, sometimes is crashing, with error : 
 Fatal Exception: java.lang.IllegalArgumentException
Unsupported value: android.graphics.ImageDecoder$DecodeException: Input was incomplete.

io.flutter.plugin.common.StandardMessageCodec.writeValue (StandardMessageCodec.java:294)
io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope (StandardMethodCodec.java:70)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error (MethodChannel.java:239)
top.kikt.imagescanner.util.ResultHandler$replyError$1.run (ResultHandler.kt:26)

**Comment by CaiJingLong** [comment]
Is there a problem only with a quick swipe?

Is there a more complete error message?

**Comment by dvasea1** [comment]
@CaiJingLong it happens during fast scroll down. this error i got from crashlitics.

**Comment by CaiJingLong** [comment]
Can you provide more log?

Your log information is missing the most critical part.Current logs can only see non-core code.
