### ISSUE TITLE
Get main album 

### ISSUE THREAD

**Issue by NicolasCELLA** [CaiJingLong/flutter_photo_manager#204]
Hello an idea how to have the same comportement of :

```
AssetPathEntity data = list[0]; // 1st album in the list, typically the "Recent" or "All" album
List<AssetEntity> imageList = await data.assetList;
```
but for the new verions ? 

I want only the main album ! Thx for your help 😇

**Comment by CaiJingLong** [comment]
Hi, there is currently no such separate use case, I will consider adding it in the future.
