### ISSUE TITLE
Can't delete iOS picture (pics are in tmp folder)

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo_manager#205]
Hi,
I'm using your plugin to show and eventually delete some pictures. 
When I load the List of AssetEntity, I save their _id_ so then, when I need to remove it, I just get them back with
`AssetEntity a = new AssetEntity(id: _resourceID);`
and do a 
`(await a.originFile).delete();`

This works perfectly on Android (it removes the file from the filesystem) but not on iOS: the problem is caused by the path that seems to be one of a thumbnail or other temporary file like that. It is not the path of the original source that keeps showing in the photos album. 
I tried both _file_ and _originFile_ method of AssetEntity but they return the same path.

I leave you the last part of a path I got from iOS: 
`/Data/Application/15842745-057F-4C9C-988D-067FF05622C9/tmp/.image/IMG_0018.JPG`

The question is: how can I get the original file path from an AssetEntity on iOS so I can delete it?

**Comment by CaiJingLong** [comment]
I think you can use the [api](https://github.com/CaiJingLong/flutter_photo_manager#delete-item) to delete item.

**Comment by CaiJingLong** [comment]
Although this can be done in Android, it is limited to before androidQ, and the data in MediaStore will not be deleted.

**Comment by rignaneseleo** [comment]
That works really well, thanks!
