### ISSUE TITLE
[BUG] AssetEntity reports inverse height and width for certain images

### ISSUE THREAD

**Issue by mhstoller** [CaiJingLong/flutter_photo_manager#209]
**Describe the bug**
Certain images in my gallery (usually ones taken with the camera directly) are reporting the height as the width and the width as the height. This causes aspect ratio calculations to be incorrect

**To Reproduce**
Use the attached image, create an AssetEntity from it and then observe the height, width and aspect ratio properties of the AssetEntity.

The correct resolution is 3456x4608 (as reported by the Android gallery), but the properties on the AssetEntity have the height and width swapped. 

**Expected behavior**
Photo manager should account for the orientation of the image / correctly report the width and height

**Flutter version**
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/max/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
![IMG_20200317_182540](https://user-images.githubusercontent.com/36415486/76915408-9fe09c00-6893-11ea-8960-6deffcdef4b5.jpg)

**Comment by mhstoller** [comment]
Interestingly if you can see it, the GitHub image preview has the image rotated incorrectly, but when you click to see the full-size image it's oriented vertically (correctly).

Most gallery applications correctly display the image vertically

**Comment by CaiJingLong** [comment]
Hi, the problem only happened in android?
Do you test the iOS?

**Comment by mhstoller** [comment]
At the moment I am blocked from physical iOS device testing by https://github.com/flutter/flutter/issues/49504

I can try to fix this, but it may take time.

I tried with iOS simulator, but it's very limited. I saved the image to photos from [the above photo](https://user-images.githubusercontent.com/36415486/76915408-9fe09c00-6893-11ea-8960-6deffcdef4b5.jpg) and the problem did **not** occur

**Comment by qpalzm963** [comment]
有解決嗎？
