### ISSUE TITLE
Android's latest picture won't be found

### ISSUE THREAD

**Issue by ROTGP** [CaiJingLong/flutter_photo_manager#21]
I solved [this](https://github.com/CaiJingLong/flutter_photo_manager/issues/20) issue and can now save photos to the public 'Pictures' directory on my device (android, for now), however, now I have a new issue. 

The new captured photos appear properly if viewed via Android's native 'Photos' app (in the appropriate 'Pictures' directory),  however, when I call `PhotoManager.getAssetPathList() `again from within my app, it won't refresh and show the new image. Are results cached somehow? Strangely, taking a new photo will make the last one appear. 

Eg: if I save 1.jpg with the camera, it appears in android's Photos app, but not within my app. Then if I save 2.jpg and refresh by calling PhotoManager.getAssetPathList() again, 1.jpg will appear, but not 2.jpg, and so on.

**Comment by CaiJingLong** [comment]
@ROTGP  I fix it .
try use version 0.1.7

**Comment by ROTGP** [comment]
@CaiJingLong thank you! I've tested it and it works. I can also confirm that this bug does not occur on iOS.

**Comment by CaiJingLong** [comment]
gook luck
