### ISSUE TITLE
[BUG]java.lang.IllegalStateException: galleryName must not be null

### ISSUE THREAD

**Issue by kingofglory** [CaiJingLong/flutter_photo_manager#212]
以下为堆栈信息：

1 top.kikt.imagescanner.core.utils.AndroidQDBUtils.getGalleryList(AndroidQDBUtils.kt:66)
--
2 top.kikt.imagescanner.core.PhotoManager.getGalleryList(PhotoManager.kt:42)
3 top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:165)
4 top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:23)
5 top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
6 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
7 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
8 java.lang.Thread.run(Thread.java:919)

**Comment by CaiJingLong** [comment]
dup of #175 #188.

**Comment by kingofglory** [comment]
请问更新到pub.dev了吗？现在flutter版本的还有这个问题。

**Comment by kingofglory** [comment]
我从pub.dev拉下来的photo_manager0.4.8，Android代码里面没有修复代码，麻烦帮忙看下

**Comment by CaiJingLong** [comment]
You can try to use 0.5.0-dev.1 version.
The release version need more time.

And you also can use git version.

**Comment by kingofglory** [comment]
Nice! Thank you very much.

**Comment by rignaneseleo** [comment]
I'm using _photos_ v0.4.8 and it is there

**Comment by AlexV525** [comment]
photos is no longer being maintained.
