### ISSUE TITLE
[BUG]java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by kingofglory** [CaiJingLong/flutter_photo_manager#217]
以下为报错堆栈：
# main(2)

java.lang.IllegalStateException

Reply already submitted

1 io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
--
2 io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
3 top.kikt.imagescanner.util.ResultHandler$reply$1.run(ResultHandler.kt:18)
4 android.os.Handler.handleCallback(Handler.java:873)
5 android.os.Handler.dispatchMessage(Handler.java:99)
6 android.os.Looper.loop(Looper.java:201)
7 android.app.ActivityThread.main(ActivityThread.java:6810)
8 java.lang.reflect.Method.invoke(Native Method)
9 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
10 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by CaiJingLong** [comment]
Need more info.

**Comment by CaiJingLong** [comment]
1. Please provide a use case / use scenario
2. More complete log information. Logs containing cause by information
