### ISSUE TITLE
[BUG] Cannot find saved photos

### ISSUE THREAD

**Issue by olegys** [CaiJingLong/flutter_photo_manager#232]
**Describe the bug**
Cannot find saved photos from album Pictures after save new photo.
Photo and album are exist on the phone and recorded on the phone.

On Xiaomi Mi9 with android 10.0 it works fine.

**To Reproduce**
                   final path = join(
                          (await getTemporaryDirectory()).path,
                          '${DateTime.now()}.png',
                        );
                        //use Camera plugin
                        await controller.takePicture(path);
                        File image =
                            await FlutterExifRotation.rotateImage(path: path);
                        Uint8List byteImage = await image.readAsBytes();
                        AssetEntity savedImage =
                            await PhotoManager.editor.saveImage(byteImage);

**Expected behavior**
PhotoManager.getAssetPathList return album Pictures with new photo

**Screenshots**
https://monosnap.com/file/mhKYB5BQm9NNsnoWQf8YvXgK1KbFx3
https://monosnap.com/file/arkJtohQwnQDrChGlW0Wi1kOHSbUfG
https://monosnap.com/file/Q1qJDTsOkuaOxggS1BBCPAIHugL5dt

**Flutter version**
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale ru-RU)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\olegy\Desktop\FlutterSDK
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\olegy\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\olegy\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\olegy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Smartphone (please complete the following information):**
 - Device: HTC One, Xiaomi Mi8 lite
 - OS: Android 5.0.2, Android 9.0

**Comment by CaiJingLong** [comment]
Can't see it in the system's photo album?

**Comment by olegys** [comment]
Photo exist in file system

https://monosnap.com/file/6nMWVbgyrRgxnwC5D5qypGRiolgIPx

No photo after selection from the gallery

https://monosnap.com/file/Nh3OsT5tbSpMH5POCqdYXQuzgJaTDL

**Comment by CaiJingLong** [comment]
Can you provide a code repository to help me reproduce it?
I cannot reproduce it on my device.

**Comment by olegys** [comment]
https://github.com/olegys/gallery_app

**Comment by olegys** [comment]
It turned out to reproduce?

**Comment by CaiJingLong** [comment]
Can you try to use the git master version to test your case?

**Comment by CaiJingLong** [comment]
Replace your photo_manager to next:
```yaml
  photo_manager:
    git:
      url: https://github.com/CaiJingLong/flutter_photo_manager.git
      ref: 61a6da64066c07a45b7b3e69098fa7703b79e97b
```

**Comment by CaiJingLong** [comment]
As for the reason, I probably know that when image retrieval.
The library api need width and height are not null, but in some cases, width and height are null. At this time, you can use the ignoreSize field in sizeConstraint to ignore the constraints of width and height .

**Comment by olegys** [comment]
Thanks ! It works great!

  photo_manager:
    git:
      url: https://github.com/CaiJingLong/flutter_photo_manager.git
      ref: 61a6da64066c07a45b7b3e69098fa7703b79e97b

And it works great!

ignoreSize field in sizeConstraint to ignore the constraints of width and height .
