### ISSUE TITLE
HEIC图片如何展示

### ISSUE THREAD

**Issue by imqiuhang** [CaiJingLong/flutter_photo_manager#236]
iOS设备选取的HEIC图片如何展示

**Comment by CaiJingLong** [comment]
flutter does not support heic, so you need to use thumbDataWithSize to get the png or jpg.

**Comment by imqiuhang** [comment]
其实可以的，不要强制将文件后缀改成jpg，保留原有的后缀名例如heic,hefc等，flutter可以显示，即使通过JPG转data的时候也保留原有后缀flutter端依然可以正常显示
