### ISSUE TITLE
[BUG]A problem occurred evaluating root project 'image_scanner'

### ISSUE THREAD

**Issue by terminatorx** [CaiJingLong/flutter_photo_manager#238]
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Administrator\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\photo_manager-0.5.0\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'image_scanner'.
> Plugin with id 'com.android.library' not found.
```

**Comment by CaiJingLong** [comment]
Your project android's root project build.gradle must have  `classpath 'com.android.tools.build:gradle:3.5.3'`. [Like this](https://github.com/CaiJingLong/flutter_photo_manager/blob/61a6da64066c07a45b7b3e69098fa7703b79e97b/example/android/build.gradle#L9)

This version number is usually the same as your android studio version.
Or use the latest 3.6.1.
