### ISSUE TITLE
fix iOS GIF and heic ，解决iOSGIF和实况图无法显示的问题

### ISSUE THREAD

**Issue by imqiuhang** [CaiJingLong/flutter_photo_manager#244]
in PMManager.m

bug fixed : GIF and heic can not open  in iOS platform
解决了iOS平台上heic和GIF无法展示的问题，只修改了 PMManager.m中的代码，heic ，GIF在转成jpg以后其实是可以正常展示的，之前我看调用fetchFullSizeImageFile获取失败是因为文件保存那里有问题，把保存data到文件的代码从ImageScanner.那边拷过来就可以解决，这个问题如果不修复，其实不管是不是获取原始最终走的都是获取原始图的方法。
```objc
      if (isOrigin) {
        [self fetchOriginImageFile:asset resultHandler:handler];
      } else {
        [self fetchOriginImageFile:asset resultHandler:handler];// ======>这里走的还是原始图
      }
```
所以，在iOS设备上其实问题蛮大的，不管是GIF还是heic文件 都是不能展示的，所以我改了下，转成jpg然后正常存储 没问题了。

最后感谢作者的开源，节约了我们不少的时间🌹

偷个懒 就不提mr了 附上我修改的diff文件

[patch.diff.zip](https://github.com/CaiJingLong/flutter_photo_manager/files/4401117/patch.diff.zip)

**Comment by CaiJingLong** [comment]
Welcome open pull request.
