### ISSUE TITLE
[Feature] Location by geocoding

### ISSUE THREAD

**Issue by leonardocustodio** [CaiJingLong/flutter_photo_manager#248]
Hi,

This library is wonderful I know for some people the GPS coordinates may be enough but it would be even better if we could get the picture location by geocoding (no internet connection, no apis).

Android as well as iOS offers local services for geocoding so it is possible to pass the latitude and longitude and get the address, city, state and country of where the photo was taken. This kind of information would be really nice to have on this library.

PS.: I know the geolocalization, distance, maps, realtime, marks and all those stuff are a lot and out of scope of this library but only the geocoding part is just a small part and very useful for most people that won't require all the other stuff that a full geolocalization library provides.

Regards,
Leonardo

**Comment by CaiJingLong** [comment]
Hi, this library's plan does not include this, and it should not be in the future.

**Comment by leonardocustodio** [comment]
Ok, i will close the issue, thank you for the feedback.
