### ISSUE TITLE
Increase max job count 40[BUG]

### ISSUE THREAD

**Issue by Loopex2019** [CaiJingLong/flutter_photo_manager#252]
Hi . Currently i am loading photos and videos from gallery. While loading them it shows me this message "Increase max job count 40". Now i red about that in the internet and what is knew is that its a memory problem because i am loading lots of images and videos , i suppose. I tried to manage this by adding pagination but i couldn't figure it out exactly. Here is my code :

```dart 
 void fetchMedia() async {
    final bool _requestResult = await PhotoManager.requestPermission();
    if (_requestResult == true) {
      final List<AssetPathEntity> _retrievedPhotos =
          await PhotoManager.getAssetPathList(type: RequestType.image);
      final List<AssetPathEntity> _retrievedVideos =
          await PhotoManager.getAssetPathList(type: RequestType.video);
      generateImageList(_retrievedPhotos);
      generateVideoList(_retrievedVideos);
    } else {
      return;
    }
  }

  void generateImageList(List<AssetPathEntity> retrievedPhotos) {
    List.generate(retrievedPhotos.length, (int index) async {
      List<AssetEntity> assets = await retrievedPhotos[index].assetList;
      setState(() {
        _photos = assets
            .map(
              (AssetEntity assetEntity) => Media(media: assetEntity),
            )
            .toList();
      });
    });
    return null;
  }

  void generateVideoList(List<AssetPathEntity> retrievedVideos) {
    List.generate(
      retrievedVideos.length,
      (int index) async {
        List<AssetEntity> _assets = await retrievedVideos[index].assetList;
        setState(() {
          _videos = _assets
              .map(
                (AssetEntity entity) => Media(media: entity),
              )
              .toList();
        });
      },
    );
    return null;
  }
``` 
And as a result for this issue it sometimes shows photos, that when i start scrolling down in the galley , they change to another photos. By videos most of the time it doesn't show all the videos in the gallery.

**Comment by mhstoller** [comment]
Can you provide a complete working code example, please?

**Comment by Loopex2019** [comment]
Here is the rest of the code : 
` Widget _buildLoadingGrid(Size size) {
    return Center(
      child: Shimmer.fromColors(
        baseColor: Colors.grey[300],
        highlightColor: Colors.grey[100],
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: size.width,
                height: size.height,
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(5),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildVideoGrid() {
    if (_videos == null) {
      return Center(
        child: CircularProgressIndicator(
          valueColor: AlwaysStoppedAnimation(
            Colors.black,
          ),
          strokeWidth: 1.5,
        ),
      );
    } else {
      return GridView.builder(
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
        ),
        itemCount: _videos.length,
        itemBuilder: (BuildContext context, int index) {
          return EnhancedFutureBuilder(
              future: _videos[index].media.thumbData,
              rememberFutureResult: true,
              whenWaiting: _buildLoadingGrid(Size(100, 100)),
              whenDone: (snapshot) {
                return GestureDetector(
                  onTap: _videos[index].isSelected == true
                      ? null
                      : () async {
                          final File _selectedFile =
                              await _videos[index].media.file;
                          if (_media.length != 15) {
                            _videos[index].onSelect(() {
                              setState(() {
                                _videos[index].isSelected = true;
                                _media.add({
                                  'media': _selectedFile.path,
                                  'type': '1',
                                });
                              });
                            });
                          } else {
                            Scaffold.of(context).showSnackBar(
                              SnackBar(
                                content: Text('You\'ve reached the Maximum'),
                              ),
                            );
                          }
                        },
                  child: Card(
                    elevation: 5,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(5),
                      side: BorderSide(
                        color: _videos[index].isSelected == true
                            ? Colors.blue
                            : Colors.transparent,
                        width: _videos[index].isSelected == true ? 2.5 : 0,
                      ),
                    ),
                    child: Stack(
                      children: <Widget>[
                        ClipRRect(
                          borderRadius: BorderRadius.circular(5),
                          child: Image.memory(
                            snapshot,
                            fit: BoxFit.cover,
                            height: 120,
                            width: 120,
                          ),
                        ),
                        Positioned(
                          top: 90,
                          left: 75,
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(3),
                            child: new BackdropFilter(
                              filter: ImageFilter.blur(
                                sigmaX: 10.0,
                                sigmaY: 10.0,
                              ),
                              child: new Container(
                                width: _videos[index]
                                            .media
                                            .videoDuration
                                            .inHours !=
                                        0
                                    ? 35
                                    : 32,
                                height: 16,
                                padding: EdgeInsets.all(1.5),
                                decoration: new BoxDecoration(
                                  color: Colors.grey.shade200.withOpacity(0.5),
                                ),
                                child: new Center(
                                  child: new Text(
                                    _videos[index]
                                        .media
                                        .videoDuration
                                        .toString()
                                        .substring(
                                          _videos[index]
                                                      .media
                                                      .videoDuration
                                                      .inHours !=
                                                  0
                                              ? 0
                                              : 2,
                                          7,
                                        ),
                                    style: TextStyle(
                                      color: Colors.grey[850],
                                      fontSize: 12,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                        _videos[index].isSelected == true
                            ? Positioned.fill(
                                child: Container(
                                  margin: EdgeInsets.all(2),
                                  decoration: BoxDecoration(
                                    color: Colors.blue.withOpacity(0.15),
                                    borderRadius: BorderRadius.circular(5),
                                  ),
                                ),
                              )
                            : Container(),
                        _videos[index].isSelected == true
                            ? Positioned(
                                top: 5,
                                right: 5,
                                child: GestureDetector(
                                  child: Icon(
                                    Icons.do_not_disturb_on,
                                    color: Colors.red[700],
                                    size: 24,
                                  ),
                                  onTap: () async {
                                    final File _selectedFile =
                                        await _videos[index].media.file;
                                    _videos[index].unSelect(() {
                                      setState(() {
                                        _media.removeWhere(
                                          (item) =>
                                              item['media'] ==
                                              _selectedFile.path,
                                        );
                                        _videos[index].isSelected = false;
                                      });
                                    });
                                  },
                                ),
                              )
                            : Container(),
                      ],
                    ),
                  ),
                );
              });
        },
      );
    }
  }

  Widget _buildImageGrid() {
    if (_photos == null) {
      return Center(
        child: CircularProgressIndicator(
          valueColor: AlwaysStoppedAnimation(
            Colors.black,
          ),
          strokeWidth: 1.5,
        ),
      );
    } else {
      return GridView.builder(
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
        ),
        itemCount: _photos.length,
        itemBuilder: (BuildContext context, int index) {
          return EnhancedFutureBuilder(
              future: _photos[index].media.thumbData,
              rememberFutureResult: true,
              whenWaiting: _buildLoadingGrid(Size(100, 100)),
              whenDone: (snapshot) {
                return GestureDetector(
                  onTap: _photos[index].isSelected == true
                      ? null
                      : () async {
                          final File _selectedFile =
                              await _photos[index].media.file;
                          if (_media.length != 15) {
                            _photos[index].onSelect(() {
                              setState(() {
                                _photos[index].isSelected = true;
                                _media.add({
                                  'media': _selectedFile.path,
                                  'type': '0',
                                });
                              });
                            });
                          } else {
                            Scaffold.of(context).showSnackBar(
                              SnackBar(
                                content: Text('You\'ve reached the Maximum'),
                              ),
                            );
                          }
                        },
                  child: Card(
                    elevation: 5,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(5),
                      side: BorderSide(
                        color: _photos[index].isSelected == true
                            ? Colors.blue
                            : Colors.transparent,
                        width: _photos[index].isSelected == true ? 2.5 : 0,
                      ),
                    ),
                    child: Stack(
                      children: <Widget>[
                        ClipRRect(
                          borderRadius: BorderRadius.circular(5),
                          child: Image.memory(
                            snapshot,
                            fit: BoxFit.cover,
                            height: 120,
                            width: 120,
                          ),
                        ),
                        _photos[index].isSelected == true
                            ? Positioned.fill(
                                child: Container(
                                  margin: EdgeInsets.all(2),
                                  decoration: BoxDecoration(
                                    color: Colors.blue.withOpacity(0.15),
                                    borderRadius: BorderRadius.circular(5),
                                  ),
                                ),
                              )
                            : Container(),
                        _photos[index].isSelected == true
                            ? Positioned(
                                top: 5,
                                right: 5,
                                child: GestureDetector(
                                  child: Icon(
                                    Icons.do_not_disturb_on,
                                    color: Colors.red[700],
                                    size: 24,
                                  ),
                                  onTap: () async {
                                    final File _selectedFile =
                                        await _photos[index].media.file;
                                    _photos[index].unSelect(() {
                                      setState(() {
                                        _media.removeWhere(
                                          (item) =>
                                              item['media'] ==
                                              _selectedFile.path,
                                        );
                                        _photos[index].isSelected = false;
                                      });
                                    });
                                  },
                                ),
                              )
                            : Container(),
                      ],
                    ),
                  ),
                );
              });
        },
      );
    }
  }`

`build Method`:

`@override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: WillPopScope(
        onWillPop: () async {
          if (_media.length != 0) {
            showDialog(
              context: context,
              builder: (context) => AlertDialog(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                title: Text('Discard picked Media?'),
                actions: <Widget>[
                  FlatButton(
                    onPressed: () {
                      Navigator.pop(context);
                      Navigator.pop(context, null);
                    },
                    child: Text('Discard'),
                  ),
                  FlatButton(
                    onPressed: () {
                      Navigator.pop(context);
                    },
                    child: Text('Cancel'),
                  ),
                ],
              ),
            );
          } else if (_media.length == 0) {
            Navigator.pop(context, null);
          }
          return false;
        },
        child: Scaffold(
          floatingActionButton: FloatingActionButton(
            onPressed: _media.length == 0
                ? null
                : () {
                    Navigator.pop(
                      context,
                      _media,
                    );
                  },
            backgroundColor: _media.length == 0 ? Colors.grey : Colors.blue,
            child: Icon(Icons.check),
          ),
          appBar: ShiftingTabBar(
            color: Colors.white,
            tabs: [
              ShiftingTab(
                icon: Icon(Icons.photo_size_select_actual),
                text: 'Photos',
              ),
              ShiftingTab(
                icon: Icon(Icons.video_library),
                text: 'Videos',
              ),
            ],
          ),
          body: Stack(
            children: <Widget>[
              TabBarView(
                children: [
                  _buildImageGrid(),
                  _buildVideoGrid(),
                ],
              ),
              _media.length != 0
                  ? Positioned(
                      top: 450,
                      right: 16,
                      child: Container(
                        width: 60,
                        height: 30,
                        child: Card(
                          elevation: 10,
                          child: Center(
                            child: Text(
                              '${_media.length} / 15',
                              style: TextStyle(
                                fontWeight: FontWeight.w600,
                                fontSize: 16,
                              ),
                            ),
                          ),
                        ),
                      ),
                    )
                  : Container(),
            ],
          ),
        ),
      ),
    );
  }
}`

`Media class` : 

`class Media {
  AssetEntity media;
  bool isSelected;
  Media({this.media, this.isSelected});
  void onSelect(Function callback) => callback();
  void unSelect(Function callBack) => callBack();
}`

**Comment by CaiJingLong** [comment]
I didn't quite understand what you meant, but photo_manager provides the API for pagination loading, how to apply it in conjunction with your business logic I can't give the full code.

[document of get asset list from AssetPathEntity](https://github.com/CaiJingLong/flutter_photo_manager#get-asset-list-from-assetpathentity)

**Comment by Loopex2019** [comment]
I used the pagination to load 20 images and videos but it loads them once . I don't understand how to load them repeatedly every 20 images and videos . Sorry I am still a beginner .

**Comment by Loopex2019** [comment]
And that message still showing in the debug console

**Comment by Loopex2019** [comment]
Great this Problem is solved using Pagination . Because when all the media once , it creates an overload for memory . But using Pagination the work ion memory will be completed step by step .
