### ISSUE TITLE
How can I get the original file?

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo_manager#254]
In my app , I'm downloading some pictures from the Internet and I noticed a strange behaviour on iOS that I'd like to understand.

Example:
When I download a picture, I choose to save it in the app folder with a filename `MVIMG_20200306_095821.jpg` that is stored in `/Users/leo/Library/Developer/CoreSimulator/Devices/0B4E2BDF-5800-41A0-9AB9-FC0A2598C960/data/Containers/Data/Application/E93201C9-0DF2-4EFA-A15A-EF22A0444536/Documents/MVIMG_20200306_095821.jpg`

When I load the recent list pic from your library, the corrispondend _AssetEntity_ of that downloaded picture has:
- `title`: null
- `titleAsync`: `IMG_0035.JPG`
- path of `file`: `/Users/leo/Library/Developer/CoreSimulator/Devices/0B4E2BDF-5800-41A0-9AB9-FC0A2598C960/data/Containers/Data/Application/E93201C9-0DF2-4EFA-A15A-EF22A0444536/tmp/.image/IMG_0035.JPG`
- path of `originFile`: `/Users/leo/Library/Developer/CoreSimulator/Devices/0B4E2BDF-5800-41A0-9AB9-FC0A2598C960/data/Containers/Data/Application/E93201C9-0DF2-4EFA-A15A-EF22A0444536/tmp/.image/IMG_0035.JPG`

I suppose the file returned is the thumbnail file stored in temp, isn't it?

But then the question is: how can I actually get the original filename?
I need a parameter to actually link the two files (the downloaded and the one got from your lib): the filenames, the modified datetime are different and the creation datetime is not available on the `File` object in Dart. 

Thanks

**Comment by CaiJingLong** [comment]
iOS and android are not the same, each of its apps runs in a sandbox with a separate file system, and you can't really get the original files stored in the system.

When you save, the system will 'automatically' assign a filename to your stored resources.

If you need to manage the files you download, you should use your own data storage system, or a simple json stored in SharedPreferences, or sqlite, hive or other databases.
If you need to associate an asset with a file you downloaded, you can use the asset's id to associate the foreign key.

The id of AssetEntity is the id of the item stored in the MediaStore in Android and the localIdentity of PHAsset in iOS. It can be associated as a unique association primary key.

You can design your database in the following way, but that's just a suggestion:

| key_name | description |
| - | - |
| id | download id , primary key|
| create_dt | create date |
| path | file path |
| download_url | url |
| size | size |
| asset_id | id of AssetEntity |
| more columns... |

**Comment by rignaneseleo** [comment]
> If you need to associate an asset with a file you downloaded, you can use the asset's id to associate the foreign key.

That's what I need to do. I don't understand what is the foreign key you are referring to. I have this problem only on iOS bc on Android the title fo the `AssetEntity` is the filename of the downloaded file.

If my app is downloading 10 pictures in parallel while I'm taking other 10 from my camera, I'll get 20 new items from the function `PhotoManager.getAssetPathList()`. 
How do I recognize the ones downloaded vs the one took from the camera? And then, if the ones downloaded are not in order because of the connection or the size of the file, how do I link each one of them to the corresponding downloaded file?

Thanks

**Comment by CaiJingLong** [comment]
https://en.wikipedia.org/wiki/Foreign_key

Create your own relational database to maintain all downloaded data.
To distinguish whether a file is downloaded or not is to go to the database and find out if the id is there.
I can only give you one idea, the exact coding is up to you.

**Comment by rignaneseleo** [comment]
I know what is a foreign key but I don't understand your way to use it. 

Are you saying that the ID of the file I download and the ID of the file you display are the same? also if their paths are different?

**Comment by CaiJingLong** [comment]
I mean: you need to maintain the correspondence between download and photo_manager yourself.

**Comment by AlexV525** [comment]
Closing without further responses.
