### ISSUE TITLE
[BUG]小米8不能选择剪拼保存的图片

### ISSUE THREAD

**Issue by Tecode** [CaiJingLong/flutter_photo_manager#255]
**Describe the bug**
使用photo_manager 0.5.0在小米8手机上选择图片的时候不能选择剪拼App保存的图片

**To Reproduce**
1. 下载[剪拼App](http://www.adnonstop.com/jianpin/)选择一个图片模版编辑图片；
2. 保存图片->保存到本地
3. 使用flutter_photo Demo 选择图片发现没有之前保存的图片；

**Expected behavior**
选择图片的时候可以选择剪拼保存的图片

**Screenshots**
### 手机设备信息
<img width="375" title="Flutter" src="https://raw.githubusercontent.com/Tecode/flutter_book/master/assets/preview/WechatIMG3.jpeg">

### 图片信息+图片
<img width="375" title="Flutter" src="https://raw.githubusercontent.com/Tecode/flutter_book/master/assets/preview/WechatIMG5.jpeg">
<img width="375" title="Flutter" src="https://raw.githubusercontent.com/Tecode/flutter_book/master/assets/preview/WechatIMG6.jpeg">

### 图片选择时没有出现之前编辑保存的图片
<img width="375" title="Flutter" src="https://github.com/Tecode/flutter_book/blob/master/assets/preview/WechatIMG4.jpeg?raw=true">
**Flutter version**

```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.2)
[✓] Connected device (2 available)
```

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo_manager/blob/3e1d0429ae81f444d64d7f114e45e39f85e77778/lib/src/filter/filter_options.dart#L81

Try set `ignoreSize` to true.
