### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by leielyq** [CaiJingLong/flutter_photo_manager#265]
#7102 java.lang.IllegalStateException
galleryName must not be null

top.kikt.imagescanner.core.utils.AndroidQDBUtils.getGalleryList(AndroidQDBUtils.kt:66)；

1 top.kikt.imagescanner.core.utils.AndroidQDBUtils.getGalleryList(AndroidQDBUtils.kt:66)
--
2 top.kikt.imagescanner.core.PhotoManager.getGalleryList(PhotoManager.kt:42)
3 top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:165)
4 top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:23)
5 top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
6 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
7 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
8 java.lang.Thread.run(Thread.java:919)

设备机型
OPPO PDCM00

CPU架构
arm64-v8a

ROM
Oppo/COLOROS

系统版本
Android 10,level 29

前后台状态
前台

**Comment by CaiJingLong** [comment]
What are you plugin version?

**Comment by leielyq** [comment]
[https://tva1.sinaimg.cn/large/007S8ZIlly1gds3n3u9szj307z01saa0.jpg](image)

0.4.8

**Comment by CaiJingLong** [comment]
The latest version is 0.5.x.
Your problem already be fixed.
