### ISSUE TITLE
如何拿到视频每一帧的图片

### ISSUE THREAD

**Issue by JamesBondPc** [CaiJingLong/flutter_photo_manager#266]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
如何拿到视频每一帧的图片
看到的往往是一开始的图片

**Comment by CaiJingLong** [comment]
photo_manager does not support this, you can use a library such as ffmpeg to get video frame data.
