### ISSUE TITLE
How i can get AssetEntity from asset id ? 

### ISSUE THREAD

**Issue by jlavyan** [CaiJingLong/flutter_photo_manager#267]
I am listen for new Assets from function **PhotoManager.addChangeCallback**. when new asset come i get id for that, but i can't get AssetEntity from that id. When i am trying create new AssetEntity with that id some parameters into it don't exist for example **createDtSecond**

How i can do that ?. 

Thanks.

**Comment by CaiJingLong** [comment]
I will add a method, when manually creating an asset by id, the user can actively call a method to refresh entity properties.

**Comment by TheLastGimbus** [comment]
I'd suggest some static `AssetEntity.fromId()` function

**Comment by CaiJingLong** [comment]
@TheLastGimbus My plan is like this, add a static method to get it, but due to the need to get info from native, this method should be asynchronous.

**Comment by TheLastGimbus** [comment]
@CaiJingLong thank you for this. By the way, I looked at you GitHub out of curiosity, and WOW. You have some stuff in there. Massive props to you.
I have two quick questions about this library.
I want to make something like a Photo Gallery app.
1. Can I safely store Asset's ID in database as a consistent referral to that single image? Is ID something that won't be changed, doubled, or replaced by some other photo?
2. Is this library future-proof for all the "Scoped Storage" that is coming to Android 11? Can I safely store Asset's IDs in database, and later refer to that photos through AssetEntities, and it will still work on 11?

Thank you so much for all of this <3

**Comment by CaiJingLong** [comment]
@TheLastGimbus 

Actually, I don't recommend storing the ID yourself, the data source for the album selector I think should only come from photo_manager.

To answer your questions:
1. id can't changed by user, But the item can be deleted.
2. andorid11's restriction theory is not clear to me at the moment, for the system albums are readable according to the documentation. Other app stored items should require permissions to access them. You can test the validity of the API on android11 yourself.

**Comment by TheLastGimbus** [comment]
I will need to, for example, store database of favourite photos. What should I store to then show user only those photos?
