### ISSUE TITLE
PhotoManager.requestPermission() call crashes in IOS Simulator

### ISSUE THREAD

**Issue by dvu714** [CaiJingLong/flutter_photo_manager#268]
The call to request for permission, PhotoManager.requestPermission(), currently crashes every time when running in the iOS simulator. 

It works fine when running in an android simulator.

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo_manager#ios-plist-config

**Comment by dvu714** [comment]
> https://github.com/CaiJingLong/flutter_photo_manager#ios-plist-config

Thank you for the quick response.
