### ISSUE TITLE
My mobile phone model is HUAWEI CAN L11, running error report

### ISSUE THREAD

**Issue by limhGeek** [CaiJingLong/flutter_photo_manager#27]
I/permission(19717): onGranted call.method = requestPermission
I/permission(19717): onGranted call.method = getGalleryIdList
I/K       (19717): start scan
I/K       (19717): num = 0
E/AndroidRuntime(19717): FATAL EXCEPTION: pool-2-thread-1
E/AndroidRuntime(19717): Process: com.example.fluttermcu, PID: 19717
E/AndroidRuntime(19717): android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 0
E/AndroidRuntime(19717): 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
E/AndroidRuntime(19717): 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
E/AndroidRuntime(19717): 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
E/AndroidRuntime(19717): 	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
E/AndroidRuntime(19717): 	at top.kikt.imagescanner.ImageScanner.scanVideo(ImageScanner.kt:114)
E/AndroidRuntime(19717): 	at top.kikt.imagescanner.ImageScanner.scan(ImageScanner.kt:60)
E/AndroidRuntime(19717): 	at top.kikt.imagescanner.ImageScanner.access$scan(ImageScanner.kt:14)
E/AndroidRuntime(19717): 	at top.kikt.imagescanner.ImageScanner$scanAndGetImageIdList$1.run(ImageScanner.kt:142)
E/AndroidRuntime(19717): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(19717): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(19717): 	at java.lang.Thread.run(Thread.java:776)
I/Process (19717): Sending signal. PID: 19717 SIG: 9
Lost connection to device.

**Comment by CaiJingLong** [comment]
fix in #28

**Comment by CaiJingLong** [comment]
try to update photo version to 0.1.8.

**Comment by limhGeek** [comment]
My system is Android 7.0 and my device has a lot of pictures.
