### ISSUE TITLE
[BUG]kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by github0911** [CaiJingLong/flutter_photo_manager#270]
E/AndroidRuntime(25410): kotlin.KotlinNullPointerException
E/AndroidRuntime(25410): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:208)
E/AndroidRuntime(25410): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:23)
E/AndroidRuntime(25410): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
E/AndroidRuntime(25410): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(25410): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(25410): 	at java.lang.Thread.run(Thread.java:764)

**Comment by github0911** [comment]
0.5.0|0.5.1-dev.4

**Comment by CaiJingLong** [comment]
1. more info, have the stack trace of cause by.
2. android os version
3. gist of dart code.

**Comment by github0911** [comment]
Android 9.0，10.0

**Comment by github0911** [comment]
iOS 也会crash，使用0.5.0+

**Comment by CaiJingLong** [comment]
iOS: https://github.com/CaiJingLong/flutter_photo_manager#ios-config

**Comment by CaiJingLong** [comment]
1. More log.
2. dart code.

**Comment by github0911** [comment]
try {
      var result = await PhotoManager.requestPermission();
      if (result) {
        // success
        var galleryList = await PhotoManager.getAssetPathList();
        galleryList.sort((s1, s2) {
          return s2.assetCount.compareTo(s1.assetCount);
        });

        this.list.clear();
        this.list.addAll(galleryList);
        assetList = await list[0]?.getAssetListRange(start: 0, end: 50);

        setState(() {});
      } else {
        // fail
        PhotoManager.openSetting();
      }
    } catch (e) {}

**Comment by github0911** [comment]
error log 没有其他的日志输出了

**Comment by github0911** [comment]
E/AndroidRuntime( 2624): kotlin.KotlinNullPointerException
E/AndroidRuntime( 2624): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:204)
E/AndroidRuntime( 2624): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:23)
E/AndroidRuntime( 2624): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
E/AndroidRuntime( 2624): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 2624): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 2624): 	at java.lang.Thread.run(Thread.java:764)

**Comment by CaiJingLong** [comment]
I need more log information, it should be without the proguard, containing the cause by information.
The current information cannot locate the error.

**Comment by github0911** [comment]
iOS的是升级版本之后出现的crash，0.4.8是没有问题。0.4.8版本，Android大部分都没有问题，但是红米K30 会出现crash

**Comment by CaiJingLong** [comment]
Is there a log message for iOS?

**Comment by CaiJingLong** [comment]
For iOS issues, you should open a new issue separately

**Comment by github0911** [comment]
这个日志输出是debug模式，日志输出是这样的，是不是和flutter版本有关系？现在的flutter版本是Flutter 1.12.13+hotfix.8

**Comment by CaiJingLong** [comment]
You mean, this is flutter log, the application is not exit?

**Comment by github0911** [comment]
通过允许Android运行的方式，打印的日志和上面贴出来的一样，没有其他的日志输出了

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/79549570-bb74d780-80c9-11ea-952d-ea473ff3ce3a.png)
The line 204 code is get asset id. But I can't find `getThumb`  of your gist code.

Can you make a more complete code to reproduce it?

**Comment by CaiJingLong** [comment]
For example, extract the code of a complete page to allow me to debug on my device

**Comment by github0911** [comment]
import 'dart:io';

import 'package:bee_nest/class/page/chat/page/photo_select_page.dart';
import 'package:bee_nest/common/provider/selected_provider.dart';
import 'package:bee_nest/common/widgets/image_panel_item.dart';
import 'package:bee_nest/common/widgets/load_image.dart';
import 'package:bee_nest/macros/macros.dart';
import 'package:bee_nest/res/resources.dart';
import 'package:bee_nest/res/styles.dart';
import 'package:bee_nest/utils/image_utils.dart';
import 'package:bee_nest/utils/toast.dart';
import 'package:bee_nest/utils/utils.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:photo_manager/photo_manager.dart';
import 'package:bee_nest/class/page/umeng_state.dart';

/// 选择图片面板
class ImagePanel extends StatefulWidget {
  Function onClickCamera;
  Function onClickGallery;
  Function(int) onClickImage;
  Function(dynamic) onClickSend;

  ImagePanel({
    @required this.onClickCamera,
    @required this.onClickGallery,
    this.onClickImage,
    @required this.onClickSend,
  });

  @override
  _ImagePanelState createState() {
    return _ImagePanelState();
  }
}

class _ImagePanelState extends State<ImagePanel> with SelectedProvider {
  List<AssetPathEntity> list = [];
  double panelHeight = Macros.scale(276);
  double bottomHeight = Macros.scale(80);
  List<AssetEntity> assetList = [];

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) {
      panelHeight = Macros.scale(266);
      bottomHeight = Macros.scale(64);
    }
    _initData();
  }

  _initData() async {
    try {
      var result = await PhotoManager.requestPermission();
      if (result) {
        // success
        var galleryList = await PhotoManager.getAssetPathList();
        galleryList.sort((s1, s2) {
          return s2.assetCount.compareTo(s1.assetCount);
        });

        this.list.clear();
        this.list.addAll(galleryList);
        assetList = await list[0]?.getAssetListRange(start: 0, end: 50);

        setState(() {});
      } else {
        // fail
        PhotoManager.openSetting();
      }
    } catch (e) {}
  }

  @override
  Widget build(BuildContext context) {
    return _buildBody();
  }

  _buildBody() {
    return SizedBox(
      height: panelHeight,
      child: Column(
        children: <Widget>[
          Expanded(
            child: CupertinoScrollbar(
                child: GridView.builder(
              shrinkWrap: true,
              scrollDirection: Axis.vertical,
              itemBuilder: _buildItem,
              itemCount: _getItemCount(),
              cacheExtent: 20,
//                physics: NeverScrollableScrollPhysics(),
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 4,
                mainAxisSpacing: 2,
                crossAxisSpacing: 2,
              ),
            )),
          ),
          _buildBottomWidget(),
        ],
      ),
    );
  }

  _getItemCount() {
    /// 手机图片不够，会出现异常
    int count = 0;
    if (assetList != null && assetList.isNotEmpty) {
      count = assetList.length >= 50 ? 50 : assetList.length;
    }
    return count;
  }

  _buildBottomWidget() {
    return Container(
      height: bottomHeight,
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Container(
            margin: EdgeInsets.only(
              left: Macros.scale(5),
              top: Macros.scale(5),
            ),
            child: FlatButton.icon(
              onPressed: () {
                if (widget.onClickCamera != null) {
                  widget.onClickCamera();
                }
              },
              color: Colors.white,
              icon: LoadAssetImage(
                "chat/icon_photograph",
                width: Macros.scale(24),
                height: Macros.scale(24),
              ),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(Macros.scale(50)),
              ),
              label: Text(
                "相机",
                style: TextStyle(
                  color: Colours.text_gray_666,
                  fontSize: Macros.scale(17),
                ),
              ),
            ),
          ),
          Container(
            margin: EdgeInsets.only(
              left: Macros.scale(5),
              top: Macros.scale(5),
            ),
            child: FlatButton.icon(
              onPressed: () {
                if (widget.onClickGallery != null) {
                  widget.onClickGallery();
                }
              },
              color: Colors.white,
              icon: LoadAssetImage(
                "chat/icon_picture_native",
                width: Macros.scale(24),
                height: Macros.scale(24),
              ),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(Macros.scale(50)),
              ),
              label: Text(
                "相册",
                style: TextStyle(
                  color: Colours.text_gray_666,
                  fontSize: Macros.scale(17),
                ),
              ),
            ),
          ),
          Expanded(
            child: Gaps.empty,
          ),
          InkWell(
            onTap: () {
              // 发送
              if (widget.onClickSend != null && selectedList != null && selectedList.isNotEmpty) {
                widget.onClickSend(selectedList);
              }
            },
            child: Container(
              margin: EdgeInsets.only(top: Macros.scale(12), right: Macros.scale(20)),
              alignment: Alignment.center,
              width: Macros.scale(60),
              height: Macros.scale(40),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(Macros.scale(8)),
                color: selectedList == null || selectedList.isEmpty
                    ? Colours.bg_button_disable
                    : Colours.brand_yellow,
              ),
              child: Text(
                "发送",
                style: TextStyle(
                  fontWeight: FontWeight.w500,
                  fontSize: Macros.scale(16),
                  color: Colours.text_black_333,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget buildItem(item) {
    if (item == null) {
      return Gaps.empty;
    }
    return ImagePanelItem(
      entity: item,
    );
  }

  Widget _buildItem(BuildContext context, int index) {
    if (assetList == null || assetList.isEmpty) {
      return Gaps.empty;
    }
    var item = assetList[index];

    return GestureDetector(
      onTap: () => _onItemClick(item, index),
      child: Stack(
        children: <Widget>[
          ImagePanelItem(
            key: ValueKey(item),
            entity: item,
          ),
          _buildSelected(item),
          _playView(item),
        ],
      ),
    );
  }

  _playView(AssetEntity item) {
    if (item.type == AssetType.video) {
      return Container(
        alignment: Alignment.center,
        child: loadAssetImage('chat/icon_video'),
      );
    } else {
      return Container();
    }
  }

  @override
  bool isUpperLimit() {
    var result = selectedCount == 9;
    if (result) {
      // 弹出提示
      Toast.show("您已经选择了9张图片");
    }
    return result;
  }

  @override
  void sure() {
    Utils.debug("sure --------------------------> ");
  }

  void _onItemClick(AssetEntity entity, int index) async {
    File file = await entity.file;
    int length = await file.length();
    if (entity.type == AssetType.image) {
      if (length > 1000000 * 10) {
        Toast.show('上传图片不能超过10M');
        return;
      }
    } else if (entity.type == AssetType.video) {
      if (length > 1000000 * 100) {
        Toast.show('上传视频不能超过100M');
        return;
      }
    }
    var currentSelected = containsEntity(entity);
    changeCheck(!currentSelected, entity);
  }

  Widget _buildSelected(AssetEntity entity) {
    var currentSelected = containsEntity(entity);
    return Positioned(
      top: Macros.scale(6),
      right: Macros.scale(6),
      width: Macros.scale(18),
      height: Macros.scale(18),
      child: Container(
        padding: EdgeInsets.all(Macros.scale(1)),
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          color: Colors.white,
        ),
        child: Container(
          width: Macros.scale(18),
          height: Macros.scale(18),
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: Color(0x66000000),
          ),
          child: GestureDetector(
            onTap: () {
              changeCheck(!currentSelected, entity);
            },
            behavior: HitTestBehavior.translucent,
            child: _buildText(entity),
          ),
        ),
      ),
    );
  }

  Widget _buildText(AssetEntity entity) {
    var isSelected = containsEntity(entity);
    Widget child;
    BoxDecoration decoration;
    if (isSelected) {
      child = Text(
        (indexOfSelected(entity) + 1).toString(),
        textAlign: TextAlign.center,
        style: TextStyle(
          fontSize: Macros.scale(14),
          color: Colours.text_black_333,
        ),
      );
      decoration = BoxDecoration(
        color: Colours.brand_yellow,
        shape: BoxShape.circle,
      );
    } else {
      decoration = BoxDecoration(
        shape: BoxShape.circle,
        border: Border.all(
          color: Colors.transparent,
        ),
      );
    }
    return AnimatedContainer(
      duration: Duration(milliseconds: 300),
      decoration: decoration,
      alignment: Alignment.center,
      child: child,
    );
  }

  void changeCheck(bool value, AssetEntity entity) {
    if (value) {
      addSelectEntity(entity);
      if (widget.onClickImage != null) {
        widget.onClickImage(selectedCount);
      }
    } else {
      removeSelectEntity(entity);
    }
    setState(() {});
  }
}

**Comment by github0911** [comment]
_buildImage(item) {
    final size = 130;
    final u8List = ImageLruCache.getData(item, size);
    Widget image;
    if (u8List != null) {
      return _getImage(u8List);
    } else {
      image = FutureBuilder<Uint8List>(
        future: Plugin().getThumb(id: item.id, width: size, height: size, format: ThumbFormat.png),
        builder: (context, snapshot) {
          Widget w;
          // if (snapshot.hasError) {
          //   w = Center(
          //     child: Text("load error"),
          //   );
          // }
          if (snapshot.hasData) {
            ImageLruCache.setData(item, size, snapshot.data);
            w = _getImage(snapshot.data);
          } else {
            w = Center(
              child: SizedBox.fromSize(
                size: Size.square(30),
                child: CupertinoActivityIndicator(),
              ),
            );
          }

          return w;
        },
      );
    }

    return image;
  }

**Comment by github0911** [comment]
buildItem 的时候有调用Plugin().getThumb(id: item.id, width: size, height: size, format: ThumbFormat.png)获取缩略图

**Comment by CaiJingLong** [comment]
I can't run your code.

Why don't you use `asset.thumbDataWithSize`?

And 

You can try to call `print (item.id)` in every buildItem.

**Comment by github0911** [comment]
asset.thumbDataWithSize 使用这个方法没有问题，我看了一下asset.thumbDataWithSize调用的也是Plugin().getThumb(id: item.id, width: size, height: size, format: ThumbFormat.png)，在0.4.8的版本这样使用是没有问题，但是升级到0.5.0之后就会出现这样的输出了

**Comment by github0911** [comment]
thanks
