### ISSUE TITLE
[BUG] Path of the original image is inaccessible on Samsung devices

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#271]
Hey,

Firstly thank you for the amazing library, it has been quite useful.

I'm working on building a gallery that organizes images by their folders. On most Android devices that I've tested, `(assetEntity.originFile).path` returns the full-path of the file within the device, which I then use to calculate the parent folder name.

But on Samsung devices, this returns something alone the lines of `/data/user/0/package.name.of.myapp/cache/random_name.jpg`.

Please find attached screenshot displaying the same issue on the `example` app within this project.

![issue](https://i.imgur.com/ns4pwMW.jpg)

Maybe I'm using the API in the wrong way. If yes, could you please tell me how I can find the location of a file denoted by an `AssetEntity`?

Thanks again.

**Comment by CaiJingLong** [comment]
The api in android sdk has changed after androidQ.
The path corresponding to each entity is marked as obsolete and is no longer recommended.

[android document](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns?hl=en#DATA)

---

You should not use this method to organize assets.

**Comment by vishnukvmd** [comment]
Thanks for the response CaiJingLong.

I see that [`RELATIVE_PATH`](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#RELATIVE_PATH) has been added. Is there a way for me access this with the help of `flutter_photo_manager`?

**Comment by CaiJingLong** [comment]
I can export it as a flutter.
But this property is not valid in iOS.

**Comment by CaiJingLong** [comment]
The 0.5.1-dev.5 add the properties.

**Comment by vishnukvmd** [comment]
Much appreciated!
