### ISSUE TITLE
[Custom] Is is possible to delete an image with the path string?

### ISSUE THREAD

**Issue by mdcroce** [CaiJingLong/flutter_photo_manager#279]
I want to delete an image as well as its thumbnail (clear cache). Is it possible to do this from path string?

**Comment by CaiJingLong** [comment]
I don't understand what you mean, is there any more detailed explanation.
What picture is deleted, is it in the system photos app or elsewhere?

**Comment by mdcroce** [comment]
When I delete a file "jpg" from DCIM folder (images from the camera in android), it still keeps a thumbnail in the gallery. Is it possible to use you lib to delete an image and its thumbnail from the complete path? eg: /storage/0/DCIM/img1.jpg

**Comment by CaiJingLong** [comment]
If you are not using MediaStore's API to delete pictures, but using File's API to delete, the modification will not be passed to MediaStore.

---
You can try to use this API to delete items whose physical files no longer exist.

```dart
await PhotoManager.editor.android.removeAllNoExistsAsset();
```

But it has the following 2 problems
1. Iterate through all files, so it is time-consuming
2. The time is slow. If there are many resources in the gallery, the time is unpredictable.
