### ISSUE TITLE
[BUG] Crop image origin !

### ISSUE THREAD

**Issue by NicolasCELLA** [CaiJingLong/flutter_photo_manager#281]
Hello, i have a problem on ios ! When with an iphone you save an image cropped in your gallery, photo_manager keep the original file ! 

Did you have any solution ?

Thx for your time 😇

**Comment by CaiJingLong** [comment]
I don't know your mean.

**Comment by NicolasCELLA** [comment]
Ok sorry i have a video :

https://youtu.be/-XETyR8qIa0

**Comment by CaiJingLong** [comment]
Currently, photo_manager sorting only supports creation time, not modification time.
Editing images such as crops of iOS photos is done on the original image, it will only affect the original asset, not create a new asset.

**Comment by CaiJingLong** [comment]
https://youtu.be/nhC-Wr_8chU

**Comment by CaiJingLong** [comment]
After you modify the picture, you need to call getThumb / file / originFile and other methods to get the picture information again

If it is still invalid, you may need to refresh the asset information. For example, if the asset is located at index 1, then use path.getAssetListRange (1,2) to retrieve the asset and replace it with the original location.

The easiest way is PhotoManager.getAssetPathList().

As in my youtube video, the thumb will refresh.

By the way, the example code come from [photo library](https://github.com/CaiJingLong/flutter_photo)

**Comment by NicolasCELLA** [comment]
I have the same problem if i reload my application 

```
// CHECK PERMISSION AND GET PHOTOS
  void _checkPermission(bool _openSetting) async {
    try{
      var result = await PhotoManager.requestPermission();
      if (result) {
        int count = 1000;
        List<AssetEntity> imageList = [];
        List<AssetPathEntity> list = await PhotoManager.getAssetPathList(type: RequestType.image, onlyAll: true);
    
        if (list != null)
          for (AssetPathEntity path in list)
            imageList.addAll(await path.getAssetListRange(start: 0, end: path.assetCount));

        if (imageList.isNotEmpty) {
          List<AssetEntity> imageListNew = imageList.length > count ? imageList.sublist(0, count) : imageList;
          List<AssetEntity> imageListPush = [];

          for (AssetEntity assetEntity in imageListNew)
            imageListPush.add(assetEntity);

          setState(() => data = imageListPush);
        }
      } else if (_openSetting) {
        AppSettings.openAppSettings();
      } else {
        Navigator.of(context).pop();
      }
    } catch (e, s) {
      if (context != null) {
        PCrashlytics.reccordError(context, e, s);
        Navigator.of(context).pop();
      }
    }
  }
```

I use this code for get images !

I don't know why i have the original image and not the cropped 🙁

**Comment by CaiJingLong** [comment]
Maybe you need update new version?

**Comment by NicolasCELLA** [comment]
0.5.1 working fine 🔥

Thx for your time 😇

**Comment by malikdoksoz** [comment]
Still not working. just thumDataWithSize working.
```dart
// current album becomes below code
     _albums = await PhotoManager.getAssetPathList(type: RequestType.image);
        if (_albums.isNotEmpty) {
          final isAllAlbum = _albums.firstWhere((element) => element.isAll,
              orElse: () => _albums.first);
          setState(() {
            _currentAlbum = isAllAlbum;
          });
        }

  Future<void> _fetchMedia(AssetPathEntity currentAlbum) async {
    if (_assets.isEmpty) {
      final ret = await currentAlbum.getAssetListRange(start: 0, end: 5000);

      final List<AssetEntity> assets = [];
      for (final asset in ret) {
        if (asset.type == AssetType.image) assets.add(asset);
      }

      setState(() {
        _assets = assets;
      });
    }
  }
```
