### ISSUE TITLE
icloud 视频播放问题 [BUG]

### ISSUE THREAD

**Issue by HumanRace0602** [CaiJingLong/flutter_photo_manager#282]
当视频缓存在icloud的时候，使用video_player播放会有问题

**Comment by HumanRace0602** [comment]
或者说 如何判断icloud的资源？感谢

**Comment by CaiJingLong** [comment]
No API is currently provided to determine whether it can be an iCloud resource.
You can join it in the future.

**Comment by CaiJingLong** [comment]
Because it is difficult to debug iCloud, I have not tested iCloud video before.

**Comment by HumanRace0602** [comment]
> Because it is difficult to debug iCloud, I have not tested iCloud video before.
thanks a lot

**Comment by CaiJingLong** [comment]
I try to export an api to describe whether it is an icloud picture.

**Comment by 1232209** [comment]
大佬，有进展吗
