### ISSUE TITLE
call to getAssetPathList takes excessively long time on some android devices

### ISSUE THREAD

**Issue by ROTGP** [CaiJingLong/flutter_photo_manager#29]
I'm calling getAssetPathList as follows: 

` List<AssetPathEntity> list = await PhotoManager.getAssetPathList(hasAll: false, hasVideo: false);`

On iOS and Android 8 (with many thousand of images on the device), it completes within a few seconds. However, some users (on Android 5 and 6) are reporting a delay of over 30 seconds, with relatively few images stored on the device.  So, my questions are: 

1) Is there some sort of caching mechanism to build this listing more efficiently (ie, on subsequent loads)

2) Could the params: "hasAll: false, hasVideo: false" have any impact on the speed?

3) Is there any other way to speed up the scan? 30 seconds is a bit of a deal-breaker, but I don't have a physical device with android 5 or 6 to test on.

**Comment by CaiJingLong** [comment]
Android uses the system's photo database. Scan all pictures/videos at once. My device has more than 3,000 pictures/videos and takes less than one second on average.

answer your question
---
1. Scanning does not have a cache, because in the case of too large data, the cache must use the database, and the image database of the system should be the most convenient, there is no need to do the cache.

2. The params won't affect the time, because it will scan anyway, but back to the beginning, the speed of SQLite database is not particularly slow, so I don't know why.

3. I have a device that is based on Android 5.1 and has thousands of pictures without feeling particularly slow.

----
This issue will open until a solution is found.

**Comment by ROTGP** [comment]
@CaiJingLong thanks for your response. I'll report my findings after I've had more time to investigate

**Comment by hongnk** [comment]
My device Huawei P20 which is quite new (Android 9.0), but also slow, it takes about 6-10 seconds when open the  photo picker. But after first load, switching album is instant. Alternate plugin such as flutter multi_image_picker is fast, but it is using native side to display so I prefer this solution. I wish to be able to preload the gallery in advance so that when user open the picker it shows instantly.

**Comment by CaiJingLong** [comment]
@hongnk 
If you have permission, you can pre-cache pictures in advance
Android needs user authorization to access album pictures. Unaware preloading is not possible.

**Comment by hongnk** [comment]
> @hongnk
> If you have permission, you can pre-cache pictures in advance
> Android needs user authorization to access album pictures. Unaware preloading is not possible.

@CaiJingLong Thanks, but I guess it is not the issue with authorization? It is fine if the first time the plugin is used it asks for permission to scan. But here I notice every time calling PhotoPicker.pickAsset it scan again and is slow. Is it possible to reuse the previous scan when reopen the plugin?

**Comment by ROTGP** [comment]
I'm still having this issue, but nothing new to report I'm afraid. On my phone (xiaomi mi-a1 with Android 9) with a LOT of photos (at least 10'000+), the scan is fast (a few seconds), but other users are reporting 5 to 10 seconds per scan. This is an issue because the scan needs to be performed each time the user takes new photos.  I've tried different builds (release, debug etc) but the performance seems to be the same.

**Comment by CaiJingLong** [comment]
@hongnk @ROTGP 

There are two things to do when `pickAsset` be called.
1. Checking Dynamic Access Permissions.
2. Scanning the database and caching the data in memory.
Calling the `pickAsset` method again won't change the process, so I can't locate where you said the initial scan time was too long.

I can try to add a observer to observe album changes, but this will not affect the initial scan speed.

**Comment by hongnk** [comment]
@CaiJingLong  Thanks I just reviewed and notice subsequently the loading is actually faster (2-4 seconds), so it is already cached. However user needs to open the picker regularly and the loading is quite noticeable, unlike other native solutions. Perhaps if we can have a method to reference a single picker instance to be able to reuse the loaded memory in subsequent calls would be great. By the way I have 7000 images in 14 folders (not created by me but from different apps like Whatsapp, Viber, temp, etc), maybe the multiple folders causing the first scan slow?

**Comment by CaiJingLong** [comment]
@hongnk 
It's normal that the speed is proportional to the quantity.
The main scan performance bottleneck in Android is to use `ContentProvider'to interact with the system database. 

I will add a params to get the cache of `List<AssetPathEntity>' .

**Comment by CaiJingLong** [comment]
@hongnk 
Thx for suggest.
In the future, in the photo package, I will pass the pathList in by the caller itself, which means that the user can cache the list himself for subsequent use.
Of course, in photo_manager, I will also implement the scheduled cache function.

**Comment by hongnk** [comment]
> @hongnk
> Thx for suggest.
> In the future, in the photo package, I will pass the pathList in by the caller itself, which means that the user can cache the list himself for subsequent use.
> Of course, in photo_manager, I will also implement the scheduled cache function.

Thanks @CaiJingLong that sounds comprehensive!

**Comment by ROTGP** [comment]
I'm not sure that I understand the proposed changes. If the user takes one or more photos (which are saved to the device's library) whilst using the app, then getAssetPathList PhotoManager.getAssetPathList() will need to be called again in order for the new photos to appear, correct?

**Comment by CaiJingLong** [comment]
The most recent master merged a paginated pr #94 , which can be seen in the next pub version.
I think the issue can be considered using that method to solve.

So, I will close this issue after uploading the next version of pub.

**Comment by SvenSchoene** [comment]
> I'm not sure that I understand the proposed changes. If the user takes one or more photos (which are saved to the device's library) whilst using the app, then getAssetPathList PhotoManager.getAssetPathList() will need to be called again in order for the new photos to appear, correct?

With the changes mentioned in #94 this is half-true: IIRC we do not reload the `AssetPathList`, we simply re-fetch the first page. This works reasonably fast (near instantaneous). Give it a try, hope it works for you as well!

**Comment by CaiJingLong** [comment]
Update version to 0.4.1.
