### ISSUE TITLE
[Feature]能说明下为什么使用Channel而不是 外接纹理吗

### ISSUE THREAD

**Issue by gybin02** [CaiJingLong/flutter_photo_manager#291]
**Is your feature request related to a problem? Please describe.**
我有把代码下载下来，使用安卓真机跑了下， 会有一些掉帧情况。 看了相关闲鱼的技术文档，发现
他们是用外接纹理来实现的，这块有相关研究吗？

**Comment by CaiJingLong** [comment]
闲鱼的看看就得了, 一个没开源, 只有ppt的东西, 性能再好也是镜花水月
