### ISSUE TITLE
[Question] Favorite on iOS Purpose / Location of Assets on iOS temporary 

### ISSUE THREAD

**Issue by filly82** [CaiJingLong/flutter_photo_manager#292]
What is the purpose of Setting/Getting Favorites on iOS? I‘ve implemented and it works so far but I thought/hoped that the internal Gallery on iOS would also show those Pictures as Favorites but it doesn‘t. 
Is there something i‘m missing here?

**Comment by filly82** [comment]
I have an Other problem which could have the same cause like mentioned above 

I want to use some of the Images returned by photo_manager as Header Images in my app so I store the location (originFile Path) of them. But this seem to work only for a While. At some point the Images just dont work anymore 

When looking at the Full Path of file or even originFile then I‘ve noticed that it points to some flutter tmp Directory. This seem to be the problem why the Images work only for a while and maybe why the Favorite does not work. 
Is this expected behaviour?
How would I get the location of the ORIGINAL Image on the Device?

**Comment by AlexV525** [comment]
Please file new issues if the problem is still exist with more details.
