### ISSUE TITLE
[Ques]How to prevent default permission check?

### ISSUE THREAD

**Issue by ASentimentalMan** [CaiJingLong/flutter_photo_manager#304]
**Describe the bug**
I am developing a photos auto-backup app needing to run photoManager in an isolate in case of choking front UI
Unfortunately photoManager will check the permission by default which CANNOT be visit in isolate
It warns me by messaging "获取权限的Activity不存在"
I am sure I have got the permission in front UI first
How can I prevent photoManager from default checking permission?
It happens on Android platform

**Log**

E/MethodChannel#top.kikt/photo_manager(19309): Failed to handle method call
E/MethodChannel#top.kikt/photo_manager(19309): java.lang.NullPointerException: 获取权限的Activity不存在
E/MethodChannel#top.kikt/photo_manager(19309): 	at top.kikt.imagescanner.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:110)
E/MethodChannel#top.kikt/photo_manager(19309): 	at top.kikt.imagescanner.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:95)
E/MethodChannel#top.kikt/photo_manager(19309): 	at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:152)
E/MethodChannel#top.kikt/photo_manager(19309): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#top.kikt/photo_manager(19309): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#top.kikt/photo_manager(19309): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#top.kikt/photo_manager(19309): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#top.kikt/photo_manager(19309): 	at android.os.MessageQueue.next(MessageQueue.java:330)
E/MethodChannel#top.kikt/photo_manager(19309): 	at android.os.Looper.loop(Looper.java:169)
E/MethodChannel#top.kikt/photo_manager(19309): 	at android.app.ActivityThread.main(ActivityThread.java:7042)
E/MethodChannel#top.kikt/photo_manager(19309): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#top.kikt/photo_manager(19309): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
E/MethodChannel#top.kikt/photo_manager(19309): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868)

**Comment by CaiJingLong** [comment]
Because permission checking is a necessary process, I built it in the request of every plugin interaction.

If you are sure that you don't need to check permissions. I can add a parameter to force ignore all permission checks. But correspondingly, when permission is needed and it is not provided, the program will crash.

**Comment by ASentimentalMan** [comment]
This plugin will be more powerful with adding that parameter
I will have permission checked before handle the request to photo manager in isolate
That's so kind of you!

**Comment by AlexV525** [comment]
Supported in 0.6.0 .
