### ISSUE TITLE
[BUG] Crashes on Android after updating to Flutter 1.17

### ISSUE THREAD

**Issue by lslv1243** [CaiJingLong/flutter_photo_manager#305]
After I updated Flutter to version 1.17 I get a crash when registering this plugin. I think the v1 embedding for Android no longer works with this plugin. Please update to support also v2 embedding.

**Comment by lslv1243** [comment]
I made a pull request to fix this issue https://github.com/CaiJingLong/flutter_photo_manager/pull/307

**Comment by CaiJingLong** [comment]
Thx for PR.
