### ISSUE TITLE
Can not get the thumb[BUG]

### ISSUE THREAD

**Issue by imuto** [CaiJingLong/flutter_photo_manager#306]
I use the v0.5.3, I find the function 'imageEntity.thumbDataWithSize(w, h)' can not return the image data. The thumb data is null. But the function 'imageEntity.thumbData' is correct. Before i use the version v0.4.8, it dose not have the issue.

Thank you for your efforts

**Comment by rignaneseleo** [comment]
Same error here. It is related with codec.

**Comment by jlavyan** [comment]
AssetEntity asset = AssetEntity(id: id);

    // TODO remove after fix photo_manager fetch issue˝
    asset.typeInt = 1;

set typeInt to 1 before load image. This issue happen after flutter upgrade

**Comment by AlexV525** [comment]
Is this still reproducible on the latest version?

**Comment by AlexV525** [comment]
Closing with stale state.
