### ISSUE TITLE
[BUG] Endless call of fetchThumb on iOS

### ISSUE THREAD

**Issue by SStesh** [CaiJingLong/flutter_photo_manager#308]
I am using photo_manager lib on my Flutter app and sometimes iOS app gets working slow because of huge processor load and printing a lot of repeated errors related to thumbnail image loading.
It happens rarely and with no stable reproduce so I wasn't able to debug it. Today I got the stable reproduce of this problem on my iPhone and investigated it more detailed.
My app uses following API for requesting thumbnail:
`AssetEntity.thumbDataWithSize(width, height)`

The problem is happening when thumbnail is requested on a specific video file. When thumbDataWithSize() is called for this video following messages are printed permanently on console:
```
[ImageManager] Error decoding image from thumbnail table, for image request: 1-4-0 for asset with localIdentifier: BCB1FB7F-03FE-44DB-82C7-1E3210DF7069/L0/001
[ImageManager] [RM]: 1-4-0 Failed to decode image
[ImageManager] Error decoding image from thumbnail table, for image request: 1-5-0 for asset with localIdentifier: BCB1FB7F-03FE-44DB-82C7-1E3210DF7069/L0/001
[ImageManager] [RM]: 1-5-0 Failed to decode image
...
```
The thumbnail is provided with a short delay but these errors are printed to console after that anyway.

I debugged photo_manager code called from app over Xcode and discovered that fetchThumb() method from PMManager.m is called recursively even when result has been already provided back to Flutter.
I see that progress handler is triggered all the time where another fetchThumb() request is called which triggers another request and progress handler called again so such loop is endless and lead to full processor load.

I don't know details why fetchThumb() called again from progress handler but I see a condition in the code which checks is handler was replied:
```
if ([handler isReplied]) {
    return;
}
```
So seems it can be called second time even if it has been already replied and such check handles this.
Putting the same check into a progress handler and preventing a call of fetchThumb() here if handler has been already replied solved my problem.
Could you please check this issue and find a solution for preventing such endless loop or apply at least this fix into the next lib release.

Thanks in advance!

**Comment by CaiJingLong** [comment]
This progress callback is for iCloud pictures/videos.
In iCloud, the download is complete when the progress is 100%, so this method will be recursed once, so that the same ResultHandler can be used to return the result.

But I did not expect that it may be called multiple times at 100%, and I will try to add some conditions in the progress callback to limit the number of recursion, including handling download errors.

**Comment by SStesh** [comment]
Thanks a lot for taking care of this issue! Looking forward for a new release of the library.

**Comment by jlavyan** [comment]
When delivery mode is opportunistic handler can be called two time for give low, high quality images. You can also set deliveryMode to highQualityFormat, fastFormat

**Comment by yadaniyil** [comment]
@SStesh hey, could you please make a fork with your fix of endless image getting from iCloud? Thanks

**Comment by yadaniyil** [comment]
@CaiJingLong can we prioritize this one? Seems like https://github.com/CaiJingLong/flutter_photo_manager/issues/377 has the same issue and the fix is quite simple.
