### ISSUE TITLE
[BUG] latlngAsync() always returns zero values

### ISSUE THREAD

**Issue by yadaniyil** [CaiJingLong/flutter_photo_manager#309]
**Describe the bug**
latlngAsync() always returns zero values

**To Reproduce**
1. Use Android Q
2. Make a photo with a location in the metadata.
3. Use photo.LatLng position = await asset.latlngAsync(); and get zero values in position

**Expected behavior**
Get real location data like in iOS and Android < 10

**Flutter version**
Flutter 1.17.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f21edf8b6 (8 days ago) • 2020-05-28 12:44:12 -0700
Engine • revision b851c71829
Tools • Dart 2.8.3

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3 Emulator

**Comment by 7snalbar** [comment]
Same issue here on iOS. Android works like a charm

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
