### ISSUE TITLE
can you open api which can get thumbnail from file path?

### ISSUE THREAD

**Issue by linguitang** [CaiJingLong/flutter_photo_manager#31]

**Comment by CaiJingLong** [comment]
I don't understand what you mean.

If you need a library of compressed pictures, you can see [flutter_image_compress](https://github.com/OpenFlutter/flutter_image_compress).

**Comment by linguitang** [comment]
I  get image/video from camera which is use [image_picker](https://pub.dartlang.org/packages/image_picker) , the plugin pick result is file. next, I need to get thumbnail  of image/video , flutter_photo_manager has realize this.

**Comment by CaiJingLong** [comment]
try to use [flutter_image_compress](https://github.com/OpenFlutter/flutter_image_compress) to compress your image file.
