### ISSUE TITLE
是否支持这个功能，在选择了照片后，就无法选择视频，反之亦然。就是互斥选择。[Feature]

### ISSUE THREAD

**Issue by seethinks** [CaiJingLong/flutter_photo_manager#311]
在做社交类产品的时候可能会遇到此类需求。谢谢。

**Comment by CaiJingLong** [comment]
The choice has nothing to do with photo_manager.
That's just a matter of your business logic level.

**Comment by seethinks** [comment]
ok，明白了。可以通过AssetType类型判断做过滤，谢谢。
