### ISSUE TITLE
[Feature] Filter on file size (Mb)

### ISSUE THREAD

**Issue by yannickvg** [CaiJingLong/flutter_photo_manager#312]
**Is your feature request related to a problem? Please describe.**
In our app we upload images and videos to our backend. Therefore we want to allow the user to only select files below 30Mb.

**Describe the solution you'd like**
We would like to be able to filter the files based on FileSizeConstraint, like we can now currently filter on SizeConstraint and DurationConstraint

**Describe alternatives you've considered**
We have tried doing this filtering after retrieving the assets from the photo_manager plugin by doing .file.length() but this easily becomes too slow. On most devices with some videos in the camera roll this takes up to a minute.

**Additional context**

**Comment by maskletter** [comment]
我现在也遇到了这个图片体积问题，我现在只能是用户选择完图片之后判断图片体积提示用户

**Comment by maskletter** [comment]
我现在也遇到过这个图片体积问题，现在的解决方案是：自定义的图片选择器，用户选择图片时候检查图片体积，超过了多少禁止选择并提示用户

**Comment by AlexV525** [comment]
We won't get the file size of entities before we make I/O requests since the `AssetEntity` is only an abstraction. Closing this since it's impossible according to the structure design.
