### ISSUE TITLE
thumbDataWithSize() gets ignored on app's first load

### ISSUE THREAD

**Issue by jj-gh** [CaiJingLong/flutter_photo_manager#316]
Specifying thumbnail size and quality with thumbDataWithSize() doesn't work on app's first load after installation. The arguments get ignored and returns full size and highest quality.

**Comment by CaiJingLong** [comment]
Just android or iOS?
Maybe related #322.

Can you try to use the 0.6.x branch to test the problem?

**Comment by jj-gh** [comment]
Unfortunately, I can't test it on iOS but I tried the branch 0.6.x on two physical android devices (7.1.1 and 9)

Calling AssetEntity.getAssetListRange() crashes the app with the following log:

E/CursorWindow(25051): Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 16 columns.
E/AndroidRuntime(25051): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime(25051): Process: com.example.app, PID: 25051
E/AndroidRuntime(25051): java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
E/AndroidRuntime(25051): 	at android.database.CursorWindow.nativeGetLong(Native Method)
E/AndroidRuntime(25051): 	at android.database.CursorWindow.getLong(CursorWindow.java:524)
E/AndroidRuntime(25051): 	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
E/AndroidRuntime(25051): 	at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
E/AndroidRuntime(25051): 	at top.kikt.imagescanner.core.utils.IDBUtils$DefaultImpls.getLong(IDBUtils.kt:133)
E/AndroidRuntime(25051): 	at top.kikt.imagescanner.core.utils.DBUtils.getLong(DBUtils.kt:36)
E/AndroidRuntime(25051): 	at top.kikt.imagescanner.core.utils.DBUtils.convertCursorToAsset(DBUtils.kt:245)
E/AndroidRuntime(25051): 	at top.kikt.imagescanner.core.utils.DBUtils.getAssetFromGalleryIdRange(DBUtils.kt:219)
E/AndroidRuntime(25051): 	at top.kikt.imagescanner.core.PhotoManager.getAssetListWithRange(PhotoManager.kt:67)
E/AndroidRuntime(25051): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$3.invoke(PhotoManagerPlugin.kt:204)
E/AndroidRuntime(25051): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$3.invoke(PhotoManagerPlugin.kt:26)
E/AndroidRuntime(25051): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(PhotoManagerPlugin.kt)
E/AndroidRuntime(25051): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(25051): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(25051): 	at java.lang.Thread.run(Thread.java:762)

**Comment by CaiJingLong** [comment]
Can you provide an example to reproduce it?
and, post your environment (flutter doctor -v), devices info (android OS version.)

If you can, provide a screenshot of photos app.

**Comment by jj-gh** [comment]
Here's a tester app [https://github.com/jj-gh/photo_manager_tester](https://github.com/jj-gh/photo_manager_tester)
The first time I ran it, it worked. But after I closed it and ran it again, the problem started happening again.


[√] Flutter (Channel master, 1.20.0-8.0.pre.75, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.20.0-8.0.pre.75 at C:\flutter
    • Framework revision bb3280885c (10 hours ago), 2020-07-13 16:28:27 -0700
    • Engine revision f10f172573
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06cb010247)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Me\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Me\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.0)
    • VS Code at C:\Users\Me\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • SM J510GN (mobile) • 6160ee73 • android-arm • Android 7.1.1 (API 25)

**Comment by CaiJingLong** [comment]
Thanks for your submission, I will see if I can reproduce the problem, I will try to solve it.

**Comment by CaiJingLong** [comment]
Hi, I fix it in 34ae13647eccacd49c41dae259fb7b5bfe5a4b02.

Thanks for report.

**Comment by jj-gh** [comment]
Thank you, the original problem is fixed on android 9 but still persists on 7.1.1
At first load after the app's installation, thumbDataWithSize() will return the full size with the following logs:

W/Glide   ( 7561): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
D/skia    ( 7561): --- SkAndroidCodec::NewFromStream returned null
D/skia    ( 7561): --- SkAndroidCodec::NewFromStream returned null

But after restarting the app, it will return the correct size.
I've updated the [tester app](https://github.com/jj-gh/photo_manager_tester) for your convenience.
