### ISSUE TITLE
Bug videos record on ios

### ISSUE THREAD

**Issue by NicolasCELLA** [CaiJingLong/flutter_photo_manager#317]
Hello, there's a problem with the videos record on ios in landscape format !

```
void _send(AssetEntity item) async {
    try {
    print('height ${item.height}');
    print('width ${item.width}');
  
   File video = await item.file;
   
    final MediaInfo _mediaInfo = MediaInfo();
    final Map<String, dynamic> mediaInfo =  await _mediaInfo.getMediaInfo(video.path);

    print('height ${mediaInfo['width']}');
    print('width ${mediaInfo['height']}');
}
```
Output:
```
AssetEntity = 
flutter: height 828
flutter: width 1792

File video = video;
flutter: height 1792
flutter: width 828
```
width and height hve been inverse ! 

An idea how to solve this problem ?

**Comment by mhstoller** [comment]
Check the AssetEntity's orientation property and see if it's rotated. Then, you can use this to get the correct height and width for your use case. If the orientation is 90 or 270 then the height and width are swapped.

```
print("Orientation: ${item.orientation}");
```

**Comment by NicolasCELLA** [comment]
output:
```
flutter: Orientation: 0
````

**Comment by mhstoller** [comment]
Maybe it's only implemented for images and not for videos

@CaiJingLong

**Comment by NicolasCELLA** [comment]
Ok Stop sorry I have inverse my print value ...

There are no problem on the File, but on my server only for videos record on ios the value are inverse !

**Comment by CaiJingLong** [comment]
@NicolasCELLA 
Sorry, I didn't understand. Is the problem with the photo_manager or your server?

Can I close the issue?

**Comment by NicolasCELLA** [comment]
Hello, sorry for the late reply

I have a problem with "ios record screen landscape"

from flutter:
```
flutter: height 828
flutter: width 1792
flutter: AssetType.video
```

from my server (node JS)
```
width: 828
height: 1792
```

The problem is only with this type of video (ios => record screen => landscape)

And this video is empty on my server 🧐

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
