### ISSUE TITLE
[BUG] Crash on iOS create album

### ISSUE THREAD

**Issue by Ashotjlavyan** [CaiJingLong/flutter_photo_manager#319]
This method 

```
PhotoManager.editor.iOS.createAlbum(
  name,
  parent: parent, // It is a folder or Recent album.
);
```

crashing on PMPlugin.m class in 288 line

`            NSDictionary *dictionary = @{@"id": id, @"errorMsg": errorMsg};
`

errorMsg is null and can't create dictionary with null.

**Comment by CaiJingLong** [comment]
If you can provide a reproducible example, I can try to solve it.
