### ISSUE TITLE
如何拿到每个相册的缩略图呢

### ISSUE THREAD

**Issue by JamesBondPc** [CaiJingLong/flutter_photo_manager#320]
flutter: [AssetPathEntity{ name: Recents, id:87574209-EE20-4693-832B-4CBB661F48F9/L0/040, length = 8 }, AssetPathEntity{ name: Screenshots, id:787B0176-78AD-4894-9641-21CBB228D79B/L0/040, length = 2 }]

**Comment by CaiJingLong** [comment]
Get the first AssetEntity from AssetPathEntity.
And get the thumb of AssetEntity
