### ISSUE TITLE
[BUG]图片数量未取完与photo_manager获取图片数量不一致，安卓

### ISSUE THREAD

**Issue by 120011676** [CaiJingLong/flutter_photo_manager#321]
[BUG]图片数量未取完与photo_manager获取图片数量不一致，安卓

**Comment by CaiJingLong** [comment]
More info?

**Comment by 120011676** [comment]
@CaiJingLong The picture under QQ folder cannot be obtained

**Comment by CaiJingLong** [comment]
You can try to set true of `ignoreSize`.
https://github.com/CaiJingLong/flutter_photo_manager/blob/28648ce9f690ef9d5c7ad9db0e1802f64d4177c1/lib/src/filter/filter_options.dart#L127
