### ISSUE TITLE
await PhotoManager.editor.saveVideo return `null`

### ISSUE THREAD

**Issue by zglnfsdyy** [CaiJingLong/flutter_photo_manager#327]
无法使用。这个方法。返回结果为null.无法得到实体

**Comment by CaiJingLong** [comment]
Other info？
Such as:  
1. plugin version.
2. android OS model and version.
3. pure gist code.
4. If you can, provide video file as zip or download url.

**Comment by rankyangel2014** [comment]
![image](https://user-images.githubusercontent.com/8031724/89021449-241f5180-d353-11ea-8ae4-523e4d452cc3.png)


save video 无效

**Comment by CaiJingLong** [comment]
@rankyangel2014 
Can you provide more info like next:

> Other info？
> Such as:
> 
> 1. plugin version.
> 2. android OS model and version.
> 3. pure gist code.
> 4. If you can, provide video file as zip or download url.

**Comment by PreviousTlx** [comment]
> ![image](https://user-images.githubusercontent.com/8031724/89021449-241f5180-d353-11ea-8ae4-523e4d452cc3.png)
> 
> save video 无效

请问下有解决办法了么，我也遇到一样的问题。

**Comment by PreviousTlx** [comment]
> 无法使用。这个方法。返回结果为null.无法得到实体

请问有解决办法么？我也遇到一样的问题。

**Comment by SUNbrightness** [comment]
> * plugin version.
> * android OS model and version.
> * pure gist code.
> * If you can, provide video file as zip or download url.



plugin version:0.5.8.
android version:10.

**Comment by SUNbrightness** [comment]
saveVideo 时加入参数title 可以解决这个问题.

**Comment by rignaneseleo** [comment]
Same error here with the version 1.2.2

Adding the `relativePath`, `title` and `desc` parameters don't solve the problem. 
It returns always `null`. 

No problems with `saveImageWithPath`

**Comment by AlexV525** [comment]
> Other info？
> Such as:
> 
> 1. plugin version.
> 2. android OS model and version.
> 3. pure gist code.
> 4. If you can, provide video file as zip or download url.

**Comment by rignaneseleo** [comment]
Here you are: 
    

- plugin version: 1.2.2
- android OS model and version: Android 10 and 11 don't work
- snippet: 

```
String output = "/data/user/0/boydpearce.my_grand_kids/app_flutter/9916_origin_IMG_5523.MOV";
AssetEntity a = await PhotoManager.editor.saveVideo(
                  File(output),
                  relativePath: output,
                  title: p.basename(output),
                  desc: "",
);
print(a);//-> null
```
I can't provide a video but I tried it with more than 30 videos (mp4 or MOV) and no one made it.

**Comment by AlexV525** [comment]
Why do you use `output` in `relativePath`?

**Comment by rignaneseleo** [comment]
Just for trying actually. It didn't work either in this way:
```
AssetEntity a = await PhotoManager.editor.saveVideo(
                  File(output),
);
```

**Comment by AlexV525** [comment]
Can you try this? https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/master/lib/src/widget/camera_picker_viewer.dart#L252

**Comment by AlexV525** [comment]
And your device model?

**Comment by rignaneseleo** [comment]
> Can you try this? https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/master/lib/src/widget/camera_picker_viewer.dart#L252

Sorry, but what do you mean by this?  The link brings me to a line of code that is basically the same as the one I'm using. 



> And your device model?

I tried it on Google Pixel 4a 5G (Android 11), Samsung Galaxy 9 (10)

**Comment by AlexV525** [comment]
I'm not sure whether it's related to your `output`'s path, since it looks like from the app's document directory. I'm wondering if your path is valid for read.

> Sorry, but what do you mean by this? The link brings me to a line of code that is basically the same as the one I'm using.

Add `title`.

```dart
AssetEntity a = await PhotoManager.editor.saveVideo(
  File(output),
  title: p.basename(output),
);
```

**Comment by AlexV525** [comment]
But we've heard some feedbacks related to this recently. Re-opening.

**Comment by rignaneseleo** [comment]
> I'm not sure whether it's related to your `output`'s path, since it looks like from the app's document directory. I'm wondering if your path is valid for read.
> 
> > Sorry, but what do you mean by this? The link brings me to a line of code that is basically the same as the one I'm using.
> 
> Add `title`.
> 
> ```dart
> AssetEntity a = await PhotoManager.editor.saveVideo(
>   File(output),
>   title: p.basename(output),
> );
> ```

I had `title` in the first snippet I sent you and it didn't work anyways. 
The path is the one from a downloaded file, I guess on Android 10-11 it goes in a temporary folder. It results to be different from the one I can get from `PhotoManager.getAssetPathList()` but that happens as well when dealing with photos.
The same logic but with `saveImageWithPath` works well and returns a complete `AssetEntity`.

**Comment by AlexV525** [comment]
@rignaneseleo Can you verify that whether the legacy storage is enabled in your project? Also is this issue reproducible using the example?

**Comment by AlexV525** [comment]
Tested with Samsung S9 (Android 10) with the demo from `wechat_camera_picker`, the method returned a valid result.

![image](https://user-images.githubusercontent.com/15884415/126298269-3e9a043c-3b8d-4e94-9a23-6328d3faf19d.png)
