### ISSUE TITLE
[BUG] PhotoManager.releaseCache() hangs

### ISSUE THREAD

**Issue by dvu714** [CaiJingLong/flutter_photo_manager#330]
**Describe the bug**
Calling PhotoManager.releaseCache() hangs and Future never completes and no errors are caught.  Cache is not released.
I'm looking to clear the cache as getAssetListPaged keeps growing the storage space.
**To Reproduce**
call await PhotoManager.releaseCache() 

**Expected behavior**
Cache to be released and Future completes.
**Flutter version**
1.17.5

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.5.1

**Comment by htetaunglin** [comment]
I also occur this problem.

**Comment by htetaunglin** [comment]
I have also this problem.

**Comment by AlexV525** [comment]
Is this still reproducible on the latest version?
