### ISSUE TITLE
gif image in ios, use "File file = await entity.file" return jpg, how get gif to upload

### ISSUE THREAD

**Issue by cizhaoyang** [CaiJingLong/flutter_photo_manager#333]
gif image in ios, use "File file = await entity.file" return jpg, how to get gif image to upload and preview, this in android is ok, but in ios is not working, i am used version is 0.5.6

**Comment by CaiJingLong** [comment]
> gif image in ios, use "File file = await entity.file" return jpg, how to get gif image to upload and preview, this in android is ok, but in ios is not working, i am used version is 0.5.6

Because HEIC cannot be directly used by flutter, the file is designed to be transcoded. If you want to obtain the original image, try to obtain titleAsync first, determine whether the name is the end of gif, and then use originFile to obtain the original resource.

See if it solves your problem.

**Comment by AlexV525** [comment]
`.file` will return a file that has been compressed with a default argument. Use `originalFile` to fetch the original one.
