### ISSUE TITLE
[BUG] Large video file (1GB) cannot determine the original file size and upload

### ISSUE THREAD

**Issue by 120011676** [CaiJingLong/flutter_photo_manager#335]
[BUG] Large video file (1GB) cannot determine the original file size and upload
Uint8List originBytes = await entity.originBytes;
The program will crash

**Comment by CaiJingLong** [comment]
For large videos, it is recommended to use file or originFile to complete the upload, because Uint8List will be loaded into the memory at one time.
Currently, no app can load such a large file at once.
