### ISSUE TITLE
[Feature]有没有适配iOS14的计划？

### ISSUE THREAD

**Issue by OctMon** [CaiJingLong/flutter_photo_manager#338]
在iOS14上选择相册直接闪退，希望能正常选择照片

**Comment by CaiJingLong** [comment]
Related https://github.com/CaiJingLong/flutter_photo/issues/134#issuecomment-660043896

**Comment by CaiJingLong** [comment]
Will support, but not now, I think we need to wait for Apple's API to stabilize and the documentation is in place.

**Comment by syssam** [comment]
any update?

**Comment by syssam** [comment]
@CaiJingLong any update?
