### ISSUE TITLE
[Feature] Get Original File Name

### ISSUE THREAD

**Issue by karstenriedel22** [CaiJingLong/flutter_photo_manager#339]
When I add a file to the gallery in IOS, the file name changes. But the original file name must be stored somewhere, because Google Photos shows the original file name.

Is it possible to retrieve the original file name in iOS and Android?

This way it would be possible to retrieve the same image on both Android and iOS devices after the image has been synchronized from one device to the other through Google Photos.

**Comment by CaiJingLong** [comment]
Use next code to include the library.

```dart
MaterialApp(
  builder: (context, widget) {
    return LoadingProvider(
      child: widget,
    );
  },
);
```

**Comment by CaiJingLong** [comment]
In iOS, the file name is not a public field, using this field to search for unknown risks (system updates may cause app crash).

**Comment by CaiJingLong** [comment]
Although PHAsset has a kvo attribute to get "originalFilename", it cannot be used as a predicate condition.

**Comment by leonardocustodio** [comment]
I have a similar issue. I save some data about the photo in my app database. And we have to find a way to keep this data when the user changes his phone model for example and download all pics again. I saw there is a field on iOS EXIF Dictionary called: kCGImagePropertyExifImageUniqueID. This field should not change even when redownloading the photo, right? Is there a way we could retrieve this value?

**Comment by leonardocustodio** [comment]
After some testing I saw that the "filename" (maybe the same as the ImageUniqueID?) is still kept when downloading a photo twice. I tested by saving a photo to the Files app in iOS than saving it back again on the Photo Library, I ended up with two images with the same "filename"...... But if just sharing and saving the photo directly in the gallery the filename changes.... I was thinking.... If we could have access to another field like the "keywords" for example, we could put a generated id there.... And in my tests this will be kept when saving the photo twice or sharing and saving it again......

Is this a feature we could implement?

**Comment by AlexV525** [comment]
Please submit new issues if anyone have more precise requests.
