### ISSUE TITLE
[BUG] Unable to fetch asset path list from an isolate

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#343]
Calling `PhotoManager.getAssetPathList(...)` from an isolate returns the following error:
```
No implementation found for method getGalleryList on channel top.kikt/photo_manager
```

`android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java` does not have an entry.

Would it be possible to expose this API so that the assets can be fetched from within an isolate?

Many thanks.

**Comment by CaiJingLong** [comment]
No plugins support calling from isolate.
