### ISSUE TITLE
Error getting thumbnails when used with .forceOldApi() in android 10?

### ISSUE THREAD

**Issue by Debjoy** [CaiJingLong/flutter_photo_manager#344]
## Problem

I want to get the thumbnail of a media file but I am getting an error fetching the thumbData. 
I have to use foreOldApi() to get the original file URL as I am using Android 10 . So when using that I am getting the error.

## Error Log

E/AndroidRuntime( 5671): FATAL EXCEPTION: pool-1-thread-4
E/AndroidRuntime( 5671): Process: com.atdebjoy.firecast, PID: 5671
E/AndroidRuntime( 5671): kotlin.NotImplementedError: An operation is not implemented: not implemented
E/AndroidRuntime( 5671): 	at top.kikt.imagescanner.core.utils.DBUtils.getThumbUri(DBUtils.kt:132)
E/AndroidRuntime( 5671): 	at top.kikt.imagescanner.core.PhotoManager.getThumb(PhotoManager.kt:84)
E/AndroidRuntime( 5671): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:212)
E/AndroidRuntime( 5671): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:26)
E/AndroidRuntime( 5671): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
E/AndroidRuntime( 5671): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 5671): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 5671): 	at java.lang.Thread.run(Thread.java:919)
I/Process ( 5671): Sending signal. PID: 5671 SIG: 9

**Comment by AlexV525** [comment]
Could you explain the relationship between "get the original file URL" and `forceOldApi()`?

**Comment by AlexV525** [comment]
Close with stale state.
