### ISSUE TITLE
[Feature] Detect files that have been deleted since a timestamp

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#345]
**Is your feature request related to a problem? Please describe.**
Currently the library does not provide a way to keep track of the files that have been deleted on disk.

**Describe the solution you'd like**
`AssetEntity` could contain an `isDeleted` property, and `getAssetPathList` could include those entities that have been deleted since `DurationConstraint.min`.

**Describe alternatives you've considered**
Currently whenever `AssetEntity.fromId()` returns `null`, I remove the corresponding file from my internal database. But I believe that the suggested solution is a better way to work around this issue.

**Comment by AlexV525** [comment]
Should this behavior valid? We all know that on Android entities might be broken in anytime, whether it's broken by other apps or the OS itself. How would we guarantee an entity is actually deleted since the concept was directly scanned from the media database?
