### ISSUE TITLE
[BUG]how to get real milliseconds in videoDuraion

### ISSUE THREAD

**Issue by godaangel** [CaiJingLong/flutter_photo_manager#348]
hello，thx for ur lib。
I have used assetEntity.videoDuration and I recognise this duration is not real milliseconds duration, maybe it's like math.round()，but I want more accurate number

I need to compare like this: videoDuraion > 4300ms ? ... : ...

**Comment by CaiJingLong** [comment]
This value is provided by the system SDK, it is not accurate.
Only when you decode the video can you get the most accurate duration.
