### ISSUE TITLE
[BUG] ( 1968): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

### ISSUE THREAD

**Issue by jpoh281** [CaiJingLong/flutter_photo_manager#351]
**Describe the bug**

**To Reproduce**

**Expected behavior**
`A clear and concise description of what you expected to happen.
`
**Screenshots**
![image](https://user-images.githubusercontent.com/54665433/90305544-eef03300-defe-11ea-98d4-ba90d882fc02.png)
I run this code. 

**Flutter version**

![image](https://user-images.githubusercontent.com/54665433/90305486-56f24980-defe-11ea-9357-296a868cfdeb.png)
**Smartphone (please complete the following information):**
 - Device:  pixel 3
 - OS:  android Q

**Log**

If applicable, add logs to help explain your problem.
![image](https://user-images.githubusercontent.com/54665433/90305472-388c4e00-defe-11ea-842d-bff8e4ffdb58.png)

```bash

```

**Comment by alejandrogiubel** [comment]
Any solution?

**Comment by dodatw** [comment]
I face same issue, any solution? why closed ?

**Comment by jpoh281** [comment]
@dodatw 
I did it copy them
go to flutter_photo_manager/example/android/app/src/main/kotlin/top/kikt/imagescannerexample/
![image](https://user-images.githubusercontent.com/54665433/106075797-af866d80-6151-11eb-8e2b-62f12ab8322c.png)

**Comment by dodatw** [comment]
Thanks. it work!

**Comment by stevelee98** [comment]
> @dodatw Tôi đã thực hiện sao chép chúng đi tới Flagship_photo_manager / example / android / app / src / main / kotlin / top / kikt / imagescannerexample / ![hình ảnh](https://user-images.githubusercontent.com/54665433/106075797-af866d80-6151-11eb-8e2b-62f12ab8322c.png)



> @dodatw I did it copy them go to flutter_photo_manager/example/android/app/src/main/kotlin/top/kikt/imagescannerexample/ ![image](https://user-images.githubusercontent.com/54665433/106075797-af866d80-6151-11eb-8e2b-62f12ab8322c.png)

How do you copy them? where to copy or do what? I am also getting the same error
