### ISSUE TITLE
[BUG] can not get thumbData

### ISSUE THREAD

**Issue by a-h-mzd** [CaiJingLong/flutter_photo_manager#353]
when calling ```thumbData``` on an ```AssetEntity``` it gives th following error:

```bash
E/PhotoManagerPlugin(26550): get 193 thumb error, width : 150, height: 150
E/PhotoManagerPlugin(26550): java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
E/PhotoManagerPlugin(26550): 	at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:344)
E/PhotoManagerPlugin(26550): 	at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:336)
E/PhotoManagerPlugin(26550): 	at com.bumptech.glide.Glide.get(Glide.java:179)
```

**Comment by CaiJingLong** [comment]
I think you can try to see https://github.com/bumptech/glide/issues/2821.

**Comment by alejandrogiubel** [comment]
Not solution yet for this problem? I need the thumbData and i got the same error. Any solution?

**Comment by alexlindroos** [comment]
I forced in gradle to use glide version 4.9.0 to fix this

**Comment by alejandrogiubel** [comment]
> I forced in gradle to use glide version 4.9.0 to fix this

Please can you give me an example? I am new in flutter and android.

**Comment by alexlindroos** [comment]
```
rootProject.allprojects {

    subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.github.bumptech.glide'
                        && details.requested.name.contains('glide')) {
                    details.useVersion '4.9.0'
                }
            }
        }
    }
}
```
I added this in to projects build.gradle and for me it worked

**Comment by AlexV525** [comment]
https://github.com/CaiJingLong/flutter_photo_manager#glide

**Comment by shilangyu** [comment]
This issue still persists. Adding the gradle hack and proguard does not help.

**Comment by AlexV525** [comment]
@shilangyu Please sunmit new issues with more info.

**Comment by shilangyu** [comment]
Crisis averted: to get it to work I had to set these exact versions for gradle (I was on v7):
- `4.1.0` in `build.gradle`
- `6.8.3` in `gradle-wrapper.properties`
