### ISSUE TITLE
[BUG]fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) not handled

### ISSUE THREAD

**Issue by haimo-free** [CaiJingLong/flutter_photo_manager#355]
fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding)未处理，使用同一个Flutter Engine时切换页面时该插件绑定的activity未改变。

修改建议：
 override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
    this.binding = binding
    plugin?.activity = binding.activity
    binding.addRequestPermissionsResultListener(createAddRequestPermissionsResultListener(permissionsUtils))
    if (plugin != null) {
      plugin?.let {
        binding.addActivityResultListener(it.deleteManager)
      }
    }
  }

**Comment by dong199101** [comment]
+1，赶紧修复；

**Comment by yy1300326388** [comment]
这个需要修复一下
