### ISSUE TITLE
ios删除图片会有提示

### ISSUE THREAD

**Issue by git-maven** [CaiJingLong/flutter_photo_manager#358]
有这样一个需求：
编辑图片以后保存，但是希望编辑过的图片在下一次访问相册的时候不被读取出来。
现在尝试过：
1.使用PhotoManager保存图片，然后退出页面后使用deleteById，但是ios上会提示是否删除，应该是ios的机制删除资源库的图片会有提示
2.保存在自己定义的文件夹，但是获取缩略图上又是一个问题
不知各位有什么好的解决方案呢

**Comment by CaiJingLong** [comment]
Save image to your app directory. You can try to use path_provider.

I think the function maybe shouldn't use the plugin.
