### ISSUE TITLE
[Feature]希望提供对iOS，iCloud图片支持

### ISSUE THREAD

**Issue by zjywill** [CaiJingLong/flutter_photo_manager#359]
现在如果图片在iCloud上，调用AssetEntity中

`  /// if you need upload file ,then you can use the file, nullable.`
` Future<File> get file async => PhotoManager._getFileWithId(this.id);`

将长时间卡在这个函数中，是否可以增加判断，看照片是否在iCloud中，或者给这个函数增加进度。

需要用iOS真机进行调试，虚拟机没模拟出iCloud环境。

**Comment by AlexV525** [comment]
iCloud 图片已经由 `PMProgressHandler` 支持，更多信息请参考 demo。
