### ISSUE TITLE
Cropping requires Source Path to Image

### ISSUE THREAD

**Issue by kthecoder** [CaiJingLong/flutter_photo_manager#363]
## Expect
What you want to achieve

To use: [image_cropper](https://pub.dev/packages/image_cropper)
The plugin requires the source path (absolute path).

```
ImageCropper.cropImage(
        sourcePath: imageFile.path,
        ...rest of code emitted...
 ));
```

How can I get that string with flutter_photo_manager?

**Comment by CaiJingLong** [comment]
Please read document or source code first.
