### ISSUE TITLE
[BUG] getAssetPathList don't contain empty albums.

### ISSUE THREAD

**Issue by kaich** [CaiJingLong/flutter_photo_manager#365]
**Describe the bug**

```
final list = await PhotoManager.getAssetPathList()
```

I want get all albums.  But the list don't contain the album that doesn't contain any photo. 

Please check. Thanks.

**Comment by CaiJingLong** [comment]
Normal, it does not include the album with empty content, I can add an option to let you get it, but it may be closed by default.

**Comment by kaich** [comment]
@CaiJingLong Thanks very much. I think you can also expose the album type and subtype for others situation. Make it more flexible.
