### ISSUE TITLE
[BUG]iPhone6 手机，切换到后台后，打开相机录视频，录制结束后，自己的app内存不足被系统杀死

### ISSUE THREAD

**Issue by William353** [CaiJingLong/flutter_photo_manager#366]
**Describe the bug**
iPhone6 手机，切换到后台后，打开相机录视频，录制结束后，自己的app内存不足被系统杀死，能帮忙看下吗 @CaiJingLong 

**Flutter version**
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale
    zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/wangpeng/Tools/flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [iOS12]

**Log**

Message from debugger: Terminated due to memory issue

```bash

```

**Comment by CaiJingLong** [comment]
Hi, the problem is iOS OS problem. I can't help you.
