### ISSUE TITLE
[Feature] Filter by create date

### ISSUE THREAD

**Issue by thanhbinh84** [CaiJingLong/flutter_photo_manager#371]
**Is your feature request related to a problem? Please describe.**
Currently, there is an optional to filter from start date to end date, but it is based on modified date. 

**Describe the solution you'd like**
Add one more param to filter by modified date or create date. 

**Describe alternatives you've considered**
I have to loop all files to filter by create date manually 

**Additional context**

**Comment by CaiJingLong** [comment]
Unlike what you said, it is currently filtered based on the creation time.
If you need to increase it, it should also increase the modification time filter, but it depends on whether iOS provides this field.

**Comment by thanhbinh84** [comment]
Could you double check, I am using stable version 0.5.8, tried example code and my own code, filter with start date is yesterday and end date is today, but the list contains all images. If I filter today only, it shows no image, it is neither based on modified nor create date.

**Comment by AlexV525** [comment]
This should be fixed in https://github.com/CaiJingLong/flutter_photo_manager/blob/master/CHANGELOG.md#110 .
