### ISSUE TITLE
Android：华为手机，获得的视频，拿到的width和height，有些视频正常拿到，有些拿到是0

### ISSUE THREAD

**Issue by xiaoxiaokong** [CaiJingLong/flutter_photo_manager#376]
打印了convertCursorToAsset函数中的 val width = cursor.getInt(MediaStore.MediaColumns.WIDTH)     val height = cursor.getInt(MediaStore.MediaColumns.HEIGHT)，值为0

**Comment by AlexV525** [comment]
部分资源原生信息不完整
