### ISSUE TITLE
[BUG] Endless loading asset file from iCloud on iOS

### ISSUE THREAD

**Issue by Artem2908** [CaiJingLong/flutter_photo_manager#377]
I'm using asset.file() to get the image file. This almost always works fine, but if there are a lot of images on iOS (in my case, there are more than 75,000 photos in iCloud), the asset.file(), asset.thumbData() and asset.thumbDataWithSize() starts endless loading without errors

Flutter version:
Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E287, locale en-GB)

**Comment by gjrjf** [comment]
Same here..

**Comment by cs-hyunseo** [comment]
Same issue. 
Is there a solution?

**Comment by gabdsg** [comment]
I have the same problem

**Comment by gulmensedat** [comment]
The images I use from icloud may crash, I am looking for a solution to the problem.

**Comment by emiliodallatorre** [comment]
I think I'm gonna workaround this by putting a timeout in file loading and by adding a button to load files with `image_picker`.

**Comment by TykanN** [comment]
I reproduced it too.
'getAssetPathList' takes too long time probably because of icloud images.

**Comment by yanivshaked** [comment]
Same here, some calls to `AssetEntity.file` never return. It does work on the second invocation.
Any temporary workaround @CaiJingLong ?

**Comment by AlexV525** [comment]
For everyone that still facing this issue, please check whether the `1.2.6` version fixed this issue or not.

**Comment by MagTuxGit** [comment]
1.2.8, iCloud photos still hangs

**Comment by AlexV525** [comment]
> 1.2.8, iCloud photos still hang

Please provide more info including usage code, logs, etc.

**Comment by MagTuxGit** [comment]
> > 1.2.8, iCloud photos still hang
> 
> Please provide more info including usage code, logs, etc.

I'm trying to fix this actually.
Details I put [here](https://github.com/CaiJingLong/flutter_photo_manager/issues/411)
