### ISSUE TITLE
[BUG] Calling Api from another isolate

### ISSUE THREAD

**Issue by TheArchitect123** [CaiJingLong/flutter_photo_manager#378]
Hello,

Does this plugin allow support for getting asset items from a different isolate? I'm trying to get a collection of asset paths from the user's local photo gallery, and it fails if I try to invoke the method **await PhotoManager.getAssetPathList(filterOption: imageOptions)**. Below is the log: 

**NoSuchMethodError: The getter 'defaultBinaryMessenger' was called on null**

**Comment by CaiJingLong** [comment]
#343
