### ISSUE TITLE
video select and detail

### ISSUE THREAD

**Issue by gulmensedat** [CaiJingLong/flutter_photo_manager#379]
I use it like here
https://medium.com/@mhstoller.it/how-to-create-a-custom-media-picker-in-flutter-to-select-photos-and-videos-from-the-gallery-988eea477643

my problem is I can't select the videos I've listed, so I can't access any details. I downloaded the example from github, tested it, it works corrupt, what would you recommend?

**Comment by leonalonso** [comment]
Hi, I have the same problem, and I absolutely don't know how to fix it. Were you successful?

**Comment by AlexV525** [comment]
If you're looking for a picker, try [wechat_assets_picker](https://pub.dev/packages/wechat_assets_picker).
