### ISSUE TITLE
 Build failed with an exception.  FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by AcmeField** [CaiJingLong/flutter_photo_manager#389]
**When i Try to run "Flutter Run" on the Android emulator**
```
/mine/app/flutter/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-0.5.8/android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt: (154, 50): Type mismatch: inferred type is Uri? but Uri was expected
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':photo_manager:compileDebugKotlin'.          
> Compilation error. See log for more details         
```    

**flutter doctor -v**                

[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
    • Flutter version 1.22.0 at /Users/xiehui/mine/app/flutter
    • Framework revision d408d302e2 (5 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/xiehui/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.7846.93

[✓] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by AlexV525** [comment]
Please use the latest version of the package.

**Comment by ClarkChu07** [comment]
solution：

> flutter clean
> flutter clean
> flutter pub cache clean
> flutter pub get
