### ISSUE TITLE
Easy way to bypass media caching on AndroidQ to play original video/view original image in full size

### ISSUE THREAD

**Issue by github3t** [CaiJingLong/flutter_photo_manager#393]
I use Photo_Manager to display media galleries and assets to pick avatars or attach media to a database entity.
When viewing an attached AssetEntity (using .fromId()) using the .originFile getter, the system is always making a deep copy of the original file. In a gallery with lots of videos this explodes the cache considerably and the viewer has to wait a very long time before videos start playing.

Is there an easy solution to get the real original file descriptor to pass to an image/video viewer widget? 

The .relativePath getter seems appropriate here, but I have no idea how to use it properly.
Do you have any ideas?

When requesting .thumbData or .thumdDataWithSize() the system does not seem to have to make a deep copy. So it appears there is a way to access the real original file.

**Comment by github3t** [comment]
I've found a way to bypass the cache for video by looking at the wechat_asset_picker code. It uses the .getMediaUrl() function. But this only works for video according to the docs 

As camera resolutions keep rising images can be quite large too. Is there a way to bypass the cache for images like video?

**Comment by AlexV525** [comment]
When we run into the process of `Uri` -> `Bitmap`, the entity must be copied to the cache directory before using it.

**Comment by AlexV525** [comment]
Closing with stale state.
