### ISSUE TITLE
[BUG]钉钉保存图片到相册中，用photo_manager无法检索到该图片

### ISSUE THREAD

**Issue by moriliefeng** [CaiJingLong/flutter_photo_manager#400]
最近使用photo_manager发现钉钉保存的图片，用这个组件来检索时，找不到任何信息，其他图片正常，如果把这张找不到的图片移动到任何一个文件夹中，就可以被检索到；而且该图片保存在相册中时，用微信或者抖音之类的社交app去打开相册是可以找到该图片，烦请作者能不能提供点思路！打扰打扰

**Comment by dodatw** [comment]
I face same issue!

**Comment by qinsong729** [comment]
1. 升级到最新版本；
2. imageOption: FilterOption(
          sizeConstraint: SizeConstraint(
            ignoreSize: true,
          ),
        )
3.ok

**Comment by AlexV525** [comment]
使用 ignoreSize 后是否可以找到？

**Comment by AlexV525** [comment]
Closing with stale state.
