### ISSUE TITLE
[BUG] Video orientation reported incorrectly (Android)

### ISSUE THREAD

**Issue by mhstoller** [CaiJingLong/flutter_photo_manager#401]
**Describe the bug**
Using the provided video, photo_manager reports the orientation as 0. When reading the metadata with ffmpeg, the orientation is correctly reported as -90°.

**To Reproduce**
-Download video here: https://drive.google.com/file/d/11Ep-AviR_fGNcXIhrtj6yIUwGs_Os13z/view?usp=sharing
-Use photo_manager to create an AssetEntity for the video
-Check the orientation value, it's reported as 0.

**Expected behavior**
Orientation should be reported as -90 (270) by reading the metadata.

**Screenshots**
Values reported by photo_manager:
![image](https://user-images.githubusercontent.com/36415486/100270596-4bafb080-2f26-11eb-91d0-0160e0ca2e8c.png)

Values reported by ffmpeg:
![image](https://user-images.githubusercontent.com/36415486/100270737-83b6f380-2f26-11eb-9b88-1c4addb7a6ae.png)

**Flutter version**
```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.0 at /Users/max/development/flutter
    • Framework revision d408d302e2 (8 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/max/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Lenovo P2a42 (mobile) • ZY223WSV6Z • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Smartphone (please complete the following information):**
 - Device: Lenovo P2a42
 - OS: Android 7.0 (API 24)

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
