### ISSUE TITLE
[BUG] Videos with no file extension don't report metadata correctly (Android)

### ISSUE THREAD

**Issue by mhstoller** [CaiJingLong/flutter_photo_manager#402]
**Describe the bug**
When a video does not have a file extension, photo_manager doesn't report the video information correctly. It reports height, width, aspect ratio, and duration as 0.

**To Reproduce**
Download video here: https://drive.google.com/file/d/1CxdIQuAfBT4PjvinCypvWSvyXCTsyd-i/view?usp=sharing
Create an AssetEntity from the video
Observe values

**Expected behavior**
By reading the video metadata it should be possible to report these values correctly even without a file extension.

**Screenshots**
photo_manager outputs:
![image](https://user-images.githubusercontent.com/36415486/100271647-d218c200-2f27-11eb-952a-4e8232b2d189.png)
![image](https://user-images.githubusercontent.com/36415486/100271857-2d4ab480-2f28-11eb-8387-e2f7834f5acb.png)

**Flutter version**
```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.0 at /Users/max/development/flutter
    • Framework revision d408d302e2 (8 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/max/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Lenovo P2a42 (mobile) • ZY223WSV6Z • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Smartphone (please complete the following information):**
- Device: Lenovo P2a42
- OS: Android 7.0 (API 24)

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
