### ISSUE TITLE
[BUG] Album assets sorted incorrectly (iOS)

### ISSUE THREAD

**Issue by mhstoller** [CaiJingLong/flutter_photo_manager#403]
**Describe the bug**
After downloading a video from the internet that has a creation date of June 30, 2018 the video is the most recent asset in my iPhone's "Recent" album. When using `PhotoManager.getAssetPathList(onlyAll: true)` and then `getAssetListPaged` the video is not shown as the most recent asset, but instead is sorted by creation date.

**To Reproduce**
Download video: https://drive.google.com/file/d/11Ep-AviR_fGNcXIhrtj6yIUwGs_Os13z/view?usp=sharing
Check sorting order returned from getAssetListPaged calls

**Expected behavior**
The sorting order should be the same as the default iOS album order. I believe it's sorted by date added on iOS, not date created. Or there should be a new option to choose which sorting method you want to use.

**Flutter version**
```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.0 at /Users/max/development/flutter
    • Framework revision d408d302e2 (8 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/max/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Lenovo P2a42 (mobile) • ZY223WSV6Z                               • android-arm64 • Android 7.0 (API 24)
    • iPhone (mobile)       • 7b07f3aafba77d607ef3d612ad70b014a542fdc3 • ios           • iOS 13.6.1

• No issues found!
```

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.6.1

**Comment by wenboLee** [comment]
+1

**Comment by wenboLee** [comment]
My solution:

**Comment by wenboLee** [comment]
But, there are not shown as the most recent asset in PhotoLibary. 😞

**Comment by wenboLee** [comment]
AirDrop a big origin pic to iphone. @rcunning @vishna @YannickBiet

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
