### ISSUE TITLE
Access Smart Albums (People and Places albums)

### ISSUE THREAD

**Issue by barfet** [CaiJingLong/flutter_photo_manager#404]
Hello, and thank you for this library.

Is it possible to get access to 'People' and 'Places' albums using this library?
I tried to use `List<AssetPathEntity> list = await PhotoManager.getAssetPathList();` and it returns some Smart Albums, like 'Favorites' and 'Recently Added', but there is no 'People' and 'Places' albums.

Thanks.

**Comment by AlexV525** [comment]
Any documents from Apple that indicate how to sort them out directly?
