### ISSUE TITLE
[BUG] Updated items are not returned by getAssetPathList on iOS

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#407]
**Description**
If I edit a photo within the iOS Photos app (crop/add a filter), and call `getAssetPathList` on iOS with correct `updateTimeCond` within the `filterOption`, it does not return the list of images that have been edited.

I'm building a photo-backup service, and due to this bug I'm unable to detect and upload updated files.

**Expected behavior**
`getAssetPathList` should also return a list of assets that were updated within the `updateTimeCond`.

**Flutter version** 1.22.2

**flutter_photo_manager version** 0.6.0-dev.7

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.2

Thanks for this library.

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
