### ISSUE TITLE
通过PhotoManager.addChangeCallback监听，是否有拿到新添加的资源api

### ISSUE THREAD

**Issue by maskletter** [CaiJingLong/flutter_photo_manager#408]
![image](https://user-images.githubusercontent.com/15777183/101241912-3fe99880-3735-11eb-99ba-ec30a5c2661c.png)
我输出到的是下面的内容

![image](https://user-images.githubusercontent.com/15777183/101241954-7c1cf900-3735-11eb-83fa-dd0f47fa0bbc.png)

我想监听图片资源变动时候，对当前页面进行更新

**Comment by AlexV525** [comment]
变动是一个通知，并不包含完整的 entity 信息。
