### ISSUE TITLE
[BUG]保存比较大的图片，在最近项目里不能按正常顺序显示

### ISSUE THREAD

**Issue by LvOlivia** [CaiJingLong/flutter_photo_manager#409]
在iOS系统，保存几张不超过4MB的图片，最近项目里可按顺序正常显示；再保存一张大图(7.8MB)，然后保存1MB的图片，发现大图依然保持在最近项目里的最后一张。
导致：手机里有很多照片时，保存新的图片，在最近项目里非常难找到。

**Comment by AlexV525** [comment]
> Is this still reproducible in the latest version (1.2.1)?

最新 1.2.1 版本是否可以重现？

**Comment by AlexV525** [comment]
Closing with stale state.
