### ISSUE TITLE
不加载文件如何获得文件大小

### ISSUE THREAD

**Issue by xjcjackin** [CaiJingLong/flutter_photo_manager#410]
你好，我如果想要获取文件占用存贮的大小，必须final File file = await entity.file;final int size = file.length();这样子才能获取到。
必须要等待文件被加载，这样子很慢，有没有方法或者能不能提供无须加载文件就可以得到文件大小的方式呢？

**Comment by AlexV525** [comment]
文件大小信息并没有被直接被存储在系统中，需要实际取出后才有结果。

**Comment by wengxianxun** [comment]
@xjcjackin  有没有好方法
