### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yj229201093** [CaiJingLong/flutter_photo_manager#416]
点击获取照片闪退，调试真机iPhone12闪退，不懂是否和全面屏有关系，iphone6sp黑屏，模拟器iPhone12黑屏，
photo_manager: ^0.6.0-dev.8
使用的就是获取代码的方法

```dart
try {
        final List<AssetEntity> result = await AssetPicker.pickAssets(
          context,
          maxAssets: maxSelected,
          requestType: RequestType.image,
        );
        if (result != null) {
          List<File> resultList = [];
          for (var e in result) {
            File file = await e.file;
            resultList.add(file);
            Utils.logs("file = " + file.path);
          }
          return resultList;
        }
      } catch (e) {
        Utils.logs(e.toString());
      }
```

![image](https://user-images.githubusercontent.com/12807664/102754154-7ff08280-43a7-11eb-893d-60b8706a442f.png)
![image](https://user-images.githubusercontent.com/12807664/102754193-8da60800-43a7-11eb-8d3c-915ebb670e51.png)
![image](https://user-images.githubusercontent.com/12807664/102754225-972f7000-43a7-11eb-81e4-662db39d488c.png)
![image](https://user-images.githubusercontent.com/12807664/102754987-bbd81780-43a8-11eb-846f-de30823957aa.png)

**Comment by CaiJingLong** [comment]
没有更多的信息吗？
我使用iOS14真机，模拟器都未出现这种问题
不过因为本人没有iphone12真机，未尝试这个版本

我的环境：
flutter: 1.22.4
photo_manager: 0.6.0-dev.8
wechat_assets_picker: master 版本

**Comment by angry-birds** [comment]
同样的问题，都出现了，只有权限为【所有照片】时才会触发。
iPhone11，iOS14.4.2
iPhoneX，iOS14.4.1

**Comment by AlexV525** [comment]
> Is this still reproducible in the latest version (1.2.1)?

1.2.1 版本是否可以重现？

**Comment by AlexV525** [comment]
Closing with stale state.
