### ISSUE TITLE
[BUG] iOS 12 Crash 

### ISSUE THREAD

**Issue by yy1300326388** [CaiJingLong/flutter_photo_manager#418]
**Describe the bug**
Photos Framework crash: 'This application is not allowed to access Photo data.'

**To Reproduce**
1. Start the app, and then click `Don't allow` to read the album
2. Click on the simulator `Debug` and then `Simulate Memory Warning`
3. Then it will crash

![image](https://user-images.githubusercontent.com/8764899/103262288-82725e00-49df-11eb-8528-09b1582d5e17.png)

**Expected behavior**

Not crash
**Screenshots**
![image](https://user-images.githubusercontent.com/8764899/103262489-09273b00-49e0-11eb-83b8-024a90582970.png)

**Flutter version**

**Smartphone (please complete the following information):**
 - Device: [ iPhone 6 Plus]
 - OS: [iOS 12.4]

**Log**

```bash
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'This application is not allowed to access Photo data.'
terminating with uncaught exception of type NSException
CoreSimulator 732.17 - Device: iPhone 6 Plus (4B2F07AD-763B-42BE-AA9C-87D0DD712E0B) - Runtime: iOS 12.4 (16G73) - DeviceType: iPhone 6 Plus
```
** Reference**
- https://www.jianshu.com/p/8ffa8ac3f523
- https://stackoverflow.com/questions/33266346/photos-framework-crash-this-application-is-not-allowed-to-access-photo-data

**Comment by NSLogZfRee** [comment]
same issue

**Comment by CaiJingLong** [comment]
Have you tried the latest version?
And, I think you may not have given the application permission to access the Photos.

**Comment by AlexV525** [comment]
Please provide the package version you're using.

**Comment by CaiJingLong** [comment]
Or, provide flutter project(github repo) to reproduce it to help me location error?

**Comment by NSLogZfRee** [comment]
0.6.0.    Flutter 1.22.5 • channel stable • git@github.com:flutter/flutter.git .  so we can't use lastest version which is support flutter 2.0.

**Comment by AlexV525** [comment]
We can't support an outdated version. Please verify with the latest version.

**Comment by AlexV525** [comment]
Closing with stale state.
