### ISSUE TITLE
[BUG]Type mismatch: inf erred type is Uri? but Uri was expected

### ISSUE THREAD

**Issue by tadpole145** [CaiJingLong/flutter_photo_manager#419]
**Describe the bug**
when i build my project with the cmd 'flutter build apk', a problem was occured as below:
 ...\.pub-cache\hosted\pub.flutter-io.cn\photo_manager-0.5.8\android\src\main\kotlin\top\kikt\imagescanner\core\utils\IDBUtils.kt: (154, 50): Type mismatch: inferred type is Uri? but Uri was expected

How can I solve this problem? please help me! thanks!

**Comment by LittleTadpole** [comment]
设置kotlin_version = '1.4.20不报错,设置为kotlin_version = '1.4.21' 就报错,不知道为啥

**Comment by AlexV525** [comment]
Please use the latest version of the package.
