### ISSUE TITLE
[Custom] Crash when used in combination with VideoCompress (https://github.com/jonataslaw/VideoCompress)

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [CaiJingLong/flutter_photo_manager#423]
Hi,
When picking a video from library, i get a crash when trying to compress it with [(https://github.com/jonataslaw/VideoCompress)](https://github.com/jonataslaw/VideoCompress).

All other case works (taking video from camera, using [https://pub.dev/packages/image_picker)](https://pub.dev/packages/image_picker)

## Expect
Compression still works

Is someone using VideoCompress ?

Thanks,
Nelson

**Comment by AlexV525** [comment]
Please provide all info about the package, like version info, device info, minimum usage code.

**Comment by AlexV525** [comment]
Closing with stale state.
