### ISSUE TITLE
[BUG] App freezes with allowing PermissionRequest on iOS 14.4 with Version 0.6.0

### ISSUE THREAD

**Issue by filly82** [CaiJingLong/flutter_photo_manager#432]
After upgrading to Version 0.6.0 I've noticed that my App freezes everytime on loading the Images with this library.
It happens directly after allowing the PermissionRequest or if I start my App with allowed Permission Status.
If I revoke the permission then the App unfreezes but of course I cannot load any Photos

Nothing changed in my code, I am requesting the Permissions with

`await PhotoManager.requestPermission();`

I've read that something changed with Version 0.6.0 regarding permissions

> User can ignore check permission(User can choose favorite permission plugin, but at the same time user have to bear the risks corresponding to the permission).

Do I have to do anything different in my code?

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
