### ISSUE TITLE
Delete cause Unhandled Exception - type 'bool' is not a subtype of 'List<dynamic>'

### ISSUE THREAD

**Issue by JmyW** [CaiJingLong/flutter_photo_manager#433]
Simply execute delete function, it causes an exception as following.

[Version]
0.6.0
[Reproduce Steps]
final List<String> result = await PhotoManager.editor.deleteWithIds([entity.id]);
[Result]
The photo in Album is able to be truly deleted but an error message is logged as following. That looks like your deleteWithIds of plugin.dart is not casted to correct type.

================================================================
flutter ( 3928): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'bool' is not a subtype of type 'List<dynamic>' in type cast
E/flutter ( 3928): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)
E/flutter ( 3928): <asynchronous suspension>
E/flutter ( 3928): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 3928): #2      Plugin.deleteWithIds (package:photo_manager/src/plugin.dart:170:25)
E/flutter ( 3928): #3      Editor.deleteWithIds (package:photo_manager/src/editor.dart:19:20)
E/flutter ( 3928): #4      _PhotoPageState.deleteImage (package:kindergartenteacher/pages/photopage.dart:329:64)
E/flutter ( 3928): #5      _PhotoPageState.build.<anonymous closure> (package:kindergartenteacher/pages/photopage.dart:229:38)
E/flutter ( 3928): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 3928): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 3928): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 3928): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 3928): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 3928): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 3928): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 3928): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 3928): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 3928): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 3928): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 3928): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 3928): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 3928): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 3928): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 3928): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 3928): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 3928): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 3928): #24     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 3928): #25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 3928): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 3928): #27     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 3928): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by AlexV525** [comment]
Seems been resolved by #460 .
