### ISSUE TITLE
[Feature] Sort using Date

### ISSUE THREAD

**Issue by prateekmedia** [CaiJingLong/flutter_photo_manager#437]
**Is your feature request related to a problem? Please describe.**
Currently the library on gives the categories based on the folder name, but what if I want all photos but categorized by their date created.

**Describe the solution you'd like**
Provide a more advanced filter by which It can automatically sort by the parameter provided instead of the old regular folder name approach.

**Comment by AlexV525** [comment]
Supported from 1.1.0 .
