### ISSUE TITLE
[BUG] the app crashes in background when permissions are changed in settings (iOS)

### ISSUE THREAD

**Issue by sstadtl** [CaiJingLong/flutter_photo_manager#439]
**Describe the bug**
If i decline permission to pictures, open the settings with PhotoManager.openSetting() and then
change them my app crashes in background.

lib version 6.0

**Flutter version**
Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-DE)

**Smartphone (please complete the following information):**
simulator 14.4
iPhone12 14.4
iPhone7 14.4

**Log**

Lost connection to device.
Exited (sigterm)

**Comment by jaysignorello** [comment]
@sstadtl this just happens in debug mode for me. Otherwise works fine.
