### ISSUE TITLE
how to display only image in gridview by suing this package

### ISSUE THREAD

**Issue by pavanZibtek** [CaiJingLong/flutter_photo_manager#440]
## Expect
What you want to achieve

## ScreenShots
Screenshots showing the purpose.

**Comment by mhstoller** [comment]
https://medium.com/@mhstoller.it/how-to-create-a-custom-media-picker-in-flutter-to-select-photos-and-videos-from-the-gallery-988eea477643

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo_manager#you-get-all-of-asset-list-gallery
Use type to get the image.

For others, please check the above article or the project example.
