### ISSUE TITLE
PhotoManager.editor.deleteWithIds(ids) caused Unhandled Exception: type 'bool' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by shofizone** [CaiJingLong/flutter_photo_manager#442]
I trying to delete with PhotoManager.editor.deleteWithIds(ids) and it gave me this error. But It actually deleting file form storage. I am using photo_manager: ^0.6.0 , test device android 8.1 and Flutter Channel stable, 1.22.6
**This issue shows up while deleting a video.** 
```
E/flutter (17860): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'bool' is not a subtype of type 'List<dynamic>' in type cast
E/flutter (17860): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)
E/flutter (17860): <asynchronous suspension>
E/flutter (17860): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (17860): #2      Plugin.deleteWithIds (package:photo_manager/src/plugin.dart:170:25)
E/flutter (17860): #3      Editor.deleteWithIds (package:photo_manager/src/editor.dart:19:20)
```

**Comment by shofizone** [comment]
@CaiJingLong Ony progress on this issue?

**Comment by AlexV525** [comment]
Is this issue still reproducible in the latest version?

**Comment by shofizone** [comment]
Yes ! on Android 8.1 
I/PhotoManagerPluginLogger(25013): onGranted call.method = deleteWithIds
E/flutter (25013): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'bool' is not a subtype of type 'List<dynamic>'
E/flutter (25013): #0      Plugin.deleteWithIds (package:photo_manager/src/plugin.dart:170:25)
E/flutter (25013): <asynchronous suspension>
E/flutter (25013): #1      AssetPathProvider.deleteSelectedAssets (package:image_scanner_example/model/photo_provider.dart:305:5)
E/flutter (25013): <asynchronous suspension>
E/flutter (25013):

**Comment by AlexV525** [comment]
Thanks for the clarification. Could you provide more info about the flutter version, device model, and the usage code? (Please wrap your code with ```)

**Comment by shofizone** [comment]
Device Model: Redmi 5 Plus (Xiaomi)
Code: 
```
  Future deleteFiles(List<AssetEntity> files) async {
    List<String> ids = files.map((e) => e.id).toList();
    try {
      await PhotoManager.editor.deleteWithIds(ids);
      return;
    } catch (e) {
      print("$e");
    }
  }
```
NB: I have cloned the flutter_photo_manager repository and found the same error with the example. but the same code is working on android 11.
Flutter version:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] VS Code, 64-bit edition (version 1.53.2)
[√] Connected device (4 available)
```

**Comment by shofizone** [comment]
Issue updated!
This issue shows up while deleting a **video**. But deleting the **image** file working fine.

**Comment by shofizone** [comment]
I think this the issue.  `resultHandler.reply(true)` . It should return a list of ids, isn't it?
![image](https://user-images.githubusercontent.com/24232207/112435983-a986c480-8d6f-11eb-8d1f-efeaa38090d6.png)

**Comment by shofizone** [comment]
I have created a pull request. #460

**Comment by AlexV525** [comment]
I'm waiting to another PR to see whether we can publish these fixes together, but I'll publish a new version if it takes too long. Thanks again for your fix and the report.
