### ISSUE TITLE
Thumb data of Video fails: --- SkAndroidCodec::NewFromStream returned null

### ISSUE THREAD

**Issue by LuisMaGit** [CaiJingLong/flutter_photo_manager#443]
**Describe the bug**
Hi,
I'm facing these error when getting the thumbData for assets type videos: 

--- SkAndroidCodec::NewFromStream returned null,

these happens mostly the first time trying to fetch the assets of the phone, it gets stuck for a while trying to get the thumbData for videos and throws the --- SkAndroidCodec::NewFromStream returned null.

**photo_manager 0.6.0**

**Flutter version**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [VersiÃ³n 10.0.14393], locale es-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

**Log**
--- SkAndroidCodec::NewFromStream returned null,

**Comment by AlexV525** [comment]
Is this still reproducable with the latest version? Was it happen to a specific video?
