### ISSUE TITLE
File path of deleted file missing

### ISSUE THREAD

**Issue by AndreGroeschel** [CaiJingLong/flutter_photo_manager#444]
**Describe the bug**
In our app we would like to observe deletion events from the gallery. To get this info we use PhotoManager.addChangeCallback. There is a deletion event but the path to the deleted file is missing

**To Reproduce**
1. Listen to changes using PhotoManager.addChangeCallback
2. Delete an image from the gallery
3. Check value.arguments['uri]

**Expected behavior**
value.arguments['uri] should contain the path to the file that was deleted

**Actual behavior**
value.arguments['uri]  only contains the path to the folder 

**Screenshots**
![image](https://user-images.githubusercontent.com/7644444/108714176-8327fc00-7519-11eb-9a35-5d04f3044f54.png)

**Flutter version**
1.22.6

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Mi 8 Pro]
 - OS: Android 10 API Level 29

**Comment by AlexV525** [comment]
`uri` field represents the Content Uri in the `MediaStore`, rather than a path.
