### ISSUE TITLE
[BUG] Getting file from icloud using entity.file is waiting too long

### ISSUE THREAD

**Issue by srubob** [CaiJingLong/flutter_photo_manager#446]
**Describe the bug**
For the users who use iCloud, accessing all pictures might lead to getting stuck at some point because the file is in iCloud. If the app is closed and reopened, then this file will be retrieved quickly, but the same thing happens for the next file. 

**Is there a way to call these files but skip and come back later so that they will be downloaded by then?**

**To Reproduce**
Backup your pictures on iOS and try to access your pictures using this library using entity.file

**Expected behavior**
You should get the file data

**Flutter version**
 1.22.6 

**Smartphone (please complete the following information):**
 - Device: iPhone11 Pro Max, iPhone X
 - OS: 14.4

**Comment by AlexV525** [comment]
Please implement this by combine the `AssetEntity.isLocallyAvailable` and the `PMProgressHandler` together.

**Comment by brax10ward** [comment]
@AlexV525 if the file is not locally available how can it be made locally available?

**Comment by AlexV525** [comment]
You can do something like:

```dart
final File file;
final bool isLocallyAvailable = await entity.isLocallyAvailable;
if (isLocallyAvailable) {
  file = await entity.originFile;
} else {
  final progressHandler = PMProgressHandler();
  progressHandler.stream.listen((event) {
    final progress = event.progress;
    print('progress state onChange: ${event.state}, progress: $progress');
  });
  file = await entity.loadFile(progressHandler: progressHandler, isOrigin: true);
}
```

Here are some snippet from the example:

https://github.com/CaiJingLong/flutter_photo_manager/blob/83bb86507af6f399bffd878af8197d8e7c069626/example/lib/page/image_list_page.dart#L181-L183

https://github.com/CaiJingLong/flutter_photo_manager/blob/83bb86507af6f399bffd878af8197d8e7c069626/example/lib/page/image_list_page.dart#L454-L459

**Comment by brax10ward** [comment]
@AlexV525 Thanks! This has made our app so much better!
