### ISSUE TITLE
[BUG] iOS albums issue

### ISSUE THREAD

**Issue by anshul01sharma** [CaiJingLong/flutter_photo_manager#447]
Hi, I am facing the issue in the iOS regarding the albums.

In th Android when I used this line "List<AssetPathEntity> albums = await PhotoManager.getAssetPathList(onlyAll: false);" then it will return all the albums of the device, but in the iOS it only return 1-2 albums like favorite ony. I need to display all the albums in my app and then on click of the albums I need to display the images of the album. So please let me know the issue I am facing in the iOS. I am testing in the iOS14.

Please help ASAP.

**Comment by barees63** [comment]
Check that you have selected permission "All Photos" rather than "Selected Photos"?

**Comment by right7ctrl** [comment]
Same here, any updates?

**Comment by AlexV525** [comment]
Should be fixed by #601 .
