### ISSUE TITLE
[REQUEST] The new null safety code design has a serious design issue regarding the AssetEntity constructor

### ISSUE THREAD

**Issue by Letalus** [CaiJingLong/flutter_photo_manager#451]
When I just recently updated the package to 5.0.1 it hit me pretty hard.
According to the own documentation the f.e. duration of an AssetEntity should have a default value of 0.
Yet within null safety it is declared as required.

Furthermore the property isFavorite or orientation is also set as required even if they are platform specific properties --> then those kind of properties should not really be set to required.

I'm using the AssetEntity object pretty often within my app.

Therefore I suggest, that we change the declaration of the AssetEntity constructor the following way, so it will become more readable and understandable:

  AssetEntity({
    required this.id,
    required this.typeInt,
    this.duration = 0,
    this.width = 0,
    this.height = 0,
    this.orientation = 0,
    this.isFavorite = false,
    this.title,
    this.createDtSecond,
    this.modifiedDateSecond,
    this.relativePath,
  });

I really hope we can improve the code, because many values really don't need to be required

**Comment by AlexV525** [comment]
Sorry for the late response. The original issue is https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/89 .

I double checked the part about `orientation` and `isFavorite` and I agreed with your opinion, but the rest part seems still required. So here's my suggestion.

```dart
AssetEntity({
  required this.id,
  required this.typeInt,
  required this.duration,
  required this.width,
  required this.height,
  this.orientation = 0,
  this.isFavorite = false,
  this.title,
  this.createDtSecond,
  this.modifiedDateSecond,
  this.relativePath,
});
```

Let me know if you have any special cases about the `width`, `height`, and `duration` fields.

**Comment by Letalus** [comment]
Sounds great, for the duration part I think this is only necessary when the AssetEntity is an video. Therefore it wont make much sense to include it as required when it won't be used for a large part of the AssetEntity entries.

For the width and height I don't really have a great special case except that I create within my own apps AssetEntities without any width and height (because they are not needed there). But in general I believe you are right that they should be required.

Thanks for your quick response!
