### ISSUE TITLE
[BUG] Pick a video at very first time. AssetEntity file getter return a file instance but the file size keep changing

### ISSUE THREAD

**Issue by JimmyTai** [CaiJingLong/flutter_photo_manager#452]
AssetEntity file getter return a file but the size keep changing.

**To Reproduce**
1. Take a video by device camera.
2. Get the file from AssetEntity.
3. Get file length in a loop
4. See file length keep changing.

**Expected behavior**
AssetEntity file getter should return a file after any changes.

**Flutter version**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hant-TW)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.2)
[✓] Connected device (1 available)
    ! Error: Chao-Ting’s iPhone is busy: Copying cache files from device. Xcode
      will continue when Chao-Ting’s iPhone is finished. (code -10)

• No issues found!

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro max
 - OS: iOS 14.2.1

**Comment by AlexV525** [comment]
The files may downloading from the iCloud

**Comment by JimmyTai** [comment]
@AlexV525

After test file getter and getMediaUrl()  in AssetEntity, they return different file path.

1. The file path from file getter
` /private/var/mobile/Containers/Data/Application/A106C2D9-2CEC-4638-A091-188C533DE4D2/tmp/.video/IMG_0084.MOV`
2. The file path from getMediaUrl()
`/var/mobile/Media/DCIM/100APPLE/IMG_0084.MOV`

It seems getMediaUrl() return the file located in Gallery, but file getter return the file located in App temporary directory.

**Comment by AlexV525** [comment]
Path is a simulated concept on all platforms, since they don't actually provide a real path that can be access directly.

**Comment by JimmyTai** [comment]
After some research, I found fetchFullSizeVideo in PMManager.m will call it self in the progress handler when progress is 1.0. Then it will trigger ExportSession multiple times. After ExportSession create the local file, fetchFullSizeVideo can found the file in local storage and return the file path. But in the in the meantime, ExportSession haven't done the process. Therefore the file size keep changing.

The other problem. After requestAVAssetForVideo for iCloud file. It will trigger ExportSession immediately. But some times the processing fail. I found some guys are discussing about this in other GitHub repo (https://github.com/banchichen/TZImagePickerController/issues/1073).

Now I use requestExportSessionForVideo instead of  requestAVAssetForVideo to solve this problem.

I will create a PR, please help me to review it.
