### ISSUE TITLE
[BUG] auto request permission on launch on iOS 12.4

### ISSUE THREAD

**Issue by sanekyy** [CaiJingLong/flutter_photo_manager#455]
**Describe the bug**
If I launch app with this package on iOS 12.4, it will ask for permission on app launch.

Reproduced on 12.3 and 12.4. 
iOS 14.+ works correctly.

**Smartphone (please complete the following information):**
 - Device: Any iPhone
 - OS: iOS 12.3-12.4

**Comment by greymag** [comment]
This line 
```
cachingManager = [PHCachingImageManager new];
```
in `PMManager` initiate permissions dialog.
