### ISSUE TITLE
[QUESTION] How to save file to specific Album on iOS

### ISSUE THREAD

**Issue by themadmrj** [CaiJingLong/flutter_photo_manager#464]
I see a method to create an album, but how do I save an image or a video to that album, once I've created it?

**Comment by AlexV525** [comment]
I found that `createAlbum` will return an `AssetPathEntity`, could you try using this entity's path in saving methods?

**Comment by huylethanh** [comment]
I can do it by create album first, getting AssetPathEntity. then save the picture to gallery, getting AssetEntity. we got the AssetPathEntity and AssetEntity, then use copyAssetToPath with 2 parameters above.

**Comment by AlexV525** [comment]
So it seems we have a valid path to save file to a specific album. Closing this.

**Comment by uzumakinaruto123** [comment]
This works but this results in duplicate images in recent and in a custom album.
