### ISSUE TITLE
[BUG] AssetEntity.fromId() times out

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#467]
## Describe the bug
Calling `AssetEntity.fromId(...)` times out for certain files.

It's mostly the first `AssetEntity.fromId(...)` call the app makes that times out, the rest work as expected.

## To Reproduce
1. Fetch and store a list of `AssetEntity` `id`s using `getAssetPathList`.
2. Call `AssetEntity.fromId(id)` for all of these fetched items.
3. The first call will time out in most cases.

## Expected behavior
All calls to `AssetEntity.fromId(id)` should succeed.

--- 
**Flutter version**
2.0.2

**PhotoManager version**
1.0.6

**Smartphone**
 - Device: OnePlus 5
 - OS: Android 10.0.1

**Comment by AlexV525** [comment]
Can you provide a minimal demo to reproduce this issue?

**Comment by vishnukvmd** [comment]
The same was happening for `originFile` too. I was able to work around by adding a timeout to the future and re-fetching it as follows. Second call seems to work flawlessly.
```dart
final asset = await file
    .getAsset()
    .timeout(Duration(seconds: 3))
    .catchError((e) async {
      if (e is TimeoutException) {
        _logger.info("Asset fetch timed out for " + file.toString());
        return await file.getAsset();
      } else {
        throw e;
      }
    });
final sourceFile = await asset.originFile
    .timeout(Duration(seconds: 3))
    .catchError((e) async {
      if (e is TimeoutException) {
        _logger.info("Origin file fetch timed out for " + file.toString());
        return await asset.originFile;
      } else {
        throw e;
      }
    });
```

**Comment by AlexV525** [comment]
To be clear, is this issue happen with all entities or just some specific entities?

**Comment by vishnukvmd** [comment]
It's reproducible for a specific entity. Not sure if it's happening for more.

Printing this specific entity shows `AssetEntity{ id:34320 , type: AssetType.image}`. I can't imagine this being very helpful. If there's any other information I can provide, please let me know.

**Comment by AlexV525** [comment]
Could you re-insert this entity to your phone? Like move the origin file around or somethibg else. Before that, it'll be  better if you can share the origin file so we can take a look.

**Comment by vishnukvmd** [comment]
Here's the original file:

![344deb17-6364-4a9e-b9fd-804f8ffa329e_chat_1539408058037](https://user-images.githubusercontent.com/1161789/118164255-83f96b80-b440-11eb-94b8-ae89c0ac4361.jpeg)

**Comment by AlexV525** [comment]
There it goes, didn't reproduced on my device...

![image](https://user-images.githubusercontent.com/15884415/118227450-235b4480-b4bb-11eb-9269-6c1a9086c758.png)

**Comment by vishnukvmd** [comment]
I’ll close the issue since it cannot be reproduced on other devices, and I’m unable to provide useful debugging information. Also, with the retrial workaround, things aren’t broken.

Thanks again for the help!
