### ISSUE TITLE
[BUG]Unstable image path

### ISSUE THREAD

**Issue by Thomson-Tsui** [CaiJingLong/flutter_photo_manager#47]
## Expect
Hi，jinglong
I used this plugin in our product.
we need to save all images path into sqlite when user select album in album-list, but the images path seem to be changed after a few days.

there is my code：
groupValue：index of album-list;
```dart
final List<AssetPathEntity> lists;
var pathList = <AssetPathEntity>[];

pathList.addAll(widget.lists);
var album = await pathList[groupValue].assetList;
    List allImages = [];
    for (var item in album) {
      var file = await item.file;
      allImages.add(file.path);
    }
```
I saved allImages into sqlite.

**Comment by CaiJingLong** [comment]
Normally, Android's path won't change.
But iOS is the reason why virtual sandbox runs. `AssetEntity` is an abstract concept. Files are generated when you call `assetEntity.file`. 

So the way you use SQLite to save image paths may not always work.

**Comment by CaiJingLong** [comment]
In Android, asset exists as a file.
In iOS, it exists in the form of [PHAsset](https://developer.apple.com/documentation/photokit/phasset?language=objc).

The only identifier I currently use in iOS is [localIdentifier](https://developer.apple.com/documentation/photokit/phobject/1622400-localidentifier?language=objc) and in android is `File.path`.

https://github.com/CaiJingLong/flutter_photo_manager/blob/4ff3cfd9a34f9a4b3e5302a91d1385cc7f25a789/lib/photo_manager.dart#L335-L338

---
So, if you have to identify the unique identifier of the picture, you can consider using `AssetEntity.id` as the unique identifier.
When I update the next version, I will add a method to get the dart layer `AssetEntity` by `id`.

**Comment by CaiJingLong** [comment]
Might be related to #48
