### ISSUE TITLE
[FEATURE] Allow to use the plugin without WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by bauerj** [CaiJingLong/flutter_photo_manager#470]
**Is your feature request related to a problem? Please describe.**
READ_EXTERNAL_STORAGE is obviously needed to show the photos but WRITE_EXTERNAL_STORAGE seems to be unnecessary for a lot of cases. To decrease chances of accidentally changing files it would be better to use as few permissions as possible. Currently, this is not possible because of how `PhotoManager.requestPermission` works.

The permission can be easily stripped from the manifest by adding an entry like `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE " tools:node="remove"/>` to my app's manifest. However, since `PhotoManager.requestPermission` always requires WRITE permission it fails.

**Describe the solution you'd like**
It would be nice if you could add a method like `PhotoManager.requestReadOnlyPermission` which does the same as `PhotoManager.requestPermission` but only requests `READ_EXTERNAL_STORAGE`.

**Describe alternatives you've considered**
I could implement such a method in my app by copying your code but it seems like a more general approach would benefit other projects as well.

**Additional context**

**Comment by AlexV525** [comment]
Discussed offline with @CaiJingLong , these permissions are in group as storage permission group in Android. So it won't be separate at present.

**Comment by amag2511** [comment]
Hi all, do we need to somehow deal with this requestLegacyExternalStorage for Android?
As I understand, some security policy changes and Google play require removing this field from the Android manifest for android 11. And switch to the Scoped Storage.

> Starting May 5th, you must let us know why your app requires broad storage access

> We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.
> 
> Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:
> 
> Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
> Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
> Remove the All files access permission from your app entirely
> For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.
> 
> Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

**Comment by AlexV525** [comment]
Closing since it's a won't fix issue.
