### ISSUE TITLE
[Albums] How can I avoid creating duplicate albums on iOS?

### ISSUE THREAD

**Issue by ghensto** [CaiJingLong/flutter_photo_manager#471]
Is it possible to have `PhotoManager.editor.iOS.createAlbumIfDoesNotExist`?

**Comment by jaysignorello** [comment]
@ghensto iOS allows you to have multiple albums with the same name. So whenever you create an album, you'll need to keep track  of them, referencing them by ID, not name. This way you can write your own function of createAlbumIfDoesNotExist

**Comment by AlexV525** [comment]
Closing since it's not maintained by the package.
