### ISSUE TITLE
[Custom] OOM after migrating from 0.5.8 to 1.1.1.

### ISSUE THREAD

**Issue by nero-angela** [CaiJingLong/flutter_photo_manager#474]
First of all, thank you for making a good package.

I am making an album app based on page view with photo_manager package.
In the 0.5.8 version it worked fine and smooth without any problems. However, when I migrated the same code to 1.1.1, OOM occurs.

I am wondering how can I achieve the same experience as 0.5.8 even in 1.1.1 version.

The test was conducted on an iOS8 real device.

cf) OOM occurs from version 0.6.0 or higher. I am curious about the difference between 0.5.8 and 0.6.0.

**Comment by CaiJingLong** [comment]
Can you provide demo to help me reproduce it?

**Comment by nero-angela** [comment]
Here is a [demo repo](https://github.com/nero-angela/photo_manager_migration/blob/master/README.md).

In photo_manager version 0.5.8, the memory usage does not exceed 300MB.
![0.5.8](https://user-images.githubusercontent.com/26322627/116773846-30c40800-aa93-11eb-89df-c1c74e6eb325.png)

But version 0.6.0, the memory usage is close to 700MB and sometimes OOM occurs.
![0.6.0](https://user-images.githubusercontent.com/26322627/116773848-33266200-aa93-11eb-9ab6-c6369f0fdefc.png)

|0.5.8|0.6.0|
|:-:|:-:|
|slow|fast|
|<video src="https://user-images.githubusercontent.com/26322627/116774009-57cf0980-aa94-11eb-922b-077edc22d814.MP4"/>|<video src="https://user-images.githubusercontent.com/26322627/116774005-4dad0b00-aa94-11eb-866c-f74c1dbc6eb2.MP4" />|

test device : iPhone 8

**Comment by AlexV525** [comment]
Could you verify that if the thumbnail is failed to fetched by the specific size? We do fixed a thumbnail's size issue recently on iOS.

**Comment by nero-angela** [comment]
I measured the length of image bytes in 4 cases for v0.5.8 and v0.6.0 like below.
```
final bytes = (snapshot.data as Uint8List);
print('$index : ${bytes.length}');
```

## Summary
|case|thumbnail size|result|
|:-:|:-:|:-:|
|1|originBytes|same|
|2|device size|v0.6.0 8 times larger than v0.5.8|
|3|device size * 0.5|v0.5.8 2 times large than v0.6.0|
|4|fixed width and height to 100| same|

## Test Result

### Case 01 : 0.5.8 == 0.6.0
```
future: widget.assets[index].originBytes,
```

| photo index |  0.5.8  |  0.6.0 |
|:-:|:-:|:-:|
| 0 | 5,085,384 | 5,085,384
| 1 | 5,141,460 | 5,141,460
| 2 | 7,406,810 | 7,406,810
| 3 | 4,726,963 | 4,726,963
| 4 | 5,347,523 | 5,347,523
| 5 | 3,211,514 | 3,211,514


### Case 02 : 0.5.8 << 0.6.0
```
future: widget.assets[index].thumbDataWithSize(
  MediaQuery.of(context).size.width.toInt(),
  MediaQuery.of(context).size.height.toInt(),
),
```

| photo index |  0.5.8  |  0.6.0 |
|:-:|:-:|:-:|
| 0 | 544,504 | 4,294,863 |
| 1 | 435,995 | 3,773,907 |
| 2 | 572,488 | 4,859,818 |
| 3 | 451,752 | 3,821,755 |
| 4 | 450,165 | 3,743,863 |
| 5 | 218,683 | 1,864,988 |


### Case 03 : 0.5.8 > 0.6.0
```
future: widget.assets[index].thumbDataWithSize(
  (MediaQuery.of(context).size.width * 0.5).toInt(),
  (MediaQuery.of(context).size.height * 0.5).toInt(),
),
```
| photo index |  0.5.8  |  0.6.0 |
|:-:|:-:|:-:|
| 0 | 159,706 | 84,139 |
| 1 | 115,299 | 44,024 |
| 2 | 164,175 | 77,870 |
| 3 | 129,287 | 68,137 |
| 4 | 129,839 | 67,006 |
| 5 | 63,635  | 37,240 |


### Case 04 : 0.5.8 == 0.6.0
```
future: widget.assets[index].thumbDataWithSize(
  100,
  100,
),
```
| photo index |  0.5.8  |  0.6.0 |
|:-:|:-:|:-:|
| 0 | 30,681 | 30,681
| 1 | 23,662 | 23,662
| 2 | 29,065 | 29,065
| 3 | 24,843 | 24,843
| 4 | 27,789 | 27,789
| 5 | 12,838 | 12,838

**Comment by AlexV525** [comment]
I've diff the difference between 0.5.8 and 0.6.0 and the iOS part seems not largely changed overall. Can you try with the `thumbDataWithOption` method to see if it's the format or the quality issue? (ref: https://github.com/CaiJingLong/flutter_photo_manager/blob/master/lib/src/entity.dart#L334)

Sorry that we're currently in the Labor Day holiday and don't have any macOS devices nearby.

**Comment by nero-angela** [comment]
In my opinion, there seems to be a difference in the `fetchThumb` function of `PHManager.m`, but I don't know objective C well, so it seems difficult to determine the exact cause.

- [v0.5.8 PHManager.m](https://github.com/CaiJingLong/flutter_photo_manager/blob/0.5.8/ios/Classes/core/PMManager.m#L307-L342)
- [v1.1.4 PHManager.m](https://github.com/CaiJingLong/flutter_photo_manager/blob/master/ios/Classes/core/PMManager.m#L336-L385)

**Comment by AlexV525** [comment]
I compare the difference between 0.5.8, 0.6.0 and 1.1.5. The result is slightly different, though it seems to be solved.

|                             | 0.5.8    | 0.6.0    | 1.1.5   |
|-----------------------------|----------|----------|---------|
| originBytes                 | 2808983  | 2808983  | 2808983 |   |
| thumbData (150x150)         | 189191   | 189191   | 40085   |
| thumbDataWithSize(400, 400) | 13727237 | 13727237 | 246580  |
