### ISSUE TITLE
this pacakge not working well in android version11.

### ISSUE THREAD

**Issue by soroutarchana** [CaiJingLong/flutter_photo_manager#483]
it's shows all the photos from gallery into the app(we are using pagination to shows all the image into the app)  but when we scroll down or do anything else then it's hang the whole app and after a while response comes so it's not a good thing  (
NOTE:- this behaviour is only for android version 11 otherwise it's fine in android version 6,7,8,9,10 
)

**Comment by CaiJingLong** [comment]
Any demo code?

**Comment by soroutarchana** [comment]
import 'dart:convert';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:image_size_getter/image_size_getter.dart';
import 'package:image_size_getter/file_input.dart';
import 'package:flutter/cupertino.dart' as ui;
import 'package:flutter/material.dart';
import 'package:swift_tiles/base/bloc/gallery_image_authentication.dart';
import 'package:swift_tiles/base/model/AddImageModel.dart';
import 'package:swift_tiles/base/model/GalleryModel.dart';
import 'package:swift_tiles/base/model/PriceTilesModel.dart';
import 'package:swift_tiles/common/common_widget.dart';
import 'package:swift_tiles/models/EditImageModel.dart';
import 'package:swift_tiles/screen/dialogg/SimpleAccountMenu.dart';
import 'package:swift_tiles/screen/edit/customise_photo.dart';
import 'package:swift_tiles/utilizer/color_page.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:swift_tiles/extensions/util_extensions.dart';
import 'package:swift_tiles/utilizer/util.dart';
import 'package:photo_manager/photo_manager.dart';

class GalleryPhotoSelectPage extends StatefulWidget {
  bool permitted;
  PriceTilesModel priceTilesModel;

  GalleryPhotoSelectPage(this.permitted, this.priceTilesModel);

  @override
  _GalleryPhotoSelectPageState createState() => _GalleryPhotoSelectPageState();
}

class _GalleryPhotoSelectPageState extends State<GalleryPhotoSelectPage>
    with TickerProviderStateMixin {
  BlocGalleryAuthentication blocGalleryAuthentication =
  new BlocGalleryAuthentication();
  TabController _tabController;
  List<AssetEntity> assets = [];
  List<String> fileListForContains = [];
  List<String> listFileDataForNextPage = [];
  List<String> fileData = [];
   int currentPage = 0;
   int lastPage;
   bool checkPhotoLength = true;
   List<Widget> _mediaList = [];

  _handleScrollEvent(ScrollNotification scroll) {
    debugPrint(
        "scroll.metrics.pixels::::::" + scroll.metrics.pixels.toString());
    debugPrint("scroll.metrics.maxScrollExtent::::::" +
        scroll.metrics.maxScrollExtent.toString());
    if (scroll.metrics.pixels / scroll.metrics.maxScrollExtent > 0.33) {
      if (currentPage != lastPage) {
        _fetchNewMedia();
      }
    }
  }

  _fetchNewMedia() async {
    debugPrint("lastPage::" +
        lastPage.toString() +
        "currentPage::::" +
        currentPage.toString());
    lastPage = currentPage;
    var result = await PhotoManager.requestPermission();
    if (result) {
      List<AssetPathEntity> albums =
      await PhotoManager.getAssetPathList(onlyAll: true);
      print(albums);
      List<AssetEntity> media =
      await albums.first.getAssetListPaged(currentPage, 100);
      print(media);
      List<Widget> temp = [];
      for (var asset in media) {
        if (asset.type != AssetType.video)
          temp.add(Container(
              child: FutureBuilder(
                future: Future.wait([
                  asset.file,
                  asset.thumbDataWithSize(100, 100),
                ]),
                builder: (_, fileThumbnailSnapShot) {
                if (fileThumbnailSnapShot.data == null || fileThumbnailSnapShot.data[1] == null)
                    return ui.Container(
                      width: 150,
                      height: 150,
                      child: ui.Center(
                        child:showProgressBar()
                      ),
                    );
                  else
                    return Stack(
                      children: [
                        Container(
                          width: 150,
                          height: 150,
                          child: Card(
                              color: Colors.black12,
                               child: !fileThumbnailSnapShot.hasData
                                  ? Center(child:showProgressBar()  )
                                  : ui.Image.memory(fileThumbnailSnapShot.data[1], fit: BoxFit.cover)),
                        ),
                        StreamBuilder<List<String>>(
                            stream: blocGalleryAuthentication.listFileDataForNextPageBloc.stream,
                            builder: (context, selectedDataListSnapshot) {

                              return getImageSize(fileThumbnailSnapShot.data[0].path)?InkWell(
                                onTap: () async {
      if (listFileDataForNextPage.length == 24 && !listFileDataForNextPage.contains(fileThumbnailSnapShot.data[0].path))
                                      "You can select only 24 photos".toastCenter(color: Colors.white);
                                    else if (listFileDataForNextPage.contains(fileThumbnailSnapShot.data[0].path)) {
                          Directory tempDir = await getTemporaryDirectory();
                          String tempPath = tempDir.path;
                          String fileName = fileThumbnailSnapShot.data[0].path.split('/').last;
                          debugPrint("tempPath:::"+tempPath);
                          debugPrint("filnameee:::"+fileName);

                                      listFileDataForNextPage.remove(fileThumbnailSnapShot.data[0].path);
                                      if(fileData.contains(tempPath+"/"+fileName))
                                        {
                                          debugPrint("it is in tempath"+fileName);
                                          fileData.remove(tempPath+"/"+fileName);
                                        }
                                      else if(fileData.contains(fileThumbnailSnapShot.data[0].path))
                                        {
                                          debugPrint("it is in filepath"+fileName);
                                          fileData.remove(fileThumbnailSnapShot.data[0].path);
                                        }

                                      blocGalleryAuthentication.listFileDataForNextPageBloc.sink.add(listFileDataForNextPage);
                                    }
                                    else {
                                      listFileDataForNextPage.add(fileThumbnailSnapShot.data[0].path);
                                      fileData.add(fileThumbnailSnapShot.data[0].path);
                                      blocGalleryAuthentication.listFileDataForNextPageBloc.sink.add(listFileDataForNextPage);
                                    }
                                    blocGalleryAuthentication.stream.listen(print);
setState(() {});
                                },
                                child: ui.Center(
                                  child: ui.Container(
                                      child: setImage(
                                          image: selectedDataListSnapshot.hasData != null &&
                                              selectedDataListSnapshot.data != null &&
                                              selectedDataListSnapshot.data.contains(fileThumbnailSnapShot.data[0].path)
                                              ? "images/selected_image.png"
                                              : "images/circle_view.png",
                                          height: 25, width: 25),)
                                ),
                              ):
                              ui.Center(child: InkWell(
                              onTap: (){
                              getImageSize(fileThumbnailSnapShot.data[0].path);
                              "Low resolution.Print quality will be lower cannot be used".toastCenter(color: Colors.white);
                              },
                                child: setImage(
                                    image: "images/error.png",
                                    height: 25, width: 25),
                              ));
                            }),
                      ],
                    );
                },
              )));
      }
      setState(() {
        _mediaList.addAll(temp);
        currentPage++;
      });
    } else {
      // fail
      /// if result is fail, you can call `PhotoManager.openSetting();`  to open android/ios applicaton's setting to get permission
    }
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    _tabController = new TabController(initialIndex: 0, vsync: this, length: 3);
    _tabController.addListener(_handleTabSelection);
    //_fetchAssets();
    if (widget.permitted) _fetchNewMedia();
  }

  void _handleTabSelection() {
    //setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: appBar(
          title: listFileDataForNextPage != null && listFileDataForNextPage.length>0 ? "Select Photos(" + listFileDataForNextPage.length.toString() +
              ")" : "Select Photos",
         // title: "Select Photos",
          leftImage: "images/back.png",
          color: Color(0xff322CE7),
          leftFunction: () {
            Navigator.pop(context);
          },
           leftPadding: 15.paddingAll()),
      body: NotificationListener<UserScrollNotification>(
        onNotification: (UserScrollNotification scroll) {
           _handleScrollEvent(scroll);
          return;
        },
        child: StreamBuilder<List<String>>(
            stream:
            blocGalleryAuthentication.listFileDataForNextPageBloc.stream,
            builder: (context, snapShotFileList) {
              return Stack(
                key: RIKeys.riKey1,
                children: [
                  CustomScrollView(
                    physics: NeverScrollableScrollPhysics(),
                    slivers: <Widget>[
                      SliverToBoxAdapter(
                        child: 20.verticalSpace(),
                      ),
                      SliverToBoxAdapter(
                        child: Container(
                          child: SizedBox(
                            height: 50,
                            child: TabBar(
                              physics: NeverScrollableScrollPhysics(),
                              controller: _tabController,
                               unselectedLabelColor: Colors.white,
                              indicatorColor: ui.Color(0xff322CE7),
                              tabs: [
                                text(
                                  snapShotFileList.data != null ? "All Photos(" + snapShotFileList.data.length.toString() +
                                      ")" : "All Photos",
                                  _tabController.index == 0 ? Color(0xff191919) : ui.Color(0xffC4C4C4),
                                ),
                                text(
                                  "Facebook",
                                  _tabController.index == 1 ? Color(0xff191919) : ui.Color(0xffC4C4C4),
                                ),
                                text(
                                  "Instagram",
                                  _tabController.index == 2 ? Color(0xff191919) : ui.Color(0xffC4C4C4),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      SliverToBoxAdapter(
                        child: Column(
                          children: [
                            Container(
                              margin: EdgeInsets.only(top: 10,),
                              // margin: 10.marginHorizontal(),
                              height: screenHeight(context),
                              child: TabBarView(
                                physics: NeverScrollableScrollPhysics(),
                                controller: _tabController,
                                children: [
                                  assets.isEmpty == null
                                      ? Center(
                                      child: Container(
                                        child: CircularProgressIndicator(),
                                      ))
                                      : widget.permitted
                                      ? gridView()
                                      : allowPermission(),
                                  facebook(),
                                  photooo(),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  widget.permitted != null && widget.permitted &&
                      _tabController.index == 0 || _tabController.index == 1 || _tabController.index == 2
                      ? Align(
                      alignment: Alignment.bottomCenter,
                      child: ui.Container(
                          margin: EdgeInsets.only(bottom: 90),
                          child: border()))
                      : Container(child: Text(_tabController.index.toString()),),
                  widget.permitted != null &&
                      widget.permitted &&
                      _tabController.index == 0 || _tabController.index == 1 || _tabController.index == 2
                      ? snapShotFileList.data != null && snapShotFileList.data.length >= 3
                      ? Container()
                      : Align(
                    alignment: Alignment.bottomCenter,
                    child: Container(
                        color: Colors.white,
                        height: 30,
                        margin: EdgeInsets.only(bottom: 90),
                        child: errorField()),
                  )
                      : Container(),
                  widget.permitted != null &&
                      widget.permitted &&
                      _tabController.index == 0 || _tabController.index == 1 || _tabController.index == 2
                      ? Align(
                    alignment: Alignment.bottomCenter,
                    child: ui.Container(
                      color: Colors.white,
                      child: InkWell(
                          onTap: () async {
                            if ( snapShotFileList.data!=null&&listFileDataForNextPage.length >= 3) {
   debugPrint("listFileDataForNextPage when we pop" + snapShotFileList.data.length.toString());
   //List<GalleryModel> galleryModelList=
                              var data = await navigate(
                                context, isAwait: true,
                                screen: CustomisePhoto(fileData, widget.priceTilesModel,listFileDataForNextPage),);
                              if (data) {
                                debugPrint("check datat when we pop fileData::"+fileData.length.toString());
                                debugPrint("check datat when we pop"+listFileDataForNextPage.length.toString());
                                debugPrint("11check datat when we pop"+snapShotFileList.data.length.toString());
                               blocGalleryAuthentication..listFileDataForNextPageBloc.sink.
                               add(listFileDataForNextPage);
                                //_fetchNewMedia();
                              }
                            }
                          },
                          child: button(context,
                              text: "Next",
                              height: 55,
                              color:
                              snapShotFileList.data != null && snapShotFileList.data.length >= 3
                                  ? Color(0xff322CE7)
                                  : Colors.grey,
                              margin: 20.marginLeftRightTopBottom(
                                  top: 20, bottom: 20))),
                    ),
                  )
                      : Container(),
                ],
              );
            }),
      ),
    );
  }

  Widget border() {
    return Container(
      height: 1,
      width: screenWidth(context),
      color: borderColor,
    );
  }

  Widget errorField() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        setImage(
            image: "images/error.png",
            height: 15,
            width: 15,
            margin: 10.marginRight()),
        customText(
          //alignmentGeometry: Alignment.center,
          textAlign: TextAlign.start,
          text: "Choose atleast 3",
          style: fonts(
              fontSize: 12, fontFamily: "Helvetica Neue", color: ui.Color(0xff322CE7)),
          //  margin: EdgeInsets.only(top: 8),
        ),
      ],
    );
  }

  Widget allowPermission() {
    return Column(
      children: [
        130.verticalSpace(),
        customText(
          alignmentGeometry: Alignment.center,
          textAlign: TextAlign.center,
          text: "To select photos from gallery you need to give permission",
          style: fonts(
              fontSize: 16, fontFamily: "Helvetica Neue", color: Colors.grey),
          margin: EdgeInsets.only(top: 8, left: 20, right: 20),
        ),
        Center(
          child: RaisedButton(
            color: Color(0xff322CE7),
            onPressed: () async {
              final permitted = await PhotoManager.requestPermission();
              debugPrint("check permissn" + widget.permitted.toString());

              if (permitted) {
                _fetchNewMedia();
                setState(() {
                  widget.permitted = permitted;
                });
              } else {
                debugPrint("check permissn" + widget.permitted.toString());
                setState(() {
                  widget.permitted = false;
                });
              }
            },
            child: Text(
              'Allow permission',
              style: ui.TextStyle(color: Colors.white),
            ),
          ),
        ),
        Container(
          height: 10,
        )
      ],
    );
  }

  Widget text(String text, ui.Color color) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        customText(
          alignmentGeometry: Alignment.center,
          textAlign: TextAlign.start,
          text: text,
          style:
          fonts(fontSize: 16, fontFamily: "Helvetica Neue", color: color),
          //  margin: EdgeInsets.only(top: 8),
        ),
        Container(
          height: 10,
        )
      ],
    );
  }

  Widget photooo() {
    return Container(
        margin: EdgeInsets.only(
          bottom: 280,
          top: 5,
        ),
        child: GridView.count(
            childAspectRatio: 1,
            mainAxisSpacing: 0,
            crossAxisSpacing: 0,
            crossAxisCount: 3,
            children: List.generate(20, (index) {
              return ui.Container(
                margin: 3.marginAll(),
                width: 150,
                height: 150,
                color: Colors.grey,
              );
            })));
  }



  Widget gridView() {
    return ui.Container(
      margin: 0.marginLeftRightTopBottom(top: 0, bottom: 300),
      child: GridView.builder(
          itemCount: _mediaList.length,
          gridDelegate:
          SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3),
          itemBuilder: (BuildContext context, int index) {
            return _mediaList[index];
          }),
    );
  }

  Widget facebook() {
    return Column(mainAxisAlignment: MainAxisAlignment.start,
        //crossAxisAlignment:CrossAxisAlignment.center ,
        children: [
          50.verticalSpace(),
          setImage(
              image: "images/facebook_icon.png",
              padding: 20.paddingAll(),
              height: 80,
              width: 80),
          setImage(
              image: "images/connect_facebook.png",
              padding: 20.paddingAll(),
              fill: BoxFit.fill,
              height: 100,
              width: 300),
        ]);
  }

  bool getImageSize(String path) {
    final file = File(path);
    Size size = ImageSizeGetter.getSize(FileInput(file));
    print(size);
    if (size.width > 100 && size.height > 100) {
      return true;
    } else {
      return false;
    }
  }

 Widget resolutionErrorField() {
    return SimpleAccountMenu(
      child:ui.Container(
          child: setImage(
              image: "images/error.png",

              height: 25,
              width: 25)),

      backgroundColor: Colors.black,
      widgets: [
        setImage(
        image: "images/resolution_pic.png",
 ),
      /*  ui.Center(
          child: customText(
            alignmentGeometry: Alignment.center,
            textAlign: TextAlign.start,
            text: "Low resolution.Print quality will be lower cannot be used",
            style:  TextStyle(decoration: TextDecoration.none,color: Colors.white,fontFamily: "Helvetica Neue",fontSize: 16),
            //fonts(fontSize: 16, fontFamily: "Helvetica Neue", color: Colors.white),
            padding: 20.paddingAll(),
           //  margin: EdgeInsets.only(top: 8,left: 10,right: 10),
          ),
        ),*/
       //  5.verticalSpace(),
       ],
      iconColor: Colors.white,
      onChange: (index) {
        // provider.updateSelection(index: index);
      },
    );
  }

}



class RIKeys {
static final riKey1 = const Key('__RIKEY1__');
static final riKey2 = const Key('__RIKEY2__');
static final riKey3 = const Key('__RIKEY3__');
}

//This is the code that i am using

**Comment by AlexV525** [comment]
Provide the value of targetSdkVersion, compileSdkVersion, and the AndroidManifest.xml . Use \``` to wrap your code.

**Comment by soroutarchana** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.swift_tiles">
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.INTERNET"/>

   <application
        android:label="swift_tiles"
        android:requestLegacyExternalStorage="true"
        android:largeHeap="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
       <activity
           android:name="com.yalantis.ucrop.UCropActivity"
           android:screenOrientation="portrait"
           android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />


       <meta-data android:name="com.facebook.sdk.ApplicationId"
           android:value="@string/facebook_app_id"/>

       <activity android:name="com.facebook.FacebookActivity"
           android:configChanges=
               "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
           android:label="@string/app_name" />
       <activity
           android:name="com.facebook.CustomTabActivity"
           android:exported="true">
           <intent-filter>
               <action android:name="android.intent.action.VIEW" />
               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />
               <data android:scheme="@string/fb_login_protocol_scheme" />
           </intent-filter>
       </activity>



   </application>
</manifest>

**Comment by soroutarchana** [comment]
compileSdkVersion 30
    minSdkVersion 19
    targetSdkVersion 30

**Comment by AlexV525** [comment]
Then provide a smallest reproducible demo, rather than a file in your project.

**Comment by nayanbabariya95** [comment]
@AlexV525 I get same problem with this plugin. please

**Comment by AlexV525** [comment]
@nayanbabariya95 Please provider a minimized reproducible demo.

**Comment by nayanbabariya95** [comment]
```
final _assetPathEntities = await PhotoManager.getAssetPathList(type: RequestType.common);
final assetEntities = await _assetPathEntities[_selectedAssetPathIndex]
        .getAssetListPaged(_pageIndex, 200);
```

This code taking 2 to 3 sec to get folder list and after that when i scrolling gridview the UI is freezing

**Comment by nayanbabariya95** [comment]
@AlexV525 Is my given code valid?

**Comment by AlexV525** [comment]
> @AlexV525 Is my given code valid?

Not really. Please try the picker demo in profile/release mode to see if it's reproducible.

**Comment by nayanbabariya95** [comment]
@AlexV525 I have tried that demo with release mode but showing loading indicator when app is fetching all assets path list
i have tried common picker (Photos + Videos). i have 2200 items in Recent.

**Comment by AlexV525** [comment]
Any recordings to indicate your description? I'm not sure about the "showing loading indicator" that you mentioned. Is a loading indicator abnormal?

**Comment by nayanbabariya95** [comment]
https://drive.google.com/file/d/1H13xnDWNiaBmAcGaQhQAMO6R55E3OBVG/view?usp=sharing
You can see my video here

**Comment by AlexV525** [comment]
So from your video I didn't see UI freezing but a little bit of lagging when loading thumbnail previews. Not sure its relationship with "smoothly like instagram" or "the UI is freezing".

**Comment by nayanbabariya95** [comment]
You can see loading indicator when click on "Multi Picker" for second and then Grid View is displaying. this things not happen with instagram

**Comment by AlexV525** [comment]
Sorry but could you provide a recording video with instagram?

**Comment by nayanbabariya95** [comment]
https://drive.google.com/file/d/1H62WmwNXB8kw4sPX8GAHvdGxOuJ4JbgF/view?usp=sharing
Here is video for Instagram flow

**Comment by AlexV525** [comment]
👍 Thanks for these solid proofs. We'll figure out if we can speed up the first load based on the instagram behavior.

**Comment by nayanbabariya95** [comment]
@AlexV525 I think Instagram is using separate native controls for image selection part. What you say?

**Comment by AlexV525** [comment]
From the video I can only tell things below:
* We might have a performance issue when loading the `AssetPathEntity`, or list of `AssetEntity`, even if we use a small amount.
* Instagram only seems to load entities with the amount of first page can be filled. From this point, you can pass a smaller value to the picker and try again.
* Thumbnails preview is pretty fast, this is something related to the MediaStore mechanism. Needs more investigation.

**Comment by nayanbabariya95** [comment]
I have also one case in which this plugin is fails
 - Media file changes are not detecting by this plugin
Example steps:
 - Open Grid View screen with Camera folder
 - Take app in background and open system camera and take photo
 - Again open Wechat Assets Picker Example app and you can not see that captured image in your Grid

Conclusion:
- This plugin not receiving changes of any media made by external apps

**Comment by AlexV525** [comment]
Please file issues to the picker if you have problem when using it. Thanks.
