### ISSUE TITLE
[BUG] IOS openSettings

### ISSUE THREAD

**Issue by wwwhttpru** [CaiJingLong/flutter_photo_manager#486]
Opening Settings does not work on IOS
I found this commented out code
If you uncomment it, then it works fine.
![Снимок экрана 2021-04-28 в 14 49 54](https://user-images.githubusercontent.com/56841516/116384291-2571a200-a831-11eb-9bce-3d91082b0e29.png)

**Comment by jaysignorello** [comment]
Seeing the same problem. 

@wwwhttpru As a workaround, I used [permission_handler](https://pub.dev/packages/permission_handler), which includes `openAppSettings()` function to open app settings.
