### ISSUE TITLE
[BUG] IOS delete cache file : no such file or directory

### ISSUE THREAD

**Issue by Tom3652** [CaiJingLong/flutter_photo_manager#487]
**Describe the bug**
Delete the IOS retrieved file (with await assetEntity.file) fail : no such file or Directory.

**To Reproduce**
1. Retrieve the file this way : File currentFile = await assetEntity.file;
2. Check if Platform.isIOS as requested in the README to delete the above cached file created after usage.
3. Call : currentFile?.deleteSync(); 

**Expected behavior**
The cached file should be deleted because it exists. 

**Flutter version**
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale fr-FR)
    • Flutter version 2.0.5 at /Users/foxtom/Desktop/flutter
    • Framework revision adc687823a (13 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008020-001204401E78002E • ios            • iOS 14.4.2
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

**Smartphone (please complete the following information):**
 - Device: Iphone XS Max
 - OS: IOS 14.2

**Log**
My logging output below : 

```
flutter: File: '/private/var/mobile/Containers/Data/Application/6428FE42-7577-4BCE-AC5B-FB255903F267/tmp/.video/1618682250_IMG_1429.MOV'
flutter: 134
flutter: Ratio : 1.7777777777777777
flutter: 238.2222222222222
flutter: It's a video !
flutter: Is IOS true !
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/private/var/mobile/Containers/Data/Application/6428FE42-7577-4BCE-AC5B-FB255903F267/tmp/.video/1618682250_IMG_1429.MOV' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
```

Is the file already destroyed now ? And the README not updated ? In this case it's fine, I just have to remove to deleteSync() method, but I prefer be sure about it :)

**Comment by Tom3652** [comment]
I am adding this error because I think it's linked according to this [post](https://stackoverflow.com/questions/45863507/error-nslocalizeddescription-cannot-save) : 

```
Export session failed: Error Domain=AVFoundationErrorDomain Code=-11823 "Cannot Save" UserInfo={NSLocalizedRecoverySuggestion=Try saving again., NSLocalizedDescription=Cannot Save, NSUnderlyingError=0x282557960 {Error Domain=NSOSStatusErrorDomain Code=-12101 "(null)"}}
```

It happens sometimes when I call ```File currentFile = await assetEntity.file```, not all the time and I think it's because I am not able to clear the cache, the files could not be overwritten or something.

Thanks in advance

**Comment by veritasware** [comment]
I use a code like this.
```
if(await currentFile.exists()) {
    await currentFile.delete();
}
```

**Comment by Tom3652** [comment]
Indeed you are right it's a good and necessary check.

However, it doesn't explain the issue and especially the second part. 

When i try to open files (especially videos) from the assetEntity, it gives a null output sometimes because of this error and i am not able to fix it myself unfortunately, it's IOS specific code in the package i guess (according to the answer on StackOverFlow)
