### ISSUE TITLE
[Feature] Remove logs or add parameter for log level

### ISSUE THREAD

**Issue by yanivshaked** [CaiJingLong/flutter_photo_manager#494]
When using the plugin on iOS, there are many NSLog prints:

![image](https://user-images.githubusercontent.com/13107481/117950192-9cbc3100-b31b-11eb-9acd-a7fce1fa122c.png)

Can those be remove or use some parameter to determine the log level for printings?

**Comment by yasinarik** [comment]
Hi. I have seen the merge and so updated it to the latest version, `1.2.0`. How to disable those logs? Couldn't understand.

Thanks a lot! @CaiJingLong
