### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1232209** [CaiJingLong/flutter_photo_manager#498]
**Describe the bug**
App Crashed when run AssetEntity.file or AssetEntity.loadFile

**To Reproduce**
1. 获取相册内的图片，然后获取到图片的AssetEntity
2. 然后通过AssetEntity获取file
 File file = await assetEntity.loadFile(isOrigin: false).catchError((error){
          print(error);
        });
3. App crashed

**Expected behavior**
如果全都能够获取到图片名称，类似于image_1234.HEIC，这种就不会崩溃
但是如果获取titleAsync返回的值是一长串id的，就无法获取到file,如果选择的图片较多app就会崩溃

**Screenshots**

**Flutter version**

**Smartphone (please complete the following information):**

**Log**

If applicable, add logs to help explain your problem.

get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
get title start
* thread #101, queue = 'com.apple.root.user-initiated-qos', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x00000001a5bebf84 vImage`vConvert_420Yp8_CbCr8ToARGB8888_vec + 724
vImage`vConvert_420Yp8_CbCr8ToARGB8888_vec:
->  0x1a5bebf84 <+724>: stp    q22, q19, [x22, #0x20]
    0x1a5bebf88 <+728>: zip2.16b v18, v18, v25
    0x1a5bebf8c <+732>: zip1.16b v19, v20, v23
    0x1a5bebf90 <+736>: zip2.16b v20, v20, v23
Target 0: (Runner) stopped.

**Comment by AlexV525** [comment]
pm version? id example?

**Comment by 1232209** [comment]
I just upgraded to this version, and then I saw printing. Maybe I got too many files at one time, which led to exceeding the memory limit

**Comment by 1232209** [comment]
I seem to have solved this problem, nice
