### ISSUE TITLE
AssetEntity property for file length in bytes

### ISSUE THREAD

**Issue by mastak-ua** [CaiJingLong/flutter_photo_manager#500]
**The problem**
It would be nice to know file ( image / video ) length in bytes without reading full file content ( originBytes ). So later content could be ordered by size, or size can be displayed somewhere as extra information.

**The solution**
Add length property to AssetEntity which tells what is the file length in bytes.

**Comment by 1232209** [comment]
I want this feature too

**Comment by CaiJingLong** [comment]
Unfortunately, this library can only provide the information provided by PhotoLibrary(ios/macOS)/MediaStore(android), other information consumes resources.

**Comment by srubob** [comment]
Even if it is from different packages, did anyone figure out how to do it? Search in google did not provide any results without reading the file. Thanks!
