### ISSUE TITLE
can not work on android targetSdkVersion 28、29

### ISSUE THREAD

**Issue by Tonigt** [CaiJingLong/flutter_photo_manager#504]
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
e: /Users/tonight/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.2.0/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerDeleteManager.kt: (116, 36): Unresolved reference: R
e: /Users/tonight/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.2.0/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerDeleteManager.kt: (119, 36): Unresolved reference: createTrashRequest
e: /Users/tonight/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.2.0/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt: (356, 73): Unresolved reference: R
e: /Users/tonight/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.2.0/android/src/main/kotlin/top/kikt/imagescanner/core/utils/Android30DbUtils.kt: (35, 34): Unresolved reference: R
e: /Users/tonight/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.2.0/android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt: (28, 67): Unresolved reference: R

**Comment by AlexV525** [comment]
flutter clean

**Comment by Tonigt** [comment]
public static class VERSION_CODES {
        public static final int BASE = 1;
        public static final int BASE_1_1 = 2;
        public static final int CUPCAKE = 3;
        public static final int CUR_DEVELOPMENT = 10000;
        public static final int DONUT = 4;
        public static final int ECLAIR = 5;
        public static final int ECLAIR_0_1 = 6;
        public static final int ECLAIR_MR1 = 7;
        public static final int FROYO = 8;
        public static final int GINGERBREAD = 9;
        public static final int GINGERBREAD_MR1 = 10;
        public static final int HONEYCOMB = 11;
        public static final int HONEYCOMB_MR1 = 12;
        public static final int HONEYCOMB_MR2 = 13;
        public static final int ICE_CREAM_SANDWICH = 14;
        public static final int ICE_CREAM_SANDWICH_MR1 = 15;
        public static final int JELLY_BEAN = 16;
        public static final int JELLY_BEAN_MR1 = 17;
        public static final int JELLY_BEAN_MR2 = 18;
        public static final int KITKAT = 19;
        public static final int KITKAT_WATCH = 20;
        public static final int LOLLIPOP = 21;
        public static final int LOLLIPOP_MR1 = 22;
        public static final int M = 23;
        public static final int N = 24;
        public static final int N_MR1 = 25;
        public static final int O = 26;
        public static final int O_MR1 = 27;
        public static final int P = 28;
        public static final int Q = 29;

        public VERSION_CODES() {
            throw new RuntimeException("Stub!");
        }
    }

not define R in android build.class

**Comment by Tonigt** [comment]
public static class VERSION_CODES {
        public static final int BASE = 1;
        public static final int BASE_1_1 = 2;
        public static final int CUPCAKE = 3;
        public static final int CUR_DEVELOPMENT = 10000;
        public static final int DONUT = 4;
        public static final int ECLAIR = 5;
        public static final int ECLAIR_0_1 = 6;
        public static final int ECLAIR_MR1 = 7;
        public static final int FROYO = 8;
        public static final int GINGERBREAD = 9;
        public static final int GINGERBREAD_MR1 = 10;
        public static final int HONEYCOMB = 11;
        public static final int HONEYCOMB_MR1 = 12;
        public static final int HONEYCOMB_MR2 = 13;
        public static final int ICE_CREAM_SANDWICH = 14;
        public static final int ICE_CREAM_SANDWICH_MR1 = 15;
        public static final int JELLY_BEAN = 16;
        public static final int JELLY_BEAN_MR1 = 17;
        public static final int JELLY_BEAN_MR2 = 18;
        public static final int KITKAT = 19;
        public static final int KITKAT_WATCH = 20;
        public static final int LOLLIPOP = 21;
        public static final int LOLLIPOP_MR1 = 22;
        public static final int M = 23;
        public static final int N = 24;
        public static final int N_MR1 = 25;
        public static final int O = 26;
        public static final int O_MR1 = 27;
        public static final int P = 28;
        public static final int Q = 29;

        public VERSION_CODES() {
            throw new RuntimeException("Stub!");
        }
    }

not define R in android build.class
