### ISSUE TITLE
[BUG] Video doesn't play the first time when is selected.

### ISSUE THREAD

**Issue by ajosecueto** [CaiJingLong/flutter_photo_manager#505]
I pick a video from my gallery, I first list all my assets entity available in my phone but when I download a video and hen save this video the first time that I select de entity and pass to VideoPlayer the video can be initialized and have another size that the file really have... then few seconds I can select the same AssetEntity and the video works...

**To Reproduce**
1. Download a file
2. Save it
3. List the assets
4. Pass asset entity to video player first time and no work

Flutter
V. 2.0.6

 - Device: iPhone11
 - OS: IOS 14

**Comment by jaysignorello** [comment]
@ajosecueto have some sample code you can share?

**Comment by nayanbabariya95** [comment]
Same issue +1
Here i am providing code
Using photo_manager: ^1.2.4 with null-safety and latest flutter version

#

```
/// Get all folder list
final assetPathEntities = await PhotoManager.getAssetPathList(type: RequestType.video);

/// To get all entities in perticular folder
final assetEntities = await assetPathEntities[0].getAssetListPaged(_pageIndex, 30);
```

Select any video file by assetEntities.file this will give Future<File>

After that load video in VideoPlayer using `video_player: ^2.1.6`

This will not load video first time but on second time video will play
This is happening in iOS device. Android is working fine

**Comment by juanmartin-8a** [comment]
As stated in the docs and also used in the photo_manager's example to play a video you can use 
```
String mediaUrl = await entity.getMediaUrl();
```
and then with video_player
```
VideoPlayerController videoController = VideoPlayerController.network(  // NETWORK not .file
    mediaUrl
);
```

**Comment by AlexV525** [comment]
Please use the `AssetEntity.getMediaUrl` method to load a video.
