### ISSUE TITLE
[BUG] cannot save videos

### ISSUE THREAD

**Issue by marcoberetta96** [CaiJingLong/flutter_photo_manager#508]
**Describe the bug**
Cannot save videos.

**To Reproduce**
```
File videoFile = File(myPath);
AssetEntity? videoEntity = await PhotoManager.editor.saveVideo(videoFile);
print(videoEntity);
print(videoEntity?.size);
```

**Flutter version**
Flutter version 2.2.0

**Smartphone (please complete the following information):**
Android 11, physical devide

**Log**
```
I/FilePickerUtils(17156): Caching from URI: content://com.android.providers.media.documents/document/video%3A51134
D/FilePickerUtils(17156): File loaded and cached at:/data/user/0/com.marco.app/cache/file_picker/VID-20210512-WA0004.mp4
D/FilePickerDelegate(17156): File path:[com.mr.flutter.plugin.filepicker.FileInfo@d89f1e6]
I/flutter (17156): null
I/flutter (17156): null
```

**Further note**
Everything is working fine when saving images.

**Comment by rignaneseleo** [comment]
I've got the same bug on Android 11.

**Comment by CaiJingLong** [comment]
Related #388

**Comment by liuyi999111** [comment]
@CaiJingLong 在 PhotoManagerPlugin 中的这行代码引起的错误
       `val title = call.argument<String>("title")!!`
在 1.2.5 版本中只要设置 title 就可以正常保存视频了
      `PhotoManager.editor.saveVideo(File(file.path), title: file.name);`

**Comment by AlexV525** [comment]
Duplicate with #327 .
