### ISSUE TITLE
[Feature] Ability to save image with a specific date

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#516]
`PhotoManager.editor.saveImageWithPath(...)` does not seem to honor the `lastModified` property of the file.

**Describe the solution you'd like**
I'd like to save an edited file, whose creation-time is in the past. For example, if a user edits a photo that was clicked a week ago, and saves it, it should be saved next to the original photo. Currently it gets added as the newest photo in the gallery.

Either `saveImage` could expose the `creationTime` as an attribute, or it could honor the `lastModified` property of the file.

**Describe alternatives you've considered**
I tried writing to a file and calling `setLastModifiedSync` to a timestamp in the past. But the saved image is getting created with the current timestamp.

**Comment by vishnukvmd** [comment]
@AlexV525 So I tried injecting timestamp into the plugin just to see if it would get saved correctly, but it did not: https://github.com/CaiJingLong/flutter_photo_manager/pull/517/files

Let me know if there's something else I could do.

PS: This is not critical, I just thought it would be nice to have.

**Comment by AlexV525** [comment]
> For example, if a user edits a photo that was clicked a week ago, and saves it, it should be saved next to the original photo. Currently it gets added as the newest photo in the gallery.

IDK if it's a correct behavior, but AFAIK the modified image is saved as the latest. Can you make a screen record to indicate it?

**Comment by vishnukvmd** [comment]
So when a user edits a photo that was taken a few weeks ago, it is likely that he/she wants to see the edited photo next to the original.

I'm okay with the default behavior of saving the file with the current timestamp. But it would be nice if there was an option to save it with the timestamp of the original image, so that they exist next to each other in the gallery.

**Comment by vishnukvmd** [comment]
Closing this since I was able to workaround this by maintaining the original `creationTime` locally, and this use case might be specific to me.
