### ISSUE TITLE
How to use changeCallbacks in android

### ISSUE THREAD

**Issue by lkysh3** [CaiJingLong/flutter_photo_manager#519]
## Expect
Hi. Thanks for making this package.

 I do take picture, and save image at my folder.
Then, in iOS, receive changeCallback.
But, in Android, don't receive changeCallback.

I don't know that's why.

I used compileSdkVersion is 30, targetSdkVersion is 30, minSdkVersion is 16.

Is the usage wrong?
Any help would be appreciated.

Thank you for your advice.

## ScreenShots
Screenshots showing the purpose.

add Callback code
![image](https://user-images.githubusercontent.com/57136604/120890253-5917c700-c63c-11eb-89b1-0929589b24cf.png)

save image code
![image](https://user-images.githubusercontent.com/57136604/120890264-6fbe1e00-c63c-11eb-98cd-3f9844294069.png)

callback method(just print)
![image](https://user-images.githubusercontent.com/57136604/120890270-79478600-c63c-11eb-9122-ee4f2de2589d.png)

**Comment by CaiJingLong** [comment]
The original observer has some problems.
Now I fixed it, but need to wait for the release of the next version.

**Comment by lkysh3** [comment]
> The original observer has some problems.
> Now I fixed it, but need to wait for the release of the next version.

Thanks for the feedback.
I look forward to the next version.
