### ISSUE TITLE
[BUG] Sort (asc, desc) options not fully working : Media mixed

### ISSUE THREAD

**Issue by Nico3652** [CaiJingLong/flutter_photo_manager#520]
I cloned this GitHub project and run it on iPhone and Samsung.
My gallery folder on both devices is completely mixed with the sort options. 

Compare to native gallery folder the sort is not working and mixed all media.

 How can this be fixed ?

**Comment by AlexV525** [comment]
Any explanation about the "mixed all media"? Screenshots, videos?

**Comment by Nico3652** [comment]
I solved my problem.

I assume the ordering by default is OrderOptionType.updateDate, then my gallery was completely mixed between media date. 

I modified it by OrderOptionType.createDate and asc to false.
