### ISSUE TITLE
[Custom] Can this access Shared Albums on iOS ?

### ISSUE THREAD

**Issue by de1mat** [CaiJingLong/flutter_photo_manager#521]
## Expect
When I retrieve a list of albums on an iOS device I would like to include the users Shared Albums and to be able to view the assets within it.

**Comment by AlexV525** [comment]
Should be fixed by #601 .

**Comment by AlexV525** [comment]
> @AlexV525 I tested the most recent build to see if I can access Shared Albums and it's not working. It certainly has fixed the missing Smart albums, but not Shared Albums.

According to #601 , you can now find albums that shared from your Mac. Isn't that true?

**Comment by jaysignorello** [comment]
@AlexV525 I haven't seen any issues in my testing. Out of caution, instead of removing it, I opened a PR that expands that check to include inherited objects of `PHAssetCollection`, which still works for pulling the shared albums on iOS.
