### ISSUE TITLE
[BUG] presentLimited's future does not resolve on iOS

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#527]
**Describe the bug**
Calling `await PhotoManager.presentLimited()` blocks the thread. There is no result returned, and the execution stops there.

**To Reproduce**
Execute `await PhotoManager.presentLimited();` on an iOS device.

**Expected behavior**
According to documentation for [presentLimitedLibraryPickerFromViewController](https://developer.apple.com/documentation/photokit/phphotolibrary/3752108-presentlimitedlibrarypickerfromv), this function should be returning a list of asset IDs. Even if that is not the case, the function should return once the user has dismissed the picker.

**Smartphone (please complete the following information):**
 - Device: iPhone11 Pro
 - OS: iOS 14.4.2

**Comment by fenngzui** [comment]
是啊，这个方法执行完了没结果，而且阻塞到这里，不知道刷新相册的时机

**Comment by AlexV525** [comment]
As I tested, `presentLimited` will only takes effect when the app has granted with the limited access.

![image](https://user-images.githubusercontent.com/15884415/123209058-a75d0f00-d4f2-11eb-8b36-7b8e26973d57.png)

**Comment by vishnukvmd** [comment]
@AlexV525 Yes, the selection dialog pops up correctly. But the future is never resolved so we don't get to know when the user has finished selecting.

**Comment by vishnukvmd** [comment]
@AlexV525 Thanks for this. But `presentLimited` is now resolving immediately, instead of waiting until the user has dismissed the dialog. I've created a new issue to discuss this: https://github.com/CaiJingLong/flutter_photo_manager/issues/544.
