### ISSUE TITLE
[BUG] EXIF information is missing in iOS

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#528]
**Describe the bug**

`AssetEntity.originFile` contains no EXIF information on iOS (HEIF images). This works as expected on Android.

**To Reproduce**
1. Click a photo on an iPhone.
2. Save/share the file returned by `AssetEntity.originFile` for the clicked photo.
3. Parse the EXIF for this file using services like http://metapicz.com or http://exif-viewer.com.
4. Verify that there is no EXIF information present.

**Expected behavior**
EXIF information should be present.

**Flutter version**
```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.1 at /Users/vishnu/work/tools/flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
```

**flutter_photo_manager version**: `master`

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.6

**Comment by vishnukvmd** [comment]
@AlexV525 please let me know if there's any additional information that I can provide.

**Comment by AlexV525** [comment]
Sure...we're quite busy at present, sorry for the delay.

**Comment by AlexV525** [comment]
If I remember correctly, the file of the asset will be copied once you called `file` or `originFile`, if the EXIF info is lost, it must been dropped with these processes.

**Comment by vishnukvmd** [comment]
Hey @AlexV525 , sorry for this, the mistake was at our end.

We were transcoding the HEIC file to JPG for rendering, and we were losing the EXIF information there. And I was testing with this transcoded file instead of the original.

`originFile` is working just as expected, sorry for the noise! 😢
