### ISSUE TITLE
How to use changeCallbacks in android

### ISSUE THREAD

**Issue by lkysh3** [CaiJingLong/flutter_photo_manager#530]
Hi. Thanks for making this package.

I do take picture, and save ![image](https://user-images.githubusercontent.com/57136604/122759192-a353a600-d2d4-11eb-90b5-7ff19021c1ab.png) at my folder.
Then, in iOS, receive changeCallback.
But, in Android, don't receive changeCallback.

I don't know that's why.

I used compileSdkVersion is 30, targetSdkVersion is 30, minSdkVersion is 16.

Is the usage wrong?
Any help would be appreciated.

Thank you for your advice.

## ScreenShots
![image](https://user-images.githubusercontent.com/57136604/122759153-95058a00-d2d4-11eb-92e2-2d778ce8ef53.png)

save image code
![image](https://user-images.githubusercontent.com/57136604/122759192-a353a600-d2d4-11eb-90b5-7ff19021c1ab.png)

callback method(just print)
![image](https://user-images.githubusercontent.com/57136604/122759238-b0709500-d2d4-11eb-9101-972e90bc94a3.png)

**Comment by juanmartin8a** [comment]
I have the same problem :/
