### ISSUE TITLE
`LateInitializationError` when create `AssetEntityPath`

### ISSUE THREAD

**Issue by mahbubmunna** [CaiJingLong/flutter_photo_manager#531]
**Describe the bug**
Creating a AssetEntityPath from id through an error saying lateInitializationError: Field '_type@73180071' has not been initialized.
I want use to the same album in iOS and for that I am saving the id for the further use, but once I'm trying to construct the asset entity path, facing this issue

**To Reproduce**
AssetPathEntity.fromId(myPreviousSavedID);

**iOS Version and Device Info**
iOS version: 14.5
iphone 11 pro Simulator

**Log**

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_type@73180071' has not been initialized.
#0      AssetPathEntity._type (package:photo_manager/src/entity.dart)
#1      AssetPathEntity.type (package:photo_manager/src/entity.dart:52:27)
#2      AssetPathEntity.typeInt (package:photo_manager/src/entity.dart:62:22)
#3      PhotoManager.fetchPathProperties (package:photo_manager/src/manager.dart:237:14)
#4      AssetPathEntity.refreshPathProperties (package:photo_manager/src/entity.dart:89:39)
#5      AssetPathEntity.fromId (package:photo_manager/src/entity.dart:14:18)
#6      _HomePageState.createAlbum (package:auto_wallpaper/screens/home_page.dart:519:48)
<asynchronous suspension>
```

**Comment by AlexV525** [comment]
Please provide a readable log stacktrace with the `_LateInitializationError`, thanks.

**Comment by mahbubmunna** [comment]
> Please provide a readable log stacktrace with the `_LateInitializationError`, thanks.

I have updated issue with full stacktrace

**Comment by AlexV525** [comment]
👍  Thanks, will take a look later.

**Comment by mahbubmunna** [comment]
> 👍 Thanks, will take a look later.

Did you get time to look into, it will be super helpful if you come up with a answer, Thanks

**Comment by AlexV525** [comment]
Can you add a breakpoint at src/entity.dart#L93 to inspect the `result` field ?

**Comment by mahbubmunna** [comment]
Sure, Let me try

**Comment by mahbubmunna** [comment]
I have inspected, before calling src/entity.dart#L93, the call to the function fetchPathProperties in src/entity.dart#L235 is happening, and the result is null
see the attached
![github](https://user-images.githubusercontent.com/30203070/123207540-5bed3580-d4df-11eb-803b-ec3c6ed4f862.png)

**Comment by AlexV525** [comment]
Can you provide more info about the iOS version you're using? Edit at the information you've provided.

**Comment by mahbubmunna** [comment]
> Can you provide more info about the iOS version you're using? Edit at the information you've provided.

I have updated in edit the ios version

**Comment by mahbubmunna** [comment]
I have also found the issue by myself, the issue was the Request type was null, we were used it without initializing it

**Comment by AlexV525** [comment]
Actually not only `RequestType` is null, other properties are not initialized during the refresh process. It needs some more tweaks to make it work perfectly, but with the PR it should worked with the minimum requirement.

**Comment by mahbubmunna** [comment]
Yes, I have passed the RequestType with only image option and it worked in my end, I have also seen your PR request, you also passed the album type as album
