### ISSUE TITLE
[BUG] Execution failed for task ':photo_manager:compileDebugKotlin'.

### ISSUE THREAD

**Issue by bhanuka96** [CaiJingLong/flutter_photo_manager#538]
I upgrade plugin from `1.2.2` to `1.2.3`. Then I got this error.

```
* What went wrong:
Execution failed for task ':photo_manager:compileDebugKotlin'.
> Compilation error. See log for more details
```

my kotlin version

```
buildscript {
    ext.kotlin_version = '1.3.72'
```

**Comment by bhanuka96** [comment]
**Temporary solution**

downgrade plugin to `1.2.2`

**Comment by AlexV525** [comment]
Where's log?

**Comment by xuechen628** [comment]
e: /Users/chen/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-1.2.4/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerDeleteManager.kt: (116, 36): Unresolved reference: R
e: /Users/chen/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-1.2.4/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerDeleteManager.kt: (119, 36): Unresolved reference: createTrashRequest
e: /Users/chen/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-1.2.4/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt: (357, 75): Unresolved reference: R
e: /Users/chen/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-1.2.4/android/src/main/kotlin/top/kikt/imagescanner/core/utils/Android30DbUtils.kt: (35, 34): Unresolved reference: R
e: /Users/chen/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-1.2.4/android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt: (28, 67): Unresolved reference: R

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':photo_manager:compileDebugKotlin'.

**Comment by AlexV525** [comment]
Run `flutter clean` everytime you've upgraded the plugin will solve this problem.

**Comment by xuechen628** [comment]
unfortunately, flutter clean doesn't help, it's always the same exception.
Steps:
1. set version to 1.2.4
2. run "flutter clean"
3. run "flutter clean" again (it is not necessary, but, yes....)
4. run "flutter pub get"
5. same exception
6. downgrade to 1.2.2
7. run "flutter clean"
8. run "flutter pub get"
9. same exception

kotlin version: 1.4.21
compileSdkVersion/targetSdkVersion: 29
minSdkVersion: 21

**Comment by AlexV525** [comment]
Is the example reproducible with this issue?

**Comment by AlexV525** [comment]
If anyone is still suffering from this
* raise your `ext.kotlin_version` in the `android/build.gradle` to `1.4.x`.
* add this line`apply plugin: 'kotlin-android'` to your `android/app/build.gradle`, and the file should be look like:

```groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
```

**Comment by bhanuka96** [comment]
> Run `flutter clean` everytime you've upgraded the plugin will solve this problem.

@AlexV525 don't close the issues. this is not a solution.

**Comment by AlexV525** [comment]
See the pinned issue #561 .

**Comment by ClarkChu07** [comment]
solution：

> 
> flutter clean
> flutter clean
> flutter pub cache clean
> flutter pub get

**Comment by ClarkChu07** [comment]
solution：
> flutter clean
> flutter clean
> flutter pub cache clean
> flutter pub get
