### ISSUE TITLE
[BUG] iOS 14, iPhone 6S has crashed when loads AssetEntity.

### ISSUE THREAD

**Issue by nerdrun** [CaiJingLong/flutter_photo_manager#541]
I've encountered an app crashed recently.
I have three iPhone test devices, iPhone 6 plus, 6s, and SE2 which running on iOS13 and iOS14.

The gallery component that I made with this nice plugin is working so well on iPhone 6 plus and SE2, but not 6S.
When I tried to load AssetEntity the app has been crashed with this error below:

```
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
Can't end BackgroundTask: no background task exists with identifier 87 (0x57), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
```

I tried to figure that out and also followed your codes but it doesn't relate with imageFormatGroup.

Could you get some information about the error?

**Comment by AlexV525** [comment]
Please get more log by running from Xcode. AFAIK `imageFormatGroup` is a property from the `camera` plugin.

**Comment by nerdrun** [comment]
Thanks for replying for that.
I assume that the error wasn't occured by your plugin.
Thank you again.

**Comment by a272312970** [comment]
> Thanks for replying for that. I assume that the error wasn't occured by your plugin. Thank you again.

How did you solve this issue? i had the same issue
