### ISSUE TITLE
[BUG] presentLimited's future does not resolve correctly on iOS

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#544]
**Describe the bug**
Calling `await PhotoManager.presentLimited()` returns immediately. There is no way to know when the user has finished selecting photos.

**To Reproduce**
Execute `await PhotoManager.presentLimited();` on an iOS device, it will resolve immediately before you close the selecter.

**Expected behavior**
According to documentation for [presentLimitedLibraryPickerFromViewController](https://developer.apple.com/documentation/photokit/phphotolibrary/3752108-presentlimitedlibrarypickerfromv), this function should be returning a list of asset IDs. Even if that is not the case, the function should return only once the user has dismissed the picker.

**Smartphone (please complete the following information):**
 - Device: iPhone11 Pro
 - OS: iOS 14.4.2

**Comment by vishnukvmd** [comment]
After looking at the code, I discovered that I can work around this limitation by attaching a callback to `PhotoManager.addChangeCallback`, and listening to updates on that callback.

But I will leave this issue open since the API feels buggy, and will let the owners decide whether this needs attention.

**Comment by AlexV525** [comment]
This method only supports iOS 15.0 actually.
![image](https://user-images.githubusercontent.com/15884415/124129430-5d56c900-dab0-11eb-902b-58b25bf9581d.png)

**Comment by vishnukvmd** [comment]
Thanks for checking @AlexV525. Closing this issue.

**Comment by nhan-nguyen-se** [comment]
> After looking at the code, I discovered that I can work around this limitation by attaching a callback to `PhotoManager.addChangeCallback`, and listening to updates on that callback.
> 
> But I will leave this issue open since the API feels buggy, and will let the owners decide whether this needs attention.

I tried this workaround and found that it does not work if user close the dialog without changing anything. The callback is not called. Did you face the same issue?

**Comment by AlexV525** [comment]
Change callback, as its named, only called when changed. BTW thanks for the GitHub notify, we can implement the new presentLimited API for iOS 15 now.

**Comment by nhan-nguyen-se** [comment]
@AlexV525 Thanks for your clarification. I wonder there is a way to detect if the dialog closed in this case in iOS 14?

**Comment by AlexV525** [comment]
> @AlexV525 Thanks for your clarification. I wonder there is a way to detect if the dialog closed in this case in iOS 14?

You can hook the lifecycle method, I think it should work pretty well in this case.

**Comment by nhan-nguyen-se** [comment]
@AlexV525 I tried lifecycle hook as well and found that the `AppLifecyleState` does not change in this case. I guess because the presentLimited modal is opened by the app itself so iOS does not force the app to be inactive when that modal is opened. 

Anyway, I have changed the behavior of my app so that it does not need to wait for the modal close anymore. Instead it only updates the view when there is a change from selected media.

It would be great if we can support iOS 15 callback. Thank you for all the hard works :)
