### ISSUE TITLE
save failed: MissingPluginException(No implementation found for method saveImage on channel top.kikt/photo_manager)[BUG]

### ISSUE THREAD

**Issue by luokunman** [CaiJingLong/flutter_photo_manager#547]
`I/flutter (29601): save failed: MissingPluginException(No implementation found for method saveImage on channel top.kikt/photo_manager)
I/flutter (29601):  #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156`

when i call `PhotoManager.editor.saveImage` method.

**Comment by vishnukvmd** [comment]
Please do a `flutter clean` and reinstall the app. If the issue persists, please share additional information about the OS, the device, your flutter and library version.

**Comment by luokunman** [comment]
> 请执行`flutter clean`并重新安装该应用程序。如果问题仍然存在，请分享相关信息、设备、您的浏览器和库版本的其他。

ok. thanks.
