### ISSUE TITLE
[macos] I could not get it to work.

### ISSUE THREAD

**Issue by iostriz** [CaiJingLong/flutter_photo_manager#548]
## Expect
I expect to be able to run get permissions, or PhotoManager.getAssetPathList() on mac, but I get a lot of compile time errors.

<img width="915" alt="Screen Shot 2021-07-02 at 16 22 25" src="https://user-images.githubusercontent.com/2076153/124288624-b1fe5080-db51-11eb-87ae-e18c01ad24e6.png">
It seems like it requires Catalist.

Can you please provide a minimal sample for macos? Or update docs to reflect the state of package?

**Comment by AlexV525** [comment]
Sorry for didn't fully test on macOS, this is introduced by #539, we'll address a fix ASAP.

**Comment by CaiJingLong** [comment]
Later, I will add a CI of macOS to avoid this PR being merged.
