### ISSUE TITLE
PhotoManager.requestPermission() only work 2 times.[BUG]

### ISSUE THREAD

**Issue by BSiddharth** [CaiJingLong/flutter_photo_manager#550]
**Describe the bug**
As it is clear from the title PhotoManager.requestPermission() only asks for permission two times, after that it does not respond

**To Reproduce**
Make a button like this 

                          
                             TextButton(
                              style: TextButton.styleFrom(
                                backgroundColor: Colors.redAccent,
                                padding: EdgeInsets.symmetric(
                                    vertical: 15, horizontal: 15),
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(10.0),
                                    side: BorderSide(color: Colors.black)),
                              ),
                              onPressed: () async {
                                permitted =
                                    await PhotoManager.requestPermission();

                              },
                              child: Text(
                                "ALLOW STORAGE PERMISSION",
                                style: TextStyle(
                                    color: Colors.white,
                                    fontWeight: FontWeight.normal,
                                    letterSpacing: 1.0,
                                    fontSize: 15),
                              ))

After denying permisson for 2 times in a row it will stop requesting further.

**Comment by vishnukvmd** [comment]
It is possible that the device's operating system is returning the result that user selected the first two times.

You could use `requestPermissionExtend`, log the result, and if permission was rejected, prompt the user to grant access from the settings (that can be opened with `openSettings`.

**Comment by BSiddharth** [comment]
@vishnukvmd  Yes it is possible that os automatically reject apps from spamming requests. I will try `PhotoManager.requestPermissionExtend()`
