### ISSUE TITLE
[BUG] Multiple calls to requestPermissionExtended on Android will return PermissionState.authorized even if storage permissions aren't granted

### ISSUE THREAD

**Issue by mhstoller** [CaiJingLong/flutter_photo_manager#551]
**Describe the bug**
When calling PhotoManager.requestPermissionExtended() or requestPermission() on Android, they are returning PermissionState.authorized and true, while the prompt for storage access is open, or even when storage access has been explicitly denied.

Using permission_handler to work around this for now, as it correctly reports the status.

**To Reproduce**
Run on an Android device and await a call to requestPermissionExtended. The storage prompt will open, but before the user selects their choice requestPermissionExtended / requestPermission has resolved already as authorized.

```
print(await PhotoManager.requestPermissionExtend());
print(await Permission.storage.status);

```

Output:
```
W/Activity(24903): Can request only one set of permissions at a time        //is this related to the issue?
I/flutter (24903): PermissionState.authorized
I/flutter (24903): PermissionStatus.denied

```

**Expected behavior**
Permissions should be handled correctly and only return when a choice is made. If storage access was declined, the requestPermission methods should return the correct output.

**Flutter version**
```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/max/development/flutter
    • Framework revision d79295af24 (4 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
```

**Smartphone (please complete the following information):**
OnePlus 6

**Comment by mhstoller** [comment]
This is on v1.2.5

**Comment by AlexV525** [comment]
It didn't reproduced with the example.

```
I/flutter ( 5380): result --- state: PermissionState.denied
```

![image](https://user-images.githubusercontent.com/15884415/124689276-cdc77500-df0a-11eb-9b8d-2f9bd5e9824f.png)

**Comment by mhstoller** [comment]
Thank you for pointing that out. The example app also works on my phone and waits for user input to resolve the future.

After digging into my code more closely, there were two separate parts that called for permissions at around the same time (which is why in my output there is a `Can request only one set of permissions at a time` message). For some reason this causes flutter_photo_manager to return the permissions as authorized even though they aren't.

You can simulate this by calling PhotoManager.requestPermissionExtend() twice without awaiting the first one. It will output an authorized state.

```
PhotoManager.requestPermissionExtend();
final _test = await PhotoManager.requestPermissionExtend();
print("state: $_test");
```

That should reproduce the behavior I was seeing. I can clean my own code up so there aren't multiple requests at the same time, but I still believe this is a bug because it shouldn't ever return authorized if it's not, and/or requesting multiple permissions at the same time should throw an exception.

Thank you!

**Comment by AlexV525** [comment]
I don't think calling twice requests without await is a proper behavior.

**Comment by mhstoller** [comment]
In my actual code I used await in both methods but they got executed at the same time. I'm just showing a way to reproduce the same behavior for testing

**Comment by AlexV525** [comment]
If you're indicating that requesting multiple permission requests should be prevented, I think we need a new issue to track that.

**Comment by mhstoller** [comment]
Okay I can open one tomorrow for that specifically. Closing.
