### ISSUE TITLE
[BUG] 视频类型获取到的 高度和宽度是反的

### ISSUE THREAD

**Issue by Oklahomawhore** [CaiJingLong/flutter_photo_manager#552]
**Describe the bug**

AssetEntity 中的width 和height ，视频类型的时候获取的高度和宽度是反的，
竖屏的视频宽度比高度还大。

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot_20210707-145719](https://user-images.githubusercontent.com/13502612/124714184-092a6980-df34-11eb-86be-0e7654631471.jpg)

**Flutter version**

**Smartphone (please complete the following information):**
 - Device: Samsun-GM7810
 - OS: Android 11

**Log**

If applicable, add logs to help explain your problem.

```bash

```

**Comment by AlexV525** [comment]
是否所有视频都是这样的情况？另请提供插件版本、Flutter版本

**Comment by AlexV525** [comment]
未复现。

![image](https://user-images.githubusercontent.com/15884415/126303510-cab55c60-e0ba-4d5e-998f-7ca73f53b602.png)

![image](https://user-images.githubusercontent.com/15884415/126303561-be7d04d7-b484-45a4-99c1-dbf847267124.png)

**Comment by qpalzm963** [comment]
遇到一樣問題
