### ISSUE TITLE
[BUG] Not full loaded albums.

### ISSUE THREAD

**Issue by Tokars** [CaiJingLong/flutter_photo_manager#554]
I have other one gallery app and I see some albums display different photos/videos count.
That method work incorrectly. 
`List<AssetPathEntity> albums = await PhotoManager.getAssetPathList(hasAll: false); `

**Comment by AlexV525** [comment]
Try ignoreSize in the filter options.

**Comment by Tokars** [comment]
> Try ignoreSize in the filter options.

Yes. It's work, thank you.
