### ISSUE TITLE
[BUG] Error while listing out the assets due to another permission request is still ongoing. 

### ISSUE THREAD

**Issue by winsonloh1998** [CaiJingLong/flutter_photo_manager#563]
**Describe the bug**
 I could not get the images/videos even i accepted the permission. Sometimes wrong with the number of permission request.

**To Reproduce**
I will use the example project of wechat_asset_picker as the way to demonstrate how the error occurred. Steps to reproduce the behavior:
1. Click on any of the option provided (i.e. common picker). 
2. Click 'Allow' on the permission prompt
3. See the error from the log.

**Expected behavior**
It should show the media after allowing the permission

**Version**
Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
Dart version 2.13.3
PhotoManager version 1.2.6

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - OS: Android 
 - Version: 10 

**Log**

```bash
E/flutter (23071): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done., null, null)
E/flutter (23071): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
E/flutter (23071): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter (23071): <asynchronous suspension>
E/flutter (23071): #2      Plugin.getAllGalleryList
package:photo_manager/src/plugin.dart:26
E/flutter (23071): <asynchronous suspension>
E/flutter (23071): #3      DefaultAssetPickerProvider.getAssetPathList
package:wechat_assets_picker/…/provider/asset_picker_provider.dart:302
E/flutter (23071): <asynchronous suspension>
E/flutter (23071): #4      new DefaultAssetPickerProvider.<anonymous closure>
package:wechat_assets_picker/…/provider/asset_picker_provider.dart:260
E/flutter (23071): <asynchronous suspension>
E/flutter (23071):

```

**Comment by AlexV525** [comment]
This is fixed by `1.2.6+1`.
