### ISSUE TITLE
[Custom]

### ISSUE THREAD

**Issue by Thomson-Tsui** [CaiJingLong/flutter_photo_manager#57]
Hi, jinglong

请问我能通过File的路径去获取到AssetEntity吗？

thanks,
ThomsonTsui

**Comment by CaiJingLong** [comment]
你之前提问过类似的问题,我在 #47 给过你回答
iOS中的图片不是以文件方式存在的,所以反向获取在iOS做不到,Android中可以做到,但是兼顾到库的兼容性,所以不能提供api

相对应的我给出了解决方案: 使用id作为唯一标识符,[查看Readme#create-assetentity-with-id](https://github.com/CaiJingLong/flutter_photo_manager#create-assetentity-with-id)
