### ISSUE TITLE
Not finding all photos stored in an album

### ISSUE THREAD

**Issue by mjolnir91** [CaiJingLong/flutter_photo_manager#574]
I'm using camera 0.8.1+5 + gallery_saver to take pictures and save them to an album. On android I've tried saving them to "Recent" and "Pictures" and the photos save fine but photo_manager fails to recognize these pictures in the album and doesn't list them as files in the album. However, any pictures taken with android's default camera app work just fine so I'm thinking there is some incompatibility between how camera 0.8.1+5 + gallery_saver takes/saves the files and what photo_manager expects. Thoughts?

**Comment by AlexV525** [comment]
Try ignoreSize in FilterOption?

**Comment by mjolnir91** [comment]
That did the trick. I'm taking photos at "UltraHigh" quality so I guess they were getting caught in the filter. Is there any problems you forsee by me turning off the this filter? 

`  List<AssetPathEntity> albums = await PhotoManager.getAssetPathList(
          filterOption: FilterOptionGroup(
              imageOption: FilterOption(
                  needTitle: false,
                  sizeConstraint: SizeConstraint(ignoreSize: true))));`

**Comment by AlexV525** [comment]
> Is there any problems you forsee by me turning off this filter?

Which means photos taken by `camera` might not included a valid size info which makes our default filter ignored them.
