### ISSUE TITLE
[BUG] java.lang.NullPointerException from PhotoManagerPlugin

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#581]
**Describe the bug**
We're receiving a large number of crash logs on Sentry with the following stack trace that points to [PhotoManagerPlugin.kt](https://github.com/ente-io/flutter_photo_manager/blob/master/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt#L41-L44).

**Information**
 - Devices: Happening across a wide range of Samsung, Mi, Pixel, Moto, OnePlus devices
 - OS: Android 7.0, 8.1.0, 9, 10, 11, 12
 - Flutter Version: 2.2.3
 - photo_manager Version: 1.2.8

**Log**

```bash
PlatformException(error, 获取权限的Activity不存在, null, java.lang.NullPointerException: 获取权限的Activity不存在
	at r.a.b.d.b.g(PermissionsUtils.java:10)
	at r.a.b.d.b.f(PermissionsUtils.java:1)
	at r.a.b.c.d.onMethodCall(PhotoManagerPlugin.kt:44)
	at k.b.c.a.j$a.a(MethodChannel.java:2)
	at io.flutter.embedding.engine.e.b.e(DartMessenger.java:5)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:2)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:181)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
)
```

Since our code is not a part of the stack trace, we're having a hard time understanding the root cause.

Any help would be much appreciated. Thank you!

**Comment by AlexV525** [comment]
Seem like you're calling permission requests or other methods from a background service, without an actual activity exist.

**Comment by vishnukvmd** [comment]
Thanks for the quick response @AlexV525!

I've verified that the only place where we call `PhotoManager.requestPermissionExtend` is from a [UI widget](https://github.com/ente-io/frame/blob/master/lib/ui/grant_permissions_widget.dart#L56).

The only operations we do in the background are:
- `PhotoManager.addChangeCallback()`
- `PhotoManager.startChangeNotify()`
- `PhotoManager.getAssetPathList()`

Also, if the app is in background, we call `PhotoManager.setIgnorePermissionCheck(true)` before calling `PhotoManager.getAssetPathList()`.

Is there anything else I've missed?

**Comment by AlexV525** [comment]
Can we make a minimum example that addresses methods you've mentioned? AFAIK all of these methods are require to have a permission check.

**Comment by vishnukvmd** [comment]
I will work on creating a minimum reproducible example.

Although I'm curious, why should any of the three methods I listed above (`addChangeCallback`, `startChangeNotify`, `getAssetPathList`) have a dependency on the app being in the foreground?

**Comment by AlexV525** [comment]
They don't, what they depended is the permission, and we need an activity to ask for permissions.

**Comment by vishnukvmd** [comment]
I verified that the `addChangeCallback`, `startChangeNotify` and `getAssetPathList` are called only when the permission has already been granted. 

But I suppose `photo_manager` is unaware of this and will prompt for permissions each time.

I will `setIgnorePermissionCheck` to `true` for all calls made from the background and see if that makes a difference.

**Comment by vishnukvmd** [comment]
This fixed the issue, thank you @AlexV525 !

**Comment by AlexV525** [comment]
This should be the issue solved by a valid solution in the most short time ever. 😄
