### ISSUE TITLE
getAssetList on AssetPathEntity gives runtime error "pageSize > 0': The pageSize must better than 0"

### ISSUE THREAD

**Issue by mahbubmunna** [CaiJingLong/flutter_photo_manager#590]
**Describe the bug**
I am trying to get all asset entities from the album of ios. Calling getAssetList, but returning "The page size is saying zero" upon calling on getAssetList on AssetPathEnity Object

**To Reproduce**
Call the getAssetList on an AssetEntityPath like an Album

**Expected behavior**
Should return List of asset Entity for the album 

**Screenshots**
![image](https://user-images.githubusercontent.com/30203070/131864095-796ad208-68d1-447f-a4d8-9ff0693c52ad.png)

**Comment by AlexV525** [comment]
Code?
