### ISSUE TITLE
[Custom] Cannot retrieve images in AndroidQ

### ISSUE THREAD

**Issue by TheDechev** [CaiJingLong/flutter_photo_manager#593]
## Expect
To retrieve the `List<AssetPathEntity>` once permissions were granted in AndroidQ.

## Actual behavior
When invoking the following code in my application on an AndroidQ emulator, it returns an **empty list**:
`final assetsPathList = await PhotoManager.getAssetPathList(type: RequestType.image);`

Notes:

- There are images on the device.
- The following line was added to AndroidManifest.xml:
        **android:requestLegacyExternalStorage="true"**

-  The `compileSdkVersion ` and `targetSdkVersion` attributes in build.gradle were set to 29

Has anyone encountered this before and can suggest a soution?

**Comment by AlexV525** [comment]
Make sure images are shown in the photos app, then reboot once.

**Comment by TheDechev** [comment]
@AlexV525 doesn't help, as you can see from the image below the images are showing in the photos app but still having the same issue:
![image](https://user-images.githubusercontent.com/24282045/132569828-0ad49a2a-b806-4551-a188-500a8545c740.png)

**Comment by AlexV525** [comment]
Is there some reason that you need 29 as your sdk version? If not, can you try 30 or 31? If it is, I'll take further checks for your case.

**Comment by TheDechev** [comment]
@AlexV525 using it as the emulator has an Android 10 installed on it, so I assumed that any SDK higher than 29 wouldn't be necessary.

Anyway, attempted to set the `targetSdkVersion` to 30, same result..

**Comment by TheDechev** [comment]
@AlexV525 The images are downloaded from Google Drive on the device.
Tried adding the `ignoreSize` option without success, tell me if I missed anything by any chance:

```
FilterOption filter = FilterOption(sizeConstraint: SizeConstraint(ignoreSize: true));
FilterOptionGroup optionGroup = FilterOptionGroup(imageOption: filter);
final assetsPathList = await PhotoManager.getAssetPathList(type: RequestType.image, filterOption: optionGroup);
```

**Comment by AlexV525** [comment]
Maybe we should make this flag enabled by default, but we'll need more clues.

Basically your MediaStore has failed to write the correct info of these images, as you may found the width/height field would be 0 if you inspect an entity.
