### ISSUE TITLE
[BUG] Ios can't find "from my mac" folder

### ISSUE THREAD

**Issue by ossgoossgo** [CaiJingLong/flutter_photo_manager#596]
Sync photos between mac and ios, 
In sytem album can saw a folder name "from my mac",
But  use this lib not see this folder,
Is lib supporting this, or how can i resolve it?

environment
Flutter 2.0.3
photo_manager 1.2.5

**Comment by KenLuo** [comment]
If albums are in other folders, getAssetPathList can not get those albums. This method seems only get those albums in gallery folder. Any other folders created by user. This method will not return albums in other folders.

**Comment by AlexV525** [comment]
Fixed by #601 .
