### ISSUE TITLE
[BUG] IOS 12.1.4 Crash problem

### ISSUE THREAD

**Issue by zzpmaster** [CaiJingLong/flutter_photo_manager#60]
**Describe the bug**
打开相册，ios崩溃

导致崩溃代码
```
ImageScanner.m

1. for (PHCollection *collection in self.galleryArray) {
2.     PHFetchResult<PHAssetCollection *> *fetchResult = [PHAssetCollection
3.             fetchAssetCollectionsWithLocalIdentifiers:@[collection.localIdentifier] options:opt];
4.     for (PHAssetCollection *assetCollection in fetchResult) {
5. 
6.         PHFetchResult<PHAsset *> *assetResult = [PHAsset
7.                 fetchAssetsInAssetCollection:assetCollection options:opt];
8.         for (PHAsset *asset in assetResult) {
9.                 _idAssetDict[asset.localIdentifier] = asset;
10.              block(assetCollection, asset);
11.         }
12.     }
13. }

```
assetCollection 有可能是PHCollectionList对象，需要过滤掉, 需要在问题代码**第五行**添加下面代码。
```
if (![assetCollection isKindOfClass:[PHAssetCollection class]]) continue;
```
修改后可以正常运行

**请验证，如果正确期待回复和更新。**

**Flutter version**
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 12.1.4
 - Version 0.3.2

**Log**

`2019-03-10 21:30:30.916729+0800 Runner[12455:3105536] -[PHCollectionList assetCollectionType]: unrecognized selector sent to instance 0x281a99080

2019-03-10 21:30:37.159769+0800 Runner[12455:3105536] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PHCollectionList assetCollectionType]: unrecognized selector sent to instance 0x281a99080'
*** First throw call stack:
(0x205dadea4 0x204f7da50 0x205cc6b14 0x205db37bc 0x205db546c 0x214b94844 0x214b2fc24 0x10099c7d4 0x1009a49c8 0x104b3f824 0x104b40dc8 0x104b48e6c 0x104b49b60 0x104b53bfc 0x2059c90dc 0x2059cbcec)

libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by CaiJingLong** [comment]
I've added the code in branch, but how to reproduce it?

**Comment by zzpmaster** [comment]
Maybe  have a lot of photos on my mobile phone, and in the folder to add subfolders. i think you can try to create new folders in the album.

Reference: 
`https://developer.apple.com/documentation/photokit/phcollectionlist`

**Comment by Harvey4431** [comment]
这个iOS崩溃问题还是存在的啊，bugly提示crash
![image](https://user-images.githubusercontent.com/12400860/59319597-da624a80-8cfd-11e9-931f-cda5720b03d6.png)

系统：iOS 12.3.1 
机型：iPhone 5s

**Comment by Harvey4431** [comment]
第一次访问相册时崩溃，此时弹出alertview提醒你给授权，如果同意，重新run再请求访问相册就不crash，如果选择拒绝，每次访问相册都crash

**Comment by CaiJingLong** [comment]
Reference resources

https://github.com/CaiJingLong/flutter_photo/blob/4945c829569f5253e0d08064737e9a62a3085b18/lib/photo.dart#L127-L139
