### ISSUE TITLE
[BUG] AssertEntity.loadFile failed to load iCloud video when isOrigin is false

### ISSUE THREAD

**Issue by nhan-nguyen-se** [CaiJingLong/flutter_photo_manager#608]
**Describe the bug**
When download iCloud video using `AssertEntity.loadFile` with `isOrigin: false` then the progress handler report failed status and return null file when reaching 100% download progress.

It works well if `isOrigin: true` 

**To Reproduce**
```dart
final assertEntity =....;
final progressHandler = PMProgressHandler();
progressHandler.stream.listen((event) {
  final progress = event.progress;
  print('Download progress: ${event.state}, progress: $progress');
});
return await assertEntity.loadFile(progressHandler: progressHandler, isOrigin: false);
```

**Expected behavior**
Calling `AssertEntity.loadFile` with `isOrigin: false` should work.

**Photo Manager version**
photo_manager: ^1.3.4

<details>
  <summary>flutter doctor</summary>
  
 [✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)

</details>

**Smartphone (please complete the following information):**
 - Device: iPhone 6 Plus (real device)
 - OS: iOS 15

**Comment by AlexV525** [comment]
We don't have videos other than origin, since a video is not able to compress in this plugin.

**Comment by nhan-nguyen-se** [comment]
@AlexV525 Thanks for explanation. This can be closed now.
