### ISSUE TITLE
Could not resolve project :photo_manager

### ISSUE THREAD

**Issue by hello-ring** [CaiJingLong/flutter_photo_manager#61]
你好，引入 photo_manager 后一直编译不通过  
以下是gradle日志，请问如何解决？  `Could not resolve project :photo_manager.`
```

Could not determine the dependencies of task ':app:processDynamicReleaseManifest'.
> Could not resolve all task dependencies for configuration ':app:dynamicReleaseRuntimeClasspath'.
   > Could not resolve project :photo_manager.
     Required by:
         project :app
      > Could not select value from candidates [null, debug, release] using AlternateDisambiguationRule.BuildTypeRule.
         > java.lang.NullPointerException (no error message)
```

dependencies中的版本：
photo_manager: ^0.3.2

**Comment by CaiJingLong** [comment]
Clone repo, run example.
If there is no problem, you need to check the project yourself. This problem should not be related to the library.

**Comment by hello-ring** [comment]
你好，这是个新项目，还没有引入其他包。
现在的情况是只要在 dependencies 中加入 `photo_manager: ^0.3.2` ， 就无法运行，报截图上的错误。
刚学flutter，这个是我开始flutter遇到的第一个错误，不知道是不是我遗漏了什么步骤？
你的example我clone下来运行过了，更新gradle版本后可以正常运行。
![Uploading WX20190312-101300@2x.png…]()

**Comment by CaiJingLong** [comment]
see
https://caijinglong.gitbooks.io/migrate-flutter-to-androidx/content/zhong-wen.html

Try to migrate androidX.

**Comment by hello-ring** [comment]
谢谢，androidX可以
