### ISSUE TITLE
[ABOUT getAssetListRange] Which class of method is this?

### ISSUE THREAD

**Issue by ggdream** [CaiJingLong/flutter_photo_manager#612]
Hello, I am using this library for the first time, but I really can't read the documentation.

For example, what is the `path` of `path.getAssetListPaged(page, perPage)`, and the performance problem refers to `getAssetListPaged` or `getAssetListRange`.

And the example under `example` is too complicated, so you can make another plugin.

So if I want to get the album pictures in segments, what should I do? Can you give a condensed example? 
Thanks

**Comment by ggdream** [comment]
I went to look at the API one by one in the code, and the problem was solved, but I still hope that the document can be modified.

**Comment by AlexV525** [comment]
Link to #584 for further updates.
