### ISSUE TITLE
How to fetch the device gallery even the app is closed

### ISSUE THREAD

**Issue by mimranMD** [CaiJingLong/flutter_photo_manager#617]
## Expect
I'm working on a project in which app check the device gallery and upload the newly received images to firebase. I'm using Photo manager and its working fine in foreground. Now I also need to fetch device gallery in background and upload newly received images to firebase in background but in background, photo manager shows permission request error. How I can resolve it please guide. 

## **### Foreground Outputs**
Here is the foreground output of work manager

I/flutter (12160): [AssetPathEntity{ name: Recent, id:isAll, length = 890 }]
I/flutter (12160): [AssetEntity (id:101197 , type: AssetType.image), AssetEntity (id:101195 , type: AssetType.image), AssetEntity (id:101194 , type: AssetType.imag
e), AssetEntity (id:101193 , type: AssetType.image), AssetEntity (id:101192 , type: AssetType.image), AssetEntity (id:101191 , type: AssetType.image), AssetEntity
(id:101190 , type: AssetType.image), AssetEntity (id:101186 , type: AssetType.image), AssetEntity (id:101185 , type: AssetType.image), AssetEntity (id:101184 , typ
e: AssetType.image), AssetEntity (id:101183 , type: AssetType.image), AssetEntity (id:101182 , type: AssetType.image), AssetEntity (id:101181 , type: AssetType.ima
ge), AssetEntity (id:101180 , type: AssetType.image), AssetEntity (id:101179 , type: AssetType.image), AssetEntity (id:101149 , type: AssetType.video), AssetEntity
 (id:101148 , type: AssetType.image), AssetEntity (id:101147 , type: AssetType.image), AssetEntity (id:101146 , type: AssetType.image), AssetEntity (id:101144 , ty
pe: AssetType.image), AssetEntity (id:101143 , type: AssetType.i
I/flutter (12160): 890

### **Background Output**
And in background it shows this 

E/MethodChannel#top.kikt/photo_manager(12160): Failed to handle method call
E/MethodChannel#top.kikt/photo_manager(12160): java.lang.NullPointerException: Activity for the permission request is not exist.
E/MethodChannel#top.kikt/photo_manager(12160):  at top.kikt.imagescanner.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:116)
E/MethodChannel#top.kikt/photo_manager(12160):  at top.kikt.imagescanner.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:102)
E/MethodChannel#top.kikt/photo_manager(12160):  at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:221)
E/MethodChannel#top.kikt/photo_manager(12160):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#top.kikt/photo_manager(12160):  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#top.kikt/photo_manager(12160):  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:819)
E/MethodChannel#top.kikt/photo_manager(12160):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#top.kikt/photo_manager(12160):  at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#top.kikt/photo_manager(12160):  at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#top.kikt/photo_manager(12160):  at android.app.ActivityThread.main(ActivityThread.java:6944)
E/MethodChannel#top.kikt/photo_manager(12160):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#top.kikt/photo_manager(12160):  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#top.kikt/photo_manager(12160):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/BackgroundWorker(12160): errorCode: error, errorMessage: Activity for the permission request is not exist.

**Comment by AlexV525** [comment]
We've discussed this in some other places. The most complete context about this should be at https://github.com/CaiJingLong/flutter_photo_manager/issues/287#issuecomment-702390920 .

The main reason you ran into this issue is we uses dynamic permission check during most of method calls, and permission checks require an `Activity`, which is quite impossible to have one in a background process.

To achieve this, you need these calls:
* Make sure you granted with permissions before schedule any background tasks.
* Use `PhotoManager.setIgnorePermissionCheck` to ignore dynamic permission checks before you call any background tasks and every time you're going to execute tasks.

Closing this as we do have a workaround, and you can still leave comments if you want to know more about this issue.
