### ISSUE TITLE
AndroidX incompatibilities in this Flutter app

### ISSUE THREAD

**Issue by JerryNingZhen** [CaiJingLong/flutter_photo_manager#63]
## Expect
What you want to achieve

## ScreenShots
![image](https://user-images.githubusercontent.com/17874806/54527340-98529280-49b4-11e9-929d-14af8a663ae6.png)
![image](https://user-images.githubusercontent.com/17874806/54527357-a56f8180-49b4-11e9-9b1b-14cbc6965ab2.png)

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo_manager#about-androidx
