### ISSUE TITLE
[BUG]Android高版本权限没有适配

### ISSUE THREAD

**Issue by a371166028** [CaiJingLong/flutter_photo_manager#66]
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=4207, uid=10086 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
E/AndroidRuntime( 4207): 	at android.os.Parcel.readException(Parcel.java:1942)
E/AndroidRuntime( 4207): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
E/AndroidRuntime( 4207): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime( 4207): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
E/AndroidRuntime( 4207): 	at android.content.ContentResolver.query(ContentResolver.java:754)
E/AndroidRuntime( 4207): 	at android.content.ContentResolver.query(ContentResolver.java:704)
E/AndroidRuntime( 4207): 	at android.content.ContentResolver.query(ContentResolver.java:662)
E/AndroidRuntime( 4207): 	at android.provider.MediaStore$Images$Media.query(MediaStore.java:868)
E/AndroidRuntime( 4207): 	at top.kikt.imagescanner.ImageScanner.scanImage(ImageScanner.kt:114)
E/AndroidRuntime( 4207): 	at top.kikt.imagescanner.ImageScanner.access$scanImage(ImageScanner.kt:16)
E/AndroidRuntime( 4207): 	at top.kikt.imagescanner.ImageScanner$getImagePathIdList$1.run(ImageScanner.kt:550)
E/AndroidRuntime( 4207): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime( 4207): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime( 4207): 	at java.lang.Thread.run(Thread.java:764)
E/EGL_emulation( 4207): tid 4252: swapBuffers(550): error 0x300d (EGL_BAD_SURFACE)

**Comment by CaiJingLong** [comment]
So what's your targetVersion?

**Comment by CaiJingLong** [comment]
Support android Q in 0.4.1.
