### ISSUE TITLE
[Custom] How can I get a list of album names

### ISSUE THREAD

**Issue by Shtibel** [CaiJingLong/flutter_photo_manager#70]
## Expect
I want to create a TabBar() with all the images.
And each tab will be a device album
And in each album to show all its images.
The first tab will have all the images.
How can I do this?

## ScreenShots
![image](https://user-images.githubusercontent.com/24429607/58478273-4e2d2080-815e-11e9-80ed-1d7a4897ec04.png)

**Comment by adriancmurray** [comment]
AssetPathEntity is exactly that.

**Comment by Shtibel** [comment]
thank you !

**Comment by at-dinhtruong** [comment]
@Shtibel Can you share me the `command` to get all images from gallery?tks

**Comment by Shtibel** [comment]
Hi @at-dinhtruong 

This is an old version, I was working on it way way back
Here is the code:

`
        
     if(this.platform.is('cordova')){

        console.log('<--- start: ', moment().format('HH:mm:ss'));

        this.library = [];

        this.albums.push({
          id: '0',
          title: 'All images',
          images: []
        });

        this.photoLibrary.requestAuthorization().then(() => {
          //getAlbums
          this.photoLibrary.getAlbums().then((albums)=>{
            albums.forEach(album => {
              this.albums.push({
                id: album.id,
                title: album.title,
                images: []
              })
            });

            console.log('<--- getAlbums:', this.albums)

            this.albumsProvider.getAlbumData(this.albums);
            
            //get all images
            this.photoLibrary.getLibrary(this.libraryItemOptions).subscribe({
              next: (chunk) => {
                //console.log('chunk:', this.chunkNum, ', length:', chunk.length);
                //this.library = this.library.concat(chunk);
                this.library = chunk;
                
                this.library.forEach(libraryItem =>{
                  let _libraryItem = libraryItem;
                  let url = libraryItem.thumbnailURL

                  this.imageLoader.preload(url);

                  // add to all images
                  //console.log('<--- add to all images:', this.albums)
                  this.albums[0].images.push({
                    libraryItem: _libraryItem,
                    url: url,
                    imageCount: null
                  });

                  //add to album
                  let album = this.albums.find(x => x.id === _libraryItem.albumIds[0]);
                  if(typeof album !== 'undefined'){
                    album.images.push({
                      libraryItem: _libraryItem,
                      url: url,
                      imageCount: null
                    });
                  }
                        
                });
                
                console.log('<--- this.chunkNum: ', this.chunkNum);
                //if(this.chunkNum==1){
                  this.rootPage = 'HomePage';
                  
                  this.cd.detectChanges();
                //}
                this.chunkNum++;

                //console.log('current albums:', this.albums);    

                this.imagesProvider.getImageData(this.albums);
              },
              complete: () => {
                console.log('all done:', this.albums);
                console.log('<--- end: ', moment().format('HH:mm:ss'));
              }              
            });
          });
        })
      }else{
      }


`

**Comment by at-dinhtruong** [comment]
@Shtibel many thanks.
