### ISSUE TITLE
flutter run 执行报错

### ISSUE THREAD

**Issue by MrSong0607** [CaiJingLong/flutter_photo_manager#76]
注: /Users/melodysong/flutter/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-0.3.4/android/src/main/kotlin/top/kikt/imagescanner/PermissionsUtils.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

**Comment by CaiJingLong** [comment]
This is a warning, not a error, It doesn't affect run. 
If your compilation exits, it may be caused by something else.
