### ISSUE TITLE
我手机的照片都存在了苹果iCloud端，我在选中这张图片时很模糊，请问如何下载iCloud的图片呢

### ISSUE THREAD

**Issue by pc1995** [CaiJingLong/flutter_photo_manager#78]
我手机的照片都存在了苹果iCloud端，我在选中这张图片时很模糊，请问如何下载iCloud的图片呢？不知道有没有解决的办法吗？期待你的答复

**Comment by CaiJingLong** [comment]
这个库没有任何UI层级在内,所以你说的模糊不知道是从何而来.
支持iCloud, 使用asset的file属性

**Comment by pc1995** [comment]
> 这个库没有任何UI层级在内,所以你说的模糊不知道是从何而来.
> 支持iCloud, 使用asset的file属性 
为了初始加载速度快一点 var data = await entity.thumbDataWithSize(150, 150);这里size设置小一点的话，显示缩略图的时候就比较模糊

**Comment by pc1995** [comment]
> 这个库没有任何UI层级在内,所以你说的模糊不知道是从何而来.
> 支持iCloud, 使用asset的file属性

asset.file 吗，我知道啦，感谢感谢
