### ISSUE TITLE
渲染没有图片加载器，在grid里面会留白，体验很差。不知道你有什么建议呢

### ISSUE THREAD

**Issue by liuchuancong** [CaiJingLong/flutter_photo_manager#81]
我使用bloc去多选 虽然完成了但是体验很差，图片加载真的要很久，Fresco没有这种库，在flutter里面真的很不好

**Comment by CaiJingLong** [comment]
The `Android` of photo_manager send bitmap data loaded with glide to the flutter.

About UI , you can see [photo](https://github.com/CaiJingLong/flutter_photo) repository.

**Comment by liuchuancong** [comment]
it's perfect! thanks,I fix my perblem.
