### ISSUE TITLE
[BUG] 部分android手机拿不到视频信息

### ISSUE THREAD

**Issue by mcxinyu** [CaiJingLong/flutter_photo_manager#82]
部分android手机拿不到视频列表，例如小米4C（android6.0.1），应该是相册（Camera文件夹）没有扫描到。
请问此部分有解决办法么？

**Comment by CaiJingLong** [comment]
I don't know how to resolve the problem.

**Comment by CSystem** [comment]
@mcxinyu @CaiJingLong  I met the same problem.

**Comment by xpader** [comment]
同样有这个问题，部分机型获取不到视频，或者只能获取到很少一部分的视频。

**Comment by xpader** [comment]
Especially many old Huawei's phone, can not scan all videos.

**Comment by CaiJingLong** [comment]
I found the problem, I will fix it in #124 .

**Comment by CaiJingLong** [comment]
Next version will fix it.
