### ISSUE TITLE
Deprecated API usage

### ISSUE THREAD

**Issue by mhstoller** [CaiJingLong/flutter_photo_manager#84]
I'm not sure how to report this properly, as I'm not sure if it's considered a bug. When running the example app or adding the dependency to my own project the following warning is shown (Android 9):

Note: /development/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-0.3.4/android/src/main/kotlin/top/kikt/imagescanner/PermissionsUtils.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

**Comment by CaiJingLong** [comment]
This is a warning, because some APIs will be marked as obsolete in some android compiled versions, but these methods will not be removed and will not cause problems when used.
You can use it with confidence.

**Comment by mhstoller** [comment]
Closing for now. If the warning becomes an error, I will open a report.

This is a great library, thank you for creating it!
