### ISSUE TITLE
[BUG] Methods marked with @UiThread must be executed on the main thread.

### ISSUE THREAD

**Issue by korenzerah** [CaiJingLong/flutter_photo_manager#88]
**Describe the bug**
When calling await PhotoManager.getAssetPathList();, an exception is being thrown:
**java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-1**
**To Reproduce**
1. Call await PhotoManager.getAssetPathList();
2. See error

**Expected behavior**
Expected to receive assetpath list. It worked a while ago.

**Flutter version**
1.7.8+hotfix.4

**Smartphone (please complete the following information):**
 - Device: [OnePlus6]
 - OS: [Android 9]

**Log**

If applicable, add logs to help explain your problem.

```bash
> I/permission(22573): onGranted call.method = requestPermission
I/permission(22573): onGranted call.method = getGalleryIdList
I/K       (22573): num = 1555
I/K       (22573): num = 25204
E/AndroidRuntime(22573): FATAL EXCEPTION: pool-3-thread-1
E/AndroidRuntime(22573): Process: com.example.throwbackinstagram, PID: 22573
E/AndroidRuntime(22573): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-1
E/AndroidRuntime(22573): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(22573): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
E/AndroidRuntime(22573): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
E/AndroidRuntime(22573): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(22573): 	at top.kikt.imagescanner.ImageScanner$scanAndGetImageIdList$1.run(ImageScanner.kt:208)
E/AndroidRuntime(22573): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(22573): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(22573): 	at java.lang.Thread.run(Thread.java:764)
W/OPDiagnose(22573): getService:OPDiagnoseService NULL
D/OSTracker(22573): OS Event: crash
I/Process (22573): Sending signal. PID: 22573 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo_manager/blob/7f88aa6d857319233ad9e6f253f72a7da529b245/android/src/main/kotlin/top/kikt/imagescanner/ResultHandler.kt#L8-L38

Every method use `Handler.post` to reply the flutter. So I don't know what's your bug.

**Comment by korenzerah** [comment]
Hey,
Can't migrate because of AndroidX migration problems. Other packages that I use in the same project did not migrate therefore I can't upgrade this one as well.
