### ISSUE TITLE
[BUG] A resource failed to call close.

### ISSUE THREAD

**Issue by lifenautjoe** [CaiJingLong/flutter_photo_manager#92]
This is a critical bug. If files don't get properly closed, the app runs out of file descriptors and the previously opened files, are not retrieved when calling `PhotoManager.getAssetPathList();` again.

**Describe the bug**

I get the console error and the images are no longer retrieved after this
```
W/System  (32145): A resource failed to call close.
```

**To Reproduce**
1.
```
List<AssetPathEntity> list = await PhotoManager.getAssetPathList();
```

2.
```
AssetPathEntity data = list[0]; // 1st album in the list, typically the "Recent" or "All" album
List<AssetEntity> imageList = await data.assetList;
```

3.
```
AssetEntity entity = imageList[0];
```

4.
```
List<int> fileData = await entity.fullData; // image/video file bytes
```

5.
See
```
W/System  (32145): A resource failed to call close.
```

6. Retrieve assets again and see that the picked asset is missing now.

**Comment by CaiJingLong** [comment]
Now, I can't see the log.
