### ISSUE TITLE
明明在原生的代码里有 getThumbPath 的方法，却为什么要返回 Uint8List 这个呢？

### ISSUE THREAD

**Issue by xpader** [CaiJingLong/flutter_photo_manager#95]
要显示缩略图的时候必须用 Unit8List 来处理，远比直接读取文件慢的多，这里是出于什么考虑没有开放出来呢，我之前使用 media_picker_builder 的时候就是直接把缩略图路径暴露出来的。

**Comment by CaiJingLong** [comment]
ThumbPath is written for android, because this field is in the database, but later found that many models are empty.

At the same time, there is no corresponding field in ios, so the method is finally abandoned.

---
Compared to the file speed of Uint8List, I have not measured it, not evaluated.

**Comment by xpader** [comment]
我懂了。
基本上现在用 Unit8List 来保存文件得写一个 LRU Cache 来缓存，或者生成文件，显然生成文件缓存后期更快速。

**Comment by CaiJingLong** [comment]
Android uses glide to load images, ios uses PHPhone api, they has built-in cache.
