### ISSUE TITLE
[Feature] pagination support only images/video video/ all

### ISSUE THREAD

**Issue by CaiJingLong** [CaiJingLong/flutter_photo_manager#97]
Since paging is provided by third-party contributors, there is no support, so I plan to add support in the future.

- [x] support type.

**Comment by xpader** [comment]
Glad to hear that, and I think you may need to add a count number property for AssetPathEntity.
Now I want to get count number, must to `(await path).length`, with pagination support, that will be ugly.

**Comment by CaiJingLong** [comment]
> Glad to hear that, and I think you may need to add a count number property for AssetPathEntity.
> Now I want to get count number, must do `(await path).length`, with pagination support, that will be ugly.

Are you referring to the total number of photos in the album?

**Comment by xpader** [comment]
> > Glad to hear that, and I think you may need to add a count number property for AssetPathEntity.
> > Now I want to get count number, must do `(await path).length`, with pagination support, that will be ugly.
> 
> Are you referring to the total number of photos in the album?

Yes.

**Comment by CaiJingLong** [comment]
see #102 .
